package com.example.util

import com.example.data.model.AppLanguage

class FrenchAppStrings : AppStrings(AppLanguage.FRENCH) {
    // Navigation & Core
    override val navMarkets: String = "Cycle"
    override val navCoins: String = "Pièces"
    override val navSignals: String = "Bande"
    override val navSettings: String = "Paramètres"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO ACTIF"
    override val upgradeToPro: String = "Passer à Pro"
    override val searchPlaceholder: String = "Rechercher 100+ cryptos..."
    override val cryptocurrenciesCount: String = "CRYPTOMONNAIES"
    override val cryptocurrencySingular: String = "CRYPTOMONNAIE"
    override val rankPrefix: String = "Rang"
    override val closeButton: String = "Fermer"
    override val institutionalTerminal: String = "Terminal des Cycles et Dérivés"
    override val latencyMs: String = "%dms latence"
    override val realtimeFeed: String = "FLUX EN DIRECT"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Layer 1"
    override val catLayer2: String = "Layer 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "IA & Infra"
    override val catMeme: String = "Mèmes"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Utilité"
    override val catFavorites: String = "Favoris"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Aperçu du Marché"
    override val marketsSubtitle: String = "Où évolue chaque crypto, tendances historiques, projections futures & whitepapers."
    override val currentPrice: String = "Prix Actuel"
    override val analogMatch: String = "Correspondance Historique"
    override val cyclePhase: String = "Phase du Cycle"
    override val daysSinceAth: String = "Jours depuis l'ATH"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "ANALOGUE HISTORIQUE DU CYCLE"
    override val historicalAnalogProTitle: String = "Analogue Historique du Cycle"
    override val historicalAnalogProUnlockedDesc: String = "L'historique live et les mouvements réalisés sont actifs."
    override val historicalAnalogProDesc: String = "Débloquez les graphiques d'historique live et les cartes de mouvements réalisés."
    override val movementAnalysisHeader: String = "ANALYSE DU MOUVEMENT & HISTORIQUE DU CYCLE"
    override val nextMoveHeader: String = "MOUVEMENTS LIVE RÉALISÉS"
    override val cycleFractalLabel: String = "Jour Fractal du Cycle"
    override val historicalMatchLabel: String = "Comment le prix a bougé d'un halving au suivant"
    override val proAnalyticsDesc: String = "Débloquez les lignes 2016 et 2020 sur le même jour de cycle pour"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "STATISTIQUES DU MARCHÉ & OFFRE DE TOKENS"
    override val circulatingSupplyLabel: String = "Offre en Circulation :"
    override val circulatingShort: String = "En circulation"
    override val infiniteDeflationary: String = "Infinie (Déflationniste)"
    override val marketCapMetric: String = "CAPITALISATION"
    override val volume24hMetric: String = "VOLUME 24H"
    override val tradingVolumeSub: String = "Volume d'échange"
    override val fdvMetric: String = "FDV (VALORISATION)"
    override val fdvSub: String = "Valorisation entièrement diluée"
    override val athMetric: String = "PLUS HAUT HISTORIQUE (ATH)"
    override val atlMetric: String = "PLUS BAS HISTORIQUE (ATL)"
    override val drawdownAthMetric: String = "BAISSE DEPUIS L'ATH"
    override val fromPeakSub: String = "Depuis le sommet"
    override val allTimeLowMetric: String = "Plus bas historique"
    override val allTimeHighMetric: String = "Plus haut historique"
    override val startMetric: String = "Début"
    override val daysSinceHighMetric: String = "Jours depuis le sommet"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & PLAN TECHNOLOGIQUE"
    override val founderLabel: String = "CRÉATEUR / FONDATEUR"
    override val genesisDateLabel: String = "DATE DE GENÈSE"
    override val whatCoinDoesLabel: String = "Que fait la crypto (Core Whitepaper Blueprint)"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Émission"
    override val useCasesLabel: String = "Cas d'Usage Principaux de l'Écosystème"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Semaines depuis le record"
    override val cycleAnalysisHeader: String = "Analyse du cycle"
    override val fromHighToLowTitle: String = "DU SOMMET À UN CREUX POSSIBLE"
    override val daysAfterAthLabel: String = "jours après le sommet historique"
    override val daysToBottomLabel: String = "jours, corrections passées (moy.)"
    override val highMarker: String = "Haut"
    override val fromHighToLowDisclaimer: String = "C'est ce qu'ont fait les cycles passés. Pas une promesse — juste une horloge."
    override val thisCycleVsLastTitle: String = "CE CYCLE VS LES PRÉCÉDENTS"
    override val daysAfterHighTitle: String = "Jours après le sommet"
    override val nowLabel: String = "Maintenant"
    override val daysOfRiseTitle: String = "Jours de hausse, historiquement"
    override val daysOfRiseSub: String = "Les hausses passées du creux au sommet suivant ont duré environ 1059 jours."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "jours avant le prochain halving"
    override val halvingHoursLabel: String = "heures restantes"
    override val whyWeSayThisTitle: String = "Contexte Historique et Réserves sur le Cycle"

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Sélectionner un Actif"
    override val signalsAllCoins: String = "Toutes les 100+ Cryptos"
    override val timeframe1D: String = "1J"
    override val timeframe1W: String = "1S"
    override val timeframe1M: String = "1M"
    override val timeframe1Y: String = "1A"
    override val timeframeCycle: String = "Cycle Macro"
    override val signalBullish: String = "24h HAUSSE"
    override val signalBearish: String = "24h BAISSE"

    // Settings Screen
    override val settingsHeader: String = "Paramètres"
    override val languageTitle: String = "Langue"
    override val languageDesc: String = "Sélectionnez votre langue préférée"
    override val optionsTitle: String = "Options"
    override val soundEffectsTitle: String = "Effets Sonores Crypto (SFX)"
    override val soundEffectsSub: String = "Sons courts au toucher, aux bascules et à la navigation"
    override val soundTestTitle: String = "Tester les Effets Audio"
    override val soundTestLaunch: String = "Montée Gamme Majeure 🎵"
    override val soundTestClick: String = "Clic Tech"
    override val soundTestToggle: String = "Bip Commutateur"
    override val soundTestChime: String = "Carillon Récompense Crypto"
    override val logChartsTitle: String = "Graphiques Logarithmiques"
    override val logChartsSub: String = "Afficher les cours sur échelle logarithmique"
    override val proMembershipTitle: String = "Abonnement Pro"
    override val manageProSubscription: String = "Gérer l'abonnement Pro"
    override val proTapeTitle: String = "LECTURE DE BANDE PRO"
    override val proTapeDesc: String = "Débloquez la lecture live RSI, EMA, ATR, funding et ETF à partir des clôtures quotidiennes. Pas une prévision."
    override val proBenefit1: String = "Lignes 2016 et 2020 sur le même jour de cycle"
    override val proBenefit2: String = "Journal des chiffres live que l'app a montrés"
    override val proBenefit3: String = "Alerte optionnelle du jour de cycle qui ouvre le graphique"
    override val proBenefit4: String = "Bande live des clôtures, du funding et de l'ETF — pas une prévision"
    override val proBenefit5: String = "IA qui lit uniquement l'instantané à l'écran"
    override val proBenefit6: String = "Leçons en plus sur levier, funding et carnet — aucun ordre de trade"
    override val currencyDisplayTitle: String = "Devise d'Affichage"
    override val howWeReadItTitle: String = "Comment nous le lisons — en mots simples"
    override val plainItem1Title: String = "1. L'histoire se répète en cycles"
    override val plainItem1Desc: String = "Les cryptos suivent des cycles de halving d'environ 4 ans. Nous comparons aujourd'hui au même jour après les halvings de 2012, 2016 et 2020."
    override val plainItem2Title: String = "2. Analogues Historiques"
    override val plainItem2Desc: String = "Sur le graphique du cycle, la courbe violette est 2020, la courbe ambre 2016 et la ligne cyan le cycle actuel."
    override val plainItem3Title: String = "3. Zones Historiques du Cycle"
    override val plainItem3Desc: String = "Par régression logarithmique, nous calculons les zones historiques à des fins d'étude. Tous les outils sont éducatifs et ne constituent pas un conseil financier."
    override val plainItem4Title: String = "4. Whitepapers Fondamentaux"
    override val plainItem4Desc: String = "Chaque fiche inclut modèle de consensus, tokenomics, fondateurs et cas d'usage réels."
    override val plainItem5Title: String = "5. Avertissement sur les Risques"
    override val plainItem5Desc: String = "Les performances passées ne préjugent pas des résultats futurs. Investissez prudemment."
    override val privacyPolicyTitle: String = "Conditions d'utilisation et Politique de confidentialité"
    override val privacyPolicyView: String = "Consulter notre politique de confidentialité et de données"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Vous payez les lignes 2016/2020, le journal, l'alerte du jour, la bande live et les leçons en plus. Prix, cap, Fear & Greed et ETF 1 jour restent gratuits. Pas une prévision."
    override val proModalFeature1: String = "Lignes 2016 et 2020 sur le même jour de cycle"
    override val proModalFeature2: String = "Journal des chiffres live que l'app a montrés"
    override val proModalFeature3: String = "Alerte optionnelle du jour de cycle qui ouvre le graphique"
    override val proModalFeature4: String = "Bande live des clôtures, du funding et de l'ETF — pas une prévision"
    override val proModalFeature5: String = "IA qui lit uniquement l'instantané à l'écran"
    override val proModalFeature6: String = "Leçons en plus sur levier, funding et carnet — aucun ordre de trade"
    override val planMonthlyTitle: String = "Mensuel"
    override val planMonthlyPeriod: String = "/ mois"
    override val planAnnualTitle: String = "Annuel"
    override val planAnnualPeriod: String = "/ an"
    override val restorePurchases: String = "Restaurer les Achats"
    override val restoringPurchases: String = "Vérification des achats sur Google Play..."
    override val playTermsDisclosure: String = "Le paiement est débité de votre compte Google Play à la confirmation d'achat. L'abonnement est reconduit automatiquement sauf résiliation au moins 24 heures avant l'échéance."
    override val financialDisclaimerTitle: String = "Avertissement Financier et Réglementaire"
    override val financialDisclaimerText: String = "Histoire éducative des cycles passés. Pas une prévision et pas un conseil. CryptoCycles n'échange pas, ne conserve pas et n'ordonne pas d'acheter ou de vendre."
    override val privacySheetTitle: String = "Confidentialité CryptoCycles"
    override val privSection1Title: String = "1. Collecte de Données"
    override val privSection1Body: String = "Les signaux et fenêtres d'achat/vente sont des motifs historiques et ne constituent pas un conseil d'investissement."
    override val privSection2Title: String = "2. Mineurs"
    override val privSection2Body: String = "CryptoCycles ne s'adresse pas aux enfants de moins de 13 ans."
    override val privSection3Title: String = "3. Contact"
    override val privSection3Body: String = "Pour toute question sur la confidentialité, utilisez l'adresse e-mail indiquée sur Google Play."
    override val privSection4Title: String = "4. Stockage Local"
    override val privSection4Body: String = "CryptoCycles ne crée pas de comptes et ne vend pas de données personnelles. Toutes vos préférences restent stockées sur votre appareil."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO lignes de cycle et lecture de bande"
    override val signalsProLockedSubtitle: String = "Débloquez les superpositions 2016 et 2020 et la lecture des clôtures quotidiennes. Pas une prévision."
    override val signalsProLockedFeature2: String = "Lecture live (RSI, EMA, ATR des clôtures quotidiennes)"
    override val signalsProLockedFeature3: String = "Journal quotidien de ce que l'app a montré"
    override val signalsGateTitle: String = "Superpositions de cycle et lecture de bande"
    override val signalsGateDesc: String = "Débloquez les lignes 2016 et 2020 et la lecture live des clôtures. Pas un signal et pas une prévision."
    override val signalsGateBadge: String = "Clôtures live · funding live · ETF live"

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "BRIEFING MACRO HEBDOMADAIRE"
    override val weeklyBriefingSub: String = "Synthèse institutionnelle hebdomadaire du cycle & posture face au risque"
    override val weeklyBriefingCurrentZone: String = "Zone Macro Actuelle"
    override val weeklyBriefingActionTitle: String = "Posture Recommandée"
    override val weeklyBriefingReasonTitle: String = "Synthèse en 3 Points"
    override val weeklyBriefingProUnlockText: String = "Débloquez le Briefing Hebdomadaire institutionnel, le playbook de zones et les analogues macro avec Pro."

    override val historicalAnalogProUnlockText: String = "Débloquez les lignes 2016 et 2020 sur le même jour de cycle. Historique uniquement."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Alertes Push Cycles & Indicateurs"
    override val alertSettingsSub: String = "Notifications instantanées sur l'appareil pour les seuils de cycle critiques"
    override val alertZoneChangeTitle: String = "Alerte Changement de Zone"
    override val alertZoneChangeDesc: String = "Alerte quand la zone d'humeur du marché change (Peur, Neutre, Funding élevé, Extrême), selon Fear & Greed et le funding"
    override val alertPiCycleTitle: String = "Écart & Croisement Pi Cycle Top"
    override val alertPiCycleDesc: String = "Alerte quand la 111DMA arrive à 10 % de la 350DMA × 2, la croise ou s'en éloigne. Vérifié chaque jour"
    override val alertRainbowTitle: String = "Transition de Bande Rainbow"
    override val alertRainbowDesc: String = "Notification lorsque Bitcoin change de bande de valorisation Rainbow"
    override val alert200WTitle: String = "Distance au 200-Week SMA"
    override val alert200WDesc: String = "Alerte quand le prix passe sous la 200W SMA, à moins de 10 % au-dessus, ou à 2,5× au-dessus. Vérifié chaque jour"
    override val alertFreeLimitNotice: String = "La version gratuite inclut jusqu'à 2 alertes actives. Passez à Pro pour des alertes illimitées."
    override val alertProUnlockNotice: String = "Fonctionnalité PRO : Alertes push illimitées pour cycles, Pi Cycle et Rainbow."

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "GROS PRINTS BINANCE USDT-M (PRO)"
    override val whaleRadarSub: String = "Prints futures Binance USDT-M dès 100 k$. Pas des transferts on-chain."
    override val whaleNotificationsTitle: String = "Notifications Push Alertes Baleines"
    override val whaleNotificationsDesc: String = "Notification pour un seul trade Binance USDT-M futures au-dessus de votre taille, tant que l'app est ouverte."
    override val whaleNotificationsProLockedDesc: String = "Pro : alerte quand un print Binance USDT-M dépasse le filtre. Pas des transferts on-chain."
    override val whaleThresholdTitle: String = "Taille Minimale d'Alerte Baleine"
    override val whaleFilterAll: String = "Toutes les Baleines"
    override val whaleFilterInflow: String = "🔻 Grosses ventes"
    override val whaleFilterBuy: String = "🔺 Gros achats"
    override val whaleCollapse: String = "Réduire"
    override val whaleViewAll: String = "Voir tout (%d)"
    override val timeJustNow: String = "À l'instant"
    override val timeMinsAgo: String = "il y a %d min"
    override val timeHoursAgo: String = "il y a %d h"
    override val liveOrderFlowTitle: String = "24/7 LIVE FLUX D'ORDRES (BINANCE)"
    override val liveOrderFlowSub: String = "Gros prints Binance USDT-M sur les majeurs : pression achat vs vente"
    override val buyDominanceLabel: String = "PRESSION D'ACHAT"
    override val sellDominanceLabel: String = "PRESSION DE VENTE"
    override val liveExecutionFeed: String = "EXÉCUTIONS EN DIRECT"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Indices Macro & Cycles"
    override val macroScreenSubtitle: String = "Modèles de valorisation institutionnels, Rainbow power law & sentiment du marché"
    override val macroProLockedTitle: String = "Outils PRO d'historique de cycle"
    override val macroProLockedSubtitle: String = "Débloquez les bandes Rainbow, les croisements Pi Cycle et le briefing hebdomadaire. Pas un signal d'achat ou de vente."
    override val macroGateTitle: String = "Outils d'historique de cycle"
    override val macroGateDesc: String = "Bandes Rainbow, croisements Pi Cycle et faits hebdomadaires. Historique uniquement — pas un trade."

    override val macroRainbowBadge: String = "HISTOIRE"

    override val macroProLockedBadge: String = "🔒 Pro Verrouillé"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Altcoin Season Index"
    override val altSeasonSubtitle: String = "75% du Top 50 des cryptos surperformant Bitcoin sur 90 jours"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Zone Neutre"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val topPerformers90d: String = "Top 90J Performers vs BTC"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Fear & Greed Index"
    override val fearGreedSubtitle: String = "Sentiment du marché, euphorie & horloge d'accumulation"
    override val fearGreedYesterday: String = "Hier"
    override val fearGreedLastWeek: String = "Semaine Dernière"
    override val fearGreedLastMonth: String = "Mois Dernier"
    override val extremeFearLabel: String = "Peur Extrême"
    override val fearLabel: String = "Peur"
    override val neutralLabel: String = "Neutre"
    override val greedLabel: String = "Avidité"
    override val extremeGreedLabel: String = "Avidité Extrême"
    override val fearGreedAccumulationTip: String = "Lecture de sentiment en direct. Un score manquant s'affiche en tiret. Pas un ordre d'achat ou de vente."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Indicateurs Pi Cycle (Sommet & Creux)"
    override val piCycleSubtitle: String = "Sommet (111SMA vs 350SMA×2) & Creux (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (CROISEMENT HISTORIQUE)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BOTTOM (CROISEMENT HISTORIQUE)"
    override val piCycleDma111: String = "SMA 111 Jours"
    override val piCycleDma350x2: String = "SMA 350 Jours × 2 (Seuil de Sommet)"
    override val piCycleEma150: String = "EMA 150 Jours"
    override val piCycleSma471x0745: String = "SMA 471 Jours × 0.745 (Seuil de Plancher)"
    override val piCycleMa200w: String = "Plancher SMA 200 Semaines"
    override val piCycleStatusSafeText: String = "Phase d'Accumulation & d'Expansion (Zone Sûre)"
    override val piCycleStatusAlertText: String = "🚨 CROISEMENT PI CYCLE TOP DÉTECTÉ (Risque de Sommet de Cycle)"
    override val piCycleBottomStatusSafeText: String = "Au-dessus du Plancher Historique (Phase d'Expansion)"
    override val piCycleBottomStatusAlertText: String = "🚨 CROISEMENT PI CYCLE BOTTOM DÉTECTÉ (plancher historique)"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "TERMINAL FUTURES"
    override val futuresOfficialFeedsSub: String = "Flux officiels Binance USDT-M · Zéro données simulées"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "OBSOLÈTE"
    override val futuresStateOffline: String = "HORS-LIGNE"
    override val futuresStateUnavailable: String = "INDISPONIBLE"
    override val futuresLastMarkIndexTitle: String = "PRIX DERNIER / MARK / INDEX"
    override val futuresLastTradedPrice: String = "Dernier Prix Échangé"
    override val futuresMarkPrice: String = "Prix Mark"
    override val futuresIndexPrice: String = "Prix Index"
    override val futuresBasis: String = "Base (Mark - Index)"
    override val futuresHigh24h: String = "Haut 24h"
    override val futuresLow24h: String = "Bas 24h"
    override val futuresVolume24h: String = "Volume 24h (USDT)"
    override val futuresBboSpreadTitle: String = "MEILLEURE OFFRE / DEMANDE (BBO) & SPREAD"
    override val futuresBestBid: String = "MEILLEURE OFFRE (BID)"
    override val futuresBestAsk: String = "MEILLEURE DEMANDE (ASK)"
    override val futuresOrderbookSpread: String = "Spread du carnet d'ordres :"
    override val futuresPerpFundingTitle: String = "TAUX DE FINANCEMENT & COMPTE À REBOURS"
    override val futuresCurrentFundingRate: String = "Taux de Financement Actuel"
    override val futuresNextFundingIn: String = "Prochain Règlement dans"
    override val futuresApproxAprLabel: String = "APR Estimé (taux × 3 × 365) :"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (ACTUALISÉ TOUTES LES 15S)"
    override val futuresContracts: String = "contrats"
    override val futuresLiquidationsListening: String = "Écoute du flux de liquidations Binance en direct..."
    override val futuresLongLiq: String = "LIQUIDATION LONG (VENTE)"
    override val futuresShortLiq: String = "LIQUIDATION SHORT (ACHAT)"
    override val futuresTradesTapeTitle: String = "⚡ BANDE DE TRANSACTIONS EN TEMPS RÉEL"
    override val futuresTradesAwaiting: String = "En attente du flux de transactions..."
    override val futuresPriceHeader: String = "Prix (USDT)"
    override val futuresQtyHeader: String = "Qté"
    override val futuresTimeHeader: String = "Heure"
    override val futuresLockedTitle: String = "Paire Futures Pro Verrouillée"
    override val futuresLockedDesc: String = "%s (%s) fait partie du niveau Pro. Débloquez le carnet d'ordres complet, l'arbitrage de base et les données des perpetuals."
    override val futuresLockedButton: String = "Débloquer l'Accès Pro"
    override val futuresSizePrefix: String = "Taille :"

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "Analyste de Marché IA"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Intelligence en Temps Réel sur les Cycles, Futures & Baleines"
    override val aiPromptPlaceholder: String = "Posez une question sur le cycle BTC, funding, support, altseason..."
    override val aiAskButton: String = "Analyser"
    override val aiQuickActionCycle: String = "Cycle & Risque Halving"
    override val aiQuickActionFutures: String = "Financement & Flux de Levier"
    override val aiQuickActionWhales: String = "Accumulation des Baleines"
    override val aiQuickActionAltseason: String = "Disponibilité Altseason"
    override val aiDisclaimer: String = "Propulsé par les modèles Gemini IA & la télémétrie en temps réel. Ne constitue pas un conseil financier."
    override val aiThinking: String = "Analyse de la télémétrie et du carnet d'ordres en direct..."
    override val aiGreeting: String = "Je suis là. Que souhaitez-vous voir ?"
    override val aiClearHistory: String = "Effacer"
    override val aiLiveContextTag: String = "Flux en Direct Connectés"
    override val aiPromptPrefixCycle: String = "Analyse la phase actuelle du cycle de halving, le risque et les analogues historiques."
    override val aiPromptPrefixFutures: String = "Interprète les taux de funding actuels, l'open interest et les risques de liquidation sur les futures."
    override val aiPromptPrefixWhales: String = "Que révèlent les alertes récentes sur les mouvements de baleines concernant l'accumulation ou la distribution institutionnelle ?"
    override val aiPromptPrefixAltseason: String = "Évalue si les conditions de marché, la dominance du BTC et le sentiment favorisent une Altseason actuellement."
    override val backtestBadgeText: String = "Live whale radar · live order flow · live liquidations"
    override val derivativesRiskGuardrail: String = "Cet écran lit la bande des perpetuals. Ce n'est pas un desk et il ne dimensionne pas les positions."

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Couche Market Intelligence : Comment ça marche"
    override val marketIntelligenceInfoButton: String = "Qu'est-ce que c'est ?"
    override val marketIntelligenceConfidenceTitle: String = "Score de Confiance (ex. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Mesure la force quantitative du positionnement actuel sur les futures selon le volume, l'open interest et le momentum."
    override val marketIntelligenceRegimesHeader: String = "Régimes de Marché (Signification des signaux)"
    override val regimeShortSqueezeTitle: String = "Pression de Short Squeeze"
    override val regimeShortSqueezeDesc: String = "Des positions vendeuses massives sont piégées. Une hausse modeste peut déclencher des liquidations en cascade et de fortes pointes."
    override val regimeSpotAccumulationTitle: String = "Accumulation Spot"
    override val regimeSpotAccumulationDesc: String = "Absorption réelle d'achats au comptant plutôt qu'un effet de levier risqué. Révèle une structure de marché saine et durable."
    override val regimeBalancedConsolidationTitle: String = "Consolidation Équilibrée"
    override val regimeBalancedConsolidationDesc: String = "L'effet de levier des dérivés et la demande spot sont à l'équilibre, annonçant une évolution en range."
    override val marketIntelligenceTelemetryHeader: String = "Télémétrie Clé"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Capital total engagé dans les contrats dérivés actifs."
    override val telemetryFundingRateTitle: String = "Taux de Financement (Funding Rate)"
    override val telemetryFundingRateDesc: String = "Frais périodiques entre acheteurs et vendeurs. Des taux très positifs signalent des positions longues surendettées vulnérables."
    override val marketIntelligenceUnderstood: String = "Compris"
}
