package com.example.util

import com.example.data.model.AppLanguage

class FrenchAppStrings : AppStrings(AppLanguage.FRENCH) {
    // Navigation & Core
    override val navMarkets: String = "Marchés"
    override val navFutures: String = "Futures"
    override val navSignals: String = "Signaux"
    override val navSettings: String = "Paramètres"
    override val navMacro: String = "Macro"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO ACTIF"
    override val backToFree: String = "Retour au gratuit"
    override val upgradeToPro: String = "Passer à Pro"
    override val proRequired: String = "Pro requis"
    override val searchPlaceholder: String = "Rechercher 100+ cryptos..."
    override val cryptocurrenciesCount: String = "CRYPTOMONNAIES"
    override val cryptocurrencySingular: String = "CRYPTOMONNAIE"
    override val turboEngineActive: String = "Moteur Turbo actif"
    override val rankPrefix: String = "Rang"
    override val closeButton: String = "Fermer"
    override val institutionalTerminal: String = "Terminal des Cycles et Dérivés"
    override val trustBarFeed: String = "Flux Institutionnel : Carnet d'Ordres Direct"
    override val latencyMs: String = "%dms latence"
    override val realtimeFeed: String = "FLUX EN DIRECT"
    override val neutralPhase: String = "Phase Neutre"
    override val avg7d: String = "Moy. 7J"
    override val avg30d: String = "Moy. 30J"
    override val daysHigh: String = "j sommet"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Layer 1"
    override val catLayer2: String = "Layer 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "IA & Infra"
    override val catMeme: String = "Mèmes"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Utilité"
    override val catFavorites: String = "Favoris"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Aperçu du Marché"
    override val marketsHeadline: String = "100+ Actifs du Monde Réel & Blueprints de Cycles"
    override val marketsSubtitle: String = "Prix live, mouvements réalisés et whitepapers pour chaque actif."
    override val fromAth: String = "depuis l'ATH"
    override val tapForCycleAnalog: String = "Touchez pour les mouvements live, l’historique et le whitepaper"
    override val heroSubtitle: String = "ANALOGUE HISTORIQUE DU CYCLE"
    override val currentPrice: String = "Prix Actuel"
    override val analogMatch: String = "Marché live"
    override val cyclePhase: String = "Phase du Cycle"
    override val daysSinceAth: String = "Jours depuis l'ATH"
    override val tapToViewCycles: String = "Appuyez pour voir les cycles & le whitepaper"

    // Markets Screen Teaser Cards
    override val marketsOrderFlowTeaserTitle: String = "Flux d'Ordres & Profondeur Futures"
    override val marketsOrderFlowTeaserSummary: String = "Funding · OI · Liquidations 24h"
    override val marketsOrderFlowTeaserLocked: String = "Verrouillé"
    override val marketsOrderFlowTeaserLockedDesc: String = "Débloquez le flux de levier & liquidations en direct"
    override val marketsOrderFlowTeaserUnlockedDesc: String = "Échelle DOM en direct & Carnet d'ordres"
    override val marketsOrderFlowTeaserUpgrade: String = "Mettre à niveau →"
    override val marketsOrderFlowTeaserOpenFutures: String = "Ouvrir Futures →"
    override val marketsSignalsTeaserTitle: String = "Radar Baleines & Signaux Fractaux"
    override val marketsSignalsTeaserLiveTag: String = "FLUX EN DIRECT"
    override val marketsSignalsTeaserSample: String = "Radar baleine live à partir des gros prints d’exchange"
    override val marketsSignalsTeaserAccumulationTag: String = "ACCUMULATION"
    override val marketsSignalsTeaserSub: String = "Cartes de liquidation & fractales de cycle 2016/2020"
    override val marketsSignalsTeaserOpen: String = "Ouvrir l'onglet Signaux →"
    override val marketsMacroTeaserNextEvent: String = "Ouvrir Macro pour DXY, rendements, ETF et stables en live"
    override val marketsMacroTeaserOpen: String = "Ouvrir Macro →"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "ANALOGUE HISTORIQUE DU CYCLE"
    override val historicalAnalogProUnlockedTitle: String = "Analyse de Cycle Pro Débloquée"
    override val historicalAnalogProTitle: String = "Analogue Historique du Cycle"
    override val historicalAnalogProUnlockedDesc: String = "Courbes analogues complètes & objectifs de prix sont actifs."
    override val historicalAnalogProDesc: String = "Débloquez les dates correspondantes et trajectoires pour toutes les cryptos."
    override val historicalAnalogManagePro: String = "Gérer Pro"
    override val historicalAnalogProPrice: String = "Débloquer Pro (3,99 €/mois)"
    override val movementAnalysisHeader: String = "ANALYSE DU MOUVEMENT & HISTORIQUE DU CYCLE"
    override val whereItMovesNowLabel: String = "Où il évolue actuellement :"
    override val whereItMovedPastLabel: String = "Où il a évolué lors des cycles passés :"
    override val nextMoveHeader: String = "MOUVEMENTS LIVE RÉALISÉS"
    override val cycleFractalLabel: String = "Jour Fractal du Cycle"
    override val historicalMatchLabel: String = "Correspondance de Modèle Historique"
    override val target1w: String = "1 Semaine"
    override val target2w: String = "2 Semaines"
    override val target4w: String = "4 Semaines"
    override val strategyGuideTitle: String = "📖 Guide Stratégique : Quand Acheter & Vendre"
    override val buyMomentTitle: String = "🟢 Meilleur Moment pour ACHETER (Accumulation)"
    override val buyMomentRules: String = "1. Lorsque le prix du Bitcoin touche ou s'approche du plancher 200W MA (<15% d'écart). Cela marque les creux historiques de cycle.\n2. Lorsque le 111 DMA est nettement sous (>40%) le 350 DMA x 2. Risque baissier minimal avec gain maximal (DCA In)."
    override val sellMomentTitle: String = "🔴 Meilleur Moment pour VENDRE (Sommet de Cycle)"
    override val sellMomentRules: String = "1. Lorsque le 111 DMA croise au-dessus du 350 DMA x 2. Cela signale une forte probabilité de sommet de cycle.\n2. Lorsque le Rainbow Chart entre dans les zones rouges 'Maximum Bubble'. L'historique montre que des baisses massives suivent (90%+ pour les altcoins)."
    override val rainbowFeatureLabel: String = "🌈 Bitcoin Rainbow Chart (Modèle Power Law Dynamique)"
    override val altSeasonFeatureLabel: String = "⚡ Altcoin Season Index (0-100) & Top 50 Performers"
    override val piCycleFeatureLabel: String = "🎯 Pi Cycle Top & Plancher 200W MA (Règles d'Achat/Vente)"
    override val fearGreedFeatureLabel: String = "😱 Fear & Greed Analyse Multi-Périodes du Sentiment"
    override val proAnalyticsTitle: String = "Analyse de Cycle Pro"
    override val proAnalyticsDesc: String = "Débloquez les comparaisons complètes 2020 & 2016 et projections pour"
    override val proAnalyticsButton: String = "Débloquer Pro (3,99 €/mois)"
    override val projectedPeakLabel: String = "ATH"
    override val projectedBottomLabel: String = "ATL"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "STATISTIQUES DU MARCHÉ & OFFRE DE TOKENS"
    override val circulatingSupplyLabel: String = "Offre en Circulation :"
    override val circulatingShort: String = "En circulation"
    override val infiniteDeflationary: String = "Infinie (Déflationniste)"
    override val marketCapMetric: String = "CAPITALISATION"
    override val volume24hMetric: String = "VOLUME 24H"
    override val tradingVolumeSub: String = "Volume d'échange"
    override val fdvMetric: String = "FDV (VALORISATION)"
    override val fdvSub: String = "Valorisation entièrement diluée"
    override val athMetric: String = "PLUS HAUT HISTORIQUE (ATH)"
    override val atlMetric: String = "PLUS BAS HISTORIQUE (ATL)"
    override val drawdownAthMetric: String = "BAISSE DEPUIS L'ATH"
    override val fromPeakSub: String = "Depuis le sommet"
    override val allTimeLowMetric: String = "Plus bas historique"
    override val allTimeHighMetric: String = "Plus haut historique"
    override val startMetric: String = "Début"
    override val liveYearsMetric: String = "6443j · 17.64 ans actif"
    override val daysSinceHighMetric: String = "Jours depuis le sommet"
    override val dropFromHighMetric: String = "-36.0% de baisse depuis le sommet"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & PLAN TECHNOLOGIQUE"
    override val founderLabel: String = "CRÉATEUR / FONDATEUR"
    override val genesisDateLabel: String = "DATE DE GENÈSE"
    override val whatCoinDoesLabel: String = "Que fait la crypto (Core Whitepaper Blueprint)"
    override val consensusLabel: String = "Mécanisme de Consensus & Architecture"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Émission"
    override val useCasesLabel: String = "Cas d'Usage Principaux de l'Écosystème"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Semaine correspondante historiquement baissière (Échantillon : n=2 cycles)"
    override val weekOfFallSub: String = "semaine 46 · typiquement 16 sem."
    override val cycleAnalysisHeader: String = "Analyse du cycle"
    override val fromHighToLowTitle: String = "DU SOMMET À UN CREUX POSSIBLE"
    override val daysAfterAthLabel: String = "jours après le sommet historique"
    override val daysToBottomLabel: String = "jours avant un creux possible"
    override val highMarker: String = "Haut"
    override val typical383dMarker: String = "typique 383j"
    override val lowMarker: String = "Bas"
    override val fromHighToLowNarrative: String = "Nous sommes à 319 jours du sommet historique. Historiquement, du sommet au creux cela prenait environ 383 jours. Il reste environ 64 jours pour un creux possible."
    override val fromHighToLowDetails: String = "06 oct 2025 · \$124,752.53 · -36.0% depuis le sommet"
    override val fromHighToLowDisclaimer: String = "C'est ce qu'ont fait les cycles passés. Pas une promesse — juste une horloge."
    override val thisCycleVsLastTitle: String = "CE CYCLE VS LES PRÉCÉDENTS"
    override val daysAfterHighTitle: String = "Jours après le sommet"
    override val daysAfterHighSub: String = "Nous sommes à 319 jours du sommet. Les baisses passées vers le creux ont duré environ 383 jours."
    override val nowLabel: String = "Maintenant"
    override val daysOfRiseTitle: String = "Jours de hausse, historiquement"
    override val daysOfRiseSub: String = "Les hausses passées du creux au sommet suivant ont duré environ 1059 jours."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "jours avant le prochain halving"
    override val halvingHoursLabel: String = "heures restantes"
    override val whatCameNextTitle: String = "Ce qui s'est passé les jours correspondants des cycles précédents"
    override val timeframe1wk: String = "en 1 sem."
    override val timeframe2wk: String = "en 2 sem."
    override val timeframe4wk: String = "en 4 sem."
    override val winRate71: String = "Live 24h"
    override val winRate79: String = "Live sparkline"
    override val winRate86: String = "Depuis ATH"
    override val whyWeSayThisTitle: String = "Contexte Historique et Réserves sur le Cycle"
    override val whyPoint1: String = "Cette semaine du cycle ressemble au 28 juin 2018 — même phase, mouvement similaire."
    override val whyPoint2: String = "Nous avons examiné 14 semaines similaires dans le passé. Au cours des 4 semaines suivantes, le prix a augmenté 12 fois sur 14 (généralement +29.5%)."
    override val whyPoint3: String = "Nous sommes à la semaine 46 de baisse. Par le passé, une telle phase a duré environ 16 semaines."
    override val whyPoint4: String = "La position du cycle et les semaines historiques pointent toutes vers la zone verte."

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Sélectionner un Actif"
    override val signalsAllCoins: String = "Toutes les 100+ Cryptos"
    override val timeframe1D: String = "1J"
    override val timeframe1W: String = "1S"
    override val timeframe1M: String = "1M"
    override val timeframe1Y: String = "1A"
    override val timeframeCycle: String = "Cycle Macro"
    override val signalBullish: String = "EXPANSION HAUSSIÈRE (BULLISH)"
    override val signalBearish: String = "CORRECTION BAISSIÈRE (BEARISH)"
    override val signalAccumulation: String = "CASSE D'ACCUMULATION"
    override val signalConfidence: String = "Fréquence de référence historique"
    override val signalLiveFeed: String = "Flux en Direct CoinGecko • Ticks 1s"
    override val analogComparisonHeader: String = "SUPERPOSITION DE L'ACTION DES PRIX HISTORIQUE"
    override val analogExplanation: String = "Alignement de l'action des prix avec des dates de cycles antérieurs. Pas une prédiction."
    override val highAccuracyNotice: String = "Journal de référence historique de backtest"

    // Settings Screen
    override val settingsHeader: String = "Paramètres"
    override val languageTitle: String = "Langue"
    override val languageDesc: String = "Sélectionnez votre langue préférée"
    override val appearanceTitle: String = "Apparence"
    override val themeGalaxyDark: String = "Galaxy Dark (Par défaut)"
    override val themeGalaxyDarkSub: String = "Fond bleu profond OLED avec accents cyan"
    override val themePureBlack: String = "Noir Pur"
    override val themePureBlackSub: String = "Mode OLED noir absolu pour économiser la batterie"
    override val themeCleanWhite: String = "Blanc Épuré"
    override val themeCleanWhiteSub: String = "Thème clair pour les environnements très éclairés"
    override val optionsTitle: String = "Options"
    override val soundEffectsTitle: String = "Effets Sonores Crypto (SFX)"
    override val soundEffectsSub: String = "Retour haptique sur la navigation et les alertes"
    override val soundTestTitle: String = "Tester les Effets Audio"
    override val soundTestLaunch: String = "Montée Gamme Majeure 🎵"
    override val soundTestClick: String = "Clic Tech"
    override val soundTestToggle: String = "Bip Commutateur"
    override val soundTestChime: String = "Carillon Récompense Crypto"
    override val hideMemecoinsTitle: String = "Masquer les Memecoins"
    override val hideMemecoinsSub: String = "Afficher uniquement les projets fondamentaux à forte capitalisation"
    override val logChartsTitle: String = "Graphiques Logarithmiques"
    override val logChartsSub: String = "Afficher les cours sur échelle logarithmique"
    override val proMembershipTitle: String = "Abonnement Pro"
    override val proMembershipPrice: String = "3,99 € / mois · 34,99 € / an"
    override val proBenefit1: String = "Masterclass institutionnelle : Chapitres 18-22 (Macro, On-Chain & Quants)"
    override val proBenefit2: String = "Moteur de signaux Futures complet & Radar de levier des baleines"
    override val proBenefit3: String = "Modèles d'épuisement Pi Cycle Top/Bottom & Forward Audit Trail"
    override val proBenefit4: String = "Flux d'actualités en direct par crypto & Alpha en temps réel"
    override val proBenefit5: String = "Alertes push instantanées illimitées & Analogues de cycles historiques profonds"
    override val currencyDisplayTitle: String = "Devise d'Affichage"
    override val howWeReadItTitle: String = "Comment nous le lisons — en mots simples"
    override val plainItem1Title: String = "1. L'histoire se répète en cycles"
    override val plainItem1Desc: String = "Les cryptos suivent des cycles de halving d'environ 4 ans. Nous alignons l'évolution actuelle avec 2020 et 2016."
    override val plainItem2Title: String = "2. Analogues Historiques"
    override val plainItem2Desc: String = "La courbe orange montre 2020 ; la courbe cyan 2016. La ligne blanche est votre trajectoire actuelle."
    override val plainItem3Title: String = "3. Zones Historiques du Cycle"
    override val plainItem3Desc: String = "Par régression logarithmique, nous calculons les zones historiques à des fins d'étude. Tous les outils sont éducatifs et ne constituent pas un conseil financier."
    override val plainItem4Title: String = "4. Whitepapers Fondamentaux"
    override val plainItem4Desc: String = "Chaque fiche inclut modèle de consensus, tokenomics, fondateurs et cas d'usage réels."
    override val plainItem5Title: String = "5. Avertissement sur les Risques"
    override val plainItem5Desc: String = "Les performances passées ne préjugent pas des résultats futurs. Investissez prudemment."
    override val privacyPolicyTitle: String = "Conditions d'utilisation et Politique de confidentialité"
    override val privacyPolicyView: String = "Consulter notre politique de confidentialité et de données"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Débloquez les analogues de cycle, alertes et analyses complètes. Résiliez à tout moment."
    override val proModalFeature1: String = "Masterclass institutionnelle : Chapitres 18-22 (Macro, On-Chain & Quants)"
    override val proModalFeature2: String = "Moteur de signaux Futures complet & Radar de levier des baleines"
    override val proModalFeature3: String = "Modèles d'épuisement Pi Cycle Top/Bottom & Forward Audit Trail"
    override val proModalFeature4: String = "Flux d'actualités en direct par crypto & Alpha en temps réel"
    override val proModalFeature5: String = "Alertes push instantanées illimitées & Analogues de cycles historiques profonds"
    override val proModalFeature6: String = "Alertes push instantanées illimitées & Analogues de cycles historiques profonds"
    override val planMonthlyTitle: String = "Mensuel"
    override val planMonthlyPrice: String = "3,99 €"
    override val planMonthlyPeriod: String = "/ mois"
    override val planMonthlyBadge: String = "Essai gratuit 7 jours"
    override val planAnnualTitle: String = "Annuel"
    override val planAnnualPrice: String = "34,99 €"
    override val planAnnualPeriod: String = "/ an"
    override val planAnnualBadge: String = "Offre Launch 40% • ~2,91 €/mois"
    override val subscribeProBtn: String = "Démarrer l'essai gratuit de 7 jours"
    override val startFreeTrialBtn: String = "Démarrer l'essai gratuit de 7 jours"
    override val startFreeTrialSub: String = "7 jours gratuits, puis 3,99 € / mois. Résiliation à tout moment."
    override val continueYearlyBtn: String = "Continuer avec Annuel (34,99 €/an)"
    override val continueYearlySub: String = "Accès Pro Immédiat • 34,99 € facturé annuellement (~2,91 €/mois)"
    override val restorePurchases: String = "Restaurer les Achats"
    override val restoringPurchases: String = "Vérification des achats sur Google Play..."
    override val cancelAnytime: String = "Résiliez à tout moment sur Google Play"
    override val playTermsDisclosure: String = "Le paiement est débité de votre compte Google Play à la confirmation d'achat. L'abonnement est reconduit automatiquement sauf résiliation au moins 24 heures avant l'échéance."
    override val financialDisclaimerTitle: String = "Avertissement Financier et Réglementaire"
    override val financialDisclaimerText: String = "CryptoCycles est fourni exclusivement à des fins éducatives et d'analyse historique. Tous les outils de cycle, projections Rainbow et analogues de halving sont éducatifs et NE constituent PAS un conseil financier ou d'investissement. Nous ne promettons ni ne garantissons de sommets de cycle ou d'objectifs de cours. Faites toujours vos propres recherches (DYOR)."
    override val privacySheetTitle: String = "Confidentialité CryptoCycles"
    override val privacyLastUpdated: String = "Dernière mise à jour : 2026"
    override val privSection1Title: String = "1. Collecte de Données"
    override val privSection1Body: String = "Les signaux et fenêtres d'achat/vente sont des motifs historiques et ne constituent pas un conseil d'investissement."
    override val privSection2Title: String = "2. Mineurs"
    override val privSection2Body: String = "CryptoCycles ne s'adresse pas aux enfants de moins de 13 ans."
    override val privSection3Title: String = "3. Contact"
    override val privSection3Body: String = "Pour toute question sur la confidentialité, utilisez l'adresse e-mail indiquée sur Google Play."
    override val privSection4Title: String = "4. Stockage Local"
    override val privSection4Body: String = "CryptoCycles ne crée pas de comptes et ne vend pas de données personnelles. Toutes vos préférences restent stockées sur votre appareil."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO Signaux Macro & Vagues de Halving"
    override val signalsProLockedSubtitle: String = "Débloquez les blueprints institutionnels de cycles macro, les analogues historiques de halving 2020 & 2016, et les alertes radar baleines en direct."
    override val signalsProLockedFeature1: String = "Analogues de Halving Historiques (superpositions de vagues 2020 & 2016)"
    override val signalsProLockedFeature2: String = "Algorithmes Grok ZigZag pour identifier sommets & corrections"
    override val signalsProLockedFeature3: String = "Fenêtres temporelles pour objectifs de sommet & accumulation au creux"
    override val signalsProLockedFeature4: String = "Notifications Push Radar Baleines pour les ordres majeurs de $10M+"

    // Zone Playbook Strings
    override val zonePlaybookTitle: String = "PLAYBOOK DES ZONES DU CYCLE"
    override val zonePlaybookSub: String = "Guide éducatif de gestion du risque selon les zones macro"
    override val zoneGreenAction: String = "Zone Verte • Entrée Progressive (Accumuler)"
    override val zoneGreenDesc: String = "Ratio risque/rendement historiquement favorable. Dollar-cost averaging systématique sur les actifs clés."
    override val zoneYellowAction: String = "Zone Jaune • Conserver & Rééquilibrer"
    override val zoneYellowDesc: String = "Zone de valorisation intermédiaire. Conserver ses positions existantes, éviter les réactions impulsives."
    override val zoneRedAction: String = "Zone Rouge • Sortie Progressive (Réduire le Risque)"
    override val zoneRedDesc: String = "Zone de valorisation en surachat. Historiquement sage de prendre des bénéfices partiels et protéger son capital."
    override val zonePlaybookDisclaimer: String = "À des fins d'étude et éducatives uniquement. Aucun conseil financier."

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "BRIEFING MACRO HEBDOMADAIRE"
    override val weeklyBriefingSub: String = "Synthèse institutionnelle hebdomadaire du cycle & posture face au risque"
    override val weeklyBriefingCurrentZone: String = "Zone Macro Actuelle"
    override val weeklyBriefingActionTitle: String = "Posture Recommandée"
    override val weeklyBriefingActionAccumulate: String = "ACCUMULER"
    override val weeklyBriefingActionHold: String = "CONSERVER"
    override val weeklyBriefingActionReduce: String = "RÉDUIRE"
    override val weeklyBriefingReasonTitle: String = "Synthèse en 3 Points"
    override val weeklyBriefingLine1: String = "1. Les métriques de valorisation macro restent positionnées dans le corridor inférieur d'accumulation."
    override val weeklyBriefingLine2: String = "2. Le plancher 200W SMA et la dynamique d'offre du halving continuent d'offrir un soutien structurel de long terme."
    override val weeklyBriefingLine3: String = "3. L'accumulation sur les portefeuilles on-chain indique une absorption soutenue pendant les consolidations."
    override val weeklyBriefingProUnlockText: String = "Débloquez le Briefing Hebdomadaire institutionnel, le playbook de zones et les analogues macro avec Pro."

    // Historical Analog Card Strings
    override val historicalAnalogCardTitle: String = "ANALOGUE HISTORIQUE DU CYCLE"
    override val historicalAnalogPhaseText: String = "Nous sommes dans la même phase de cycle que le %s."
    override val historicalAnalogFollowThrough: String = "Après ce point, l'évolution typique a été : 30j : %s • 90j : %s • 180j : %s"
    override val historicalAnalogNotFinancialAdvice: String = "Modèle éducatif basé sur l'historique fractal de 2016 & 2020. Pas de conseil financier."
    override val historicalAnalogProUnlockText: String = "Débloquez les courbes fractales de l'analogue historique et les trajectoires 30/90/180 jours."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Alertes Push Cycles & Indicateurs"
    override val alertSettingsSub: String = "Notifications instantanées sur l'appareil pour les seuils de cycle critiques"
    override val alertZoneChangeTitle: String = "Alerte Changement de Zone"
    override val alertZoneChangeDesc: String = "Notification lorsque Bitcoin transite entre les zones Verte, Jaune et Rouge"
    override val alertPiCycleTitle: String = "Écart & Croisement Pi Cycle Top"
    override val alertPiCycleDesc: String = "Notification lorsque l'écart entre 111DMA et 350DMA x 2 se resserre ou croise"
    override val alertRainbowTitle: String = "Transition de Bande Rainbow"
    override val alertRainbowDesc: String = "Notification lorsque Bitcoin change de bande de valorisation Rainbow"
    override val alert200WTitle: String = "Distance au 200-Week SMA"
    override val alert200WDesc: String = "Notification lorsque le cours s'approche ou dévie significativement du 200W SMA"
    override val alertFreeLimitNotice: String = "La version gratuite inclut jusqu'à 2 alertes actives. Passez à Pro pour des alertes illimitées."
    override val alertProUnlockNotice: String = "Fonctionnalité PRO : Alertes push illimitées pour cycles, Pi Cycle et Rainbow."

    // Widget Strings
    override val widgetSettingsTitle: String = "Widget Écran d'Accueil"
    override val widgetSettingsDesc: String = "Affichez la zone de cycle actuelle, le cours du BTC et les jours depuis l'ATH sur votre écran d'accueil"
    override val widgetZoneLabel: String = "Zone"
    override val widgetBtcPriceLabel: String = "Prix BTC"
    override val widgetDaysSinceAthLabel: String = "Jours Depuis ATH"

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "RADAR BALEINES & GRANDS MOUVEMENTS ON-CHAIN (PRO)"
    override val whaleRadarSub: String = "Télémétrie en temps réel des flux de portefeuilles et d'échanges institutionnels ($10M+)"
    override val whaleNotificationsTitle: String = "Notifications Push Alertes Baleines"
    override val whaleNotificationsDesc: String = "Recevez des alertes instantanées lors d'achats massifs de baleines ou de transferts vers les échanges."
    override val whaleNotificationsProLockedDesc: String = "Fonctionnalité PRO exclusive. Alertes push en direct pour les transferts majeurs ($10M+)."
    override val whaleThresholdTitle: String = "Taille Minimale d'Alerte Baleine"
    override val whaleFilterAll: String = "Toutes les Baleines"
    override val whaleFilterInflow: String = "🚨 Entrées / Ventes"
    override val whaleFilterOutflow: String = "🟢 Accumulation"
    override val whaleFilterBuy: String = "🚀 Méga Achats"
    override val whaleCollapse: String = "Réduire"
    override val whaleViewAll: String = "Voir tout (%d)"
    override val timeJustNow: String = "À l'instant"
    override val timeMinsAgo: String = "il y a %d min"
    override val timeHoursAgo: String = "il y a %d h"
    override val liveOrderFlowTitle: String = "24/7 LIVE FLUX D'ORDRES (BINANCE)"
    override val liveOrderFlowSub: String = "Flux tick en temps réel : Oscillateur pression achat vs vente"
    override val buyDominanceLabel: String = "PRESSION D'ACHAT"
    override val sellDominanceLabel: String = "PRESSION DE VENTE"
    override val netVolumeDelta: String = "FLUX NET 24H"
    override val liveExecutionFeed: String = "EXÉCUTIONS EN DIRECT"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Indices Macro & Cycles"
    override val macroScreenSubtitle: String = "Modèles de valorisation institutionnels, Rainbow power law & sentiment du marché"
    override val macroUpdated4m: String = "Mis à jour il y a 4 min"
    override val macroProLockedTitle: String = "Suite PRO Macro & Rainbow Chart"
    override val macroProLockedSubtitle: String = "Débloquez la valorisation dynamique Bitcoin Rainbow, l'index Altcoin Season 90 jours, Fear & Greed et les indicateurs Pi Cycle Top."

    // Macro Filters
    override val macroFilterAll: String = "Tous les Indices"
    override val macroFilterEconomicCalendar: String = "📅 Calendrier NFP & CPI"
    override val macroFilterRiskBackdrop: String = "🌐 DXY, 10Y & FedWatch"
    override val macroFilterRainbow: String = "🌈 Rainbow Chart"
    override val macroFilterAltSeason: String = "⚡ Alt Season"
    override val macroFilterFearGreed: String = "😱 Fear & Greed"
    override val macroFilterPiCycle: String = "🎯 Pi Cycle & 200W"

    // Macro Economic Calendar & Risk Cards
    override val macroEconomicCalendarCardTitle: String = "📅 Données Économiques & NFP / CPI"
    override val macroEconomicCalendarCardSub: String = "Prochain : Emploi US (NFP) Vendredi 15:30 UTC"
    override val macroNfpFridayBadge: String = "NFP VENDREDI"
    override val macroRiskBackdropCardTitle: String = "🌐 DXY, Rendements 10Y & FedWatch"
    override val macroRiskBackdropCardSub: String = "Liquidité Mondiale en USD & Rendements Souverains"
    override val macroRiskBackdropBadge: String = "CADRE MACRO"
    override val macroRainbowCardTitle: String = "🌈 Modèle de Prix Bitcoin Rainbow"
    override val macroRainbowCardSub: String = "Bandes de Valorisation Logarithmiques"
    override val macroRainbowBadge: String = "HOLD / DCA"
    override val macroAltSeasonCardTitle: String = "⚡ Altcoin Season Index"
    override val macroAltSeasonCardSub: String = "42/100 · Zone Neutre (Bitcoin Season)"
    override val macroFearGreedCardTitle: String = "😱 Fear & Greed Index"
    override val macroFearGreedCardSub: String = "68/100 · Sentiment d'Avidité"

    override val macroUsJobsTitle: String = "Emploi US : Non-Farm Payrolls (NFP)"
    override val macroUsJobsTime: String = "Vendredi 15:30 UTC"
    override val macroCpiTitle: String = "Indice des Prix à la Consommation US (CPI)"
    override val macroCpiTime: String = "Mercredi prochain 13:30 UTC"
    override val macroForecastLabel: String = "Prévision"
    override val macroPreviousLabel: String = "Précédent"
    override val macroVolatilityLabel: String = "Volatilité"
    override val macroConsensusYoyLabel: String = "Consensus YoY"
    override val macroPriorYoyLabel: String = "Précédent YoY"
    override val macroProOnly: String = "🔒 Pro Uniquement"
    override val macroProHigh: String = "🔒 Élevée"
    override val macroProLockedBadge: String = "🔒 Pro Verrouillé"

    override val macroFedWatchTitle: String = "CME FedWatch : Probabilité de Baisse des Taux"
    override val macroDxyTitle: String = "DXY : Indice du Dollar US"
    override val macroUs10yTitle: String = "US 10Y : Rendement des Bons du Trésor US à 10 ans"
    override val macroBrentTitle: String = "Pétrole Brut Brent"

    // Rainbow Chart Strings
    override val rainbowHeaderTitle: String = "Bitcoin Rainbow Chart"
    override val rainbowHeaderSubtitle: String = "Graphique Dynamique Rainbow"
    override val rainbowFormulaTag: String = "Power Law Dynamique (Ajustement R² 94.3%)"
    override val rainbowDescription: String = "Modèle dynamique de régression logarithmique Power Law couvrant l'historique complet du Bitcoin depuis 2012."
    override val rainbowCurrentBandLabel: String = "Bande de Valorisation Actuelle"
    override val rainbowCyclePeakTarget: String = "Objectif Sommet de Cycle"
    override val rainbowFireSaleTarget: String = "Plancher de Braderie (Fire Sale)"
    override val rainbowFilterAll: String = "Toutes les Bandes"
    override val rainbowInspectHelp: String = "Touchez et faites glisser sur le graphique pour examiner les cours & bandes historiques"
    override val halvingVerticalLabel: String = "Halving"
    override val halving2032Est: String = "Halving 2032 (Estimé)"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Altcoin Season Index"
    override val altSeasonSubtitle: String = "75% du Top 50 des cryptos surperformant Bitcoin sur 90 jours"
    override val altSeasonScoreLabel: String = "Score Altcoin Season"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Zone Neutre"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val altSeasonOutperformedCount: String = "%d sur %d cryptos ont battu le BTC"
    override val topPerformers90d: String = "Top 90J Performers vs BTC"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Fear & Greed Index"
    override val fearGreedSubtitle: String = "Sentiment du marché, euphorie & horloge d'accumulation"
    override val fearGreedNow: String = "Aujourd'hui"
    override val fearGreedYesterday: String = "Hier"
    override val fearGreedLastWeek: String = "Semaine Dernière"
    override val fearGreedLastMonth: String = "Mois Dernier"
    override val extremeFearLabel: String = "Peur Extrême"
    override val fearLabel: String = "Peur"
    override val neutralLabel: String = "Neutre"
    override val greedLabel: String = "Avidité"
    override val extremeGreedLabel: String = "Avidité Extrême"
    override val fearGreedAccumulationTip: String = "Historiquement, les valeurs sous 25 (Peur Extrême) représentent des fenêtres d'accumulation macro optimales."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Indicateurs Pi Cycle (Sommet & Creux)"
    override val piCycleSubtitle: String = "Sommet (111SMA vs 350SMA×2) & Creux (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (SOMMET / SIGNAL DE VENTE)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BOTTOM (PLANCHER / SIGNAL D'ACHAT)"
    override val piCycleDma111: String = "SMA 111 Jours"
    override val piCycleDma350x2: String = "SMA 350 Jours × 2 (Seuil de Sommet)"
    override val piCycleEma150: String = "EMA 150 Jours"
    override val piCycleSma471x0745: String = "SMA 471 Jours × 0.745 (Seuil de Plancher)"
    override val piCycleMa200w: String = "Plancher SMA 200 Semaines"
    override val piCycleDistanceToCross: String = "Distance au Croisement Pi Top"
    override val piCycleDistanceToBottomCross: String = "Distance au Croisement du Creux"
    override val piCycleStatusSafeText: String = "Phase d'Accumulation & d'Expansion (Zone Sûre)"
    override val piCycleStatusAlertText: String = "🚨 CROISEMENT PI CYCLE TOP DÉTECTÉ (Risque de Sommet de Cycle)"
    override val piCycleBottomStatusSafeText: String = "Au-dessus du Plancher Historique (Phase d'Expansion)"
    override val piCycleBottomStatusAlertText: String = "🚨 CROISEMENT PI CYCLE BOTTOM DÉTECTÉ (Achat Plancher Historique)"
    override val piCycleGenerationalSupport: String = "Support Historique Générationnel"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "TERMINAL FUTURES"
    override val futuresOfficialFeedsSub: String = "Flux officiels Binance USDT-M · Zéro données simulées"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "OBSOLÈTE"
    override val futuresStateOffline: String = "HORS-LIGNE"
    override val futuresStateUnavailable: String = "INDISPONIBLE"
    override val futuresLastMarkIndexTitle: String = "PRIX DERNIER / MARK / INDEX"
    override val futuresLastTradedPrice: String = "Dernier Prix Échangé"
    override val futuresMarkPrice: String = "Prix Mark"
    override val futuresIndexPrice: String = "Prix Index"
    override val futuresBasis: String = "Base (Mark - Index)"
    override val futuresHigh24h: String = "Haut 24h"
    override val futuresLow24h: String = "Bas 24h"
    override val futuresVolume24h: String = "Volume 24h (USDT)"
    override val futuresBboSpreadTitle: String = "MEILLEURE OFFRE / DEMANDE (BBO) & SPREAD"
    override val futuresBestBid: String = "MEILLEURE OFFRE (BID)"
    override val futuresBestAsk: String = "MEILLEURE DEMANDE (ASK)"
    override val futuresOrderbookSpread: String = "Spread du carnet d'ordres :"
    override val futuresPerpFundingTitle: String = "TAUX DE FINANCEMENT & COMPTE À REBOURS"
    override val futuresCurrentFundingRate: String = "Taux de Financement Actuel"
    override val futuresNextFundingIn: String = "Prochain Règlement dans"
    override val futuresApproxAprLabel: String = "APR Estimé (taux × 3 × 365) :"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (ACTUALISÉ TOUTES LES 15S)"
    override val futuresContracts: String = "contrats"
    override val futuresNoOpenInterest: String = "Aucune donnée d'open interest"
    override val futuresFearGreed5m: String = "Peur & Avidité (5m)"
    override val futuresBtcDominance60s: String = "Dominance BTC (60s)"
    override val futuresLiquidationsTapeTitle: String = "🚨 Ordres Forcés Binance (Liquidations)"
    override val futuresLiquidationsListening: String = "Écoute du flux de liquidations Binance en direct..."
    override val futuresCaptured: String = "capturées"
    override val futuresLongLiq: String = "LIQUIDATION LONG (VENTE)"
    override val futuresShortLiq: String = "LIQUIDATION SHORT (ACHAT)"
    override val futuresTradesTapeTitle: String = "⚡ BANDE DE TRANSACTIONS EN TEMPS RÉEL"
    override val futuresTradesAwaiting: String = "En attente du flux de transactions..."
    override val futuresPriceHeader: String = "Prix (USDT)"
    override val futuresQtyHeader: String = "Qté"
    override val futuresTimeHeader: String = "Heure"
    override val futuresLockedTitle: String = "Paire Futures Pro Verrouillée"
    override val futuresLockedDesc: String = "%s (%s) fait partie du niveau Pro. Débloquez le carnet d'ordres complet, l'arbitrage de base et les données des perpetuals."
    override val futuresLockedButton: String = "Débloquer l'Accès Pro"
    override val futuresProPair: String = "Paire Pro"
    override val futuresSizePrefix: String = "Taille :"

    // Structured 3-Line Metric Explainers (Headers & Micro-copy)
    override val explainerWhatItIsLabel: String = "Ce que c'est : "
    override val explainerWhatItShowsLabel: String = "Ce que cela montre : "
    override val explainerNotASignalLabel: String = "Pas un signal : "

    // Macro Metric Explainers
    override val explainerNfpWhat: String = "Variation mensuelle de l'emploi non agricole aux États-Unis, publiée par le Bureau of Labor Statistics."
    override val explainerNfpShows: String = "Tension sur le marché du travail et activité économique orientant directement les décisions de taux de la Fed."
    override val explainerNfpNotMean: String = "Contexte de liquidité macroéconomique pour les taux, pas un signal directionnel direct pour les cryptos."

    override val explainerCpiWhat: String = "Mesure clé de l'inflation suivant l'évolution moyenne des prix d'un panier de biens et services."
    override val explainerCpiShows: String = "Érosion du pouvoir d'achat des consommateurs et trajectoire vers l'objectif de 2% de la Fed."
    override val explainerCpiNotMean: String = "Contexte d'inflation globale, pas un déclencheur algorithmique d'exécution de marché."

    override val explainerFedWatchWhat: String = "Probabilité implicite de baisse des taux calculée à partir des contrats futures Fed Funds à 30 jours."
    override val explainerFedWatchShows: String = "Consensus du marché quant aux assouplissements monétaires de la Réserve Fédérale."
    override val explainerFedWatchNotMean: String = "Distribution de probabilité de marché, pas un engagement garanti de politique de banque centrale."

    override val explainerDxyWhat: String = "Indice géométriquement pondéré mesurant la force du dollar américain face à 6 devises majeures."
    override val explainerDxyShows: String = "Conditions mondiales de liquidité en dollar, fuite de capitaux et pouvoir d'achat relatif."
    override val explainerDxyNotMean: String = "Marée de liquidité macro, pas un déterminant isolé des creux ou sommets des cryptomonnaies."

    override val explainerUs10yWhat: String = "Rendement annuel des titres de dette souveraine américaine à 10 ans."
    override val explainerUs10yShows: String = "Coût mondial du capital sans risque et anticipations de croissance/inflation à long terme."
    override val explainerUs10yNotMean: String = "Taux d'actualisation macro pour les actifs à risque, pas un signal d'exécution court terme."

    override val explainerBrentWhat: String = "Référence internationale de prix pour les contrats de pétrole brut physique."
    override val explainerBrentShows: String = "Pressions inflationnistes sur les matières premières énergétiques et activité industrielle mondiale."
    override val explainerBrentNotMean: String = "Composante des indices d'inflation, pas un moteur directionnel direct pour les cryptos."

    // Futures Metric Explainers
    override val explainerFundingWhat: String = "Frais de financement périodiques échangés entre acheteurs (longs) et vendeurs (shorts) sur les contrats perpétuels."
    override val explainerFundingShows: String = "Concentration du positionnement des traders et biais de levier directionnel sur les marchés dérivés."
    override val explainerFundingNotMean: String = "Un fort biais reflète le levier utilisé, pas un retournement immédiat ou garanti des cours."

    override val explainerOiWhat: String = "Total des positions ouvertes et valorisation en dollars sur l'ensemble des contrats perpétuels actifs."
    override val explainerOiShows: String = "Flux net d'entrée ou de sortie des capitaux dérivés et expansion continue du levier."
    override val explainerOiNotMean: String = "Mesure de l'engagement global sur dérivés, pas un résultat directionnel sans le contexte du prix."

    override val explainerSentimentWhat: String = "Indice de sentiment (0-100) et part de la capitalisation boursière totale détenue par Bitcoin."
    override val explainerSentimentShows: String = "Appétit pour le risque et rotation des capitaux entre Bitcoin et les Altcoins."
    override val explainerSentimentNotMean: String = "Posture macroéconomique globale, pas un signal d'exécution de trading à court terme."

    override val explainerLiqWhat: String = "Liquidations forcées de positions exécutées lors de la rupture de la marge de maintien."
    override val explainerLiqShows: String = "Zones de prix concentrées où les comptes surendettés sont clôturés par la plateforme."
    override val explainerLiqNotMean: String = "Cascades de débouclage forcé, pas une accumulation institutionnelle directionnelle organique."

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "Analyste de Marché IA"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Intelligence en Temps Réel sur les Cycles, Futures & Baleines"
    override val aiPromptPlaceholder: String = "Posez une question sur le cycle BTC, funding, support, altseason..."
    override val aiAskButton: String = "Analyser"
    override val aiQuickActionCycle: String = "Cycle & Risque Halving"
    override val aiQuickActionFutures: String = "Financement & Flux de Levier"
    override val aiQuickActionWhales: String = "Accumulation des Baleines"
    override val aiQuickActionAltseason: String = "Disponibilité Altseason"
    override val aiDisclaimer: String = "Propulsé par les modèles Gemini IA & la télémétrie en temps réel. Ne constitue pas un conseil financier."
    override val aiThinking: String = "Analyse de la télémétrie et du carnet d'ordres en direct..."
    override val aiGreeting: String = "Je suis là. Que souhaitez-vous voir ?"
    override val aiClearHistory: String = "Effacer"
    override val aiLiveContextTag: String = "Flux en Direct Connectés"
    override val aiPromptPrefixCycle: String = "Analyse la phase actuelle du cycle de halving, le risque et les analogues historiques."
    override val aiPromptPrefixFutures: String = "Interprète les taux de funding actuels, l'open interest et les risques de liquidation sur les futures."
    override val aiPromptPrefixWhales: String = "Que révèlent les alertes récentes sur les mouvements de baleines concernant l'accumulation ou la distribution institutionnelle ?"
    override val aiPromptPrefixAltseason: String = "Évalue si les conditions de marché, la dominance du BTC et le sentiment favorisent une Altseason actuellement."
    override val backtestBadgeText: String = "Radar baleine live · order flow live · liquidations live"
    override val derivativesRiskGuardrail: String = "Protocole Dérivés : Tradez de manière responsable. Ne risquez jamais plus de 1-2% du capital par position."

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Couche Market Intelligence : Comment ça marche"
    override val marketIntelligenceInfoButton: String = "Qu'est-ce que c'est ?"
    override val marketIntelligenceConfidenceTitle: String = "Score de Confiance (ex. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Mesure la force quantitative du positionnement actuel sur les futures selon le volume, l'open interest et le momentum."
    override val marketIntelligenceRegimesHeader: String = "Régimes de Marché (Signification des signaux)"
    override val regimeShortSqueezeTitle: String = "Pression de Short Squeeze"
    override val regimeShortSqueezeDesc: String = "Des positions vendeuses massives sont piégées. Une hausse modeste peut déclencher des liquidations en cascade et de fortes pointes."
    override val regimeSpotAccumulationTitle: String = "Accumulation Spot"
    override val regimeSpotAccumulationDesc: String = "Absorption réelle d'achats au comptant plutôt qu'un effet de levier risqué. Révèle une structure de marché saine et durable."
    override val regimeBalancedConsolidationTitle: String = "Consolidation Équilibrée"
    override val regimeBalancedConsolidationDesc: String = "L'effet de levier des dérivés et la demande spot sont à l'équilibre, annonçant une évolution en range."
    override val marketIntelligenceTelemetryHeader: String = "Télémétrie Clé"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Capital total engagé dans les contrats dérivés actifs."
    override val telemetryFundingRateTitle: String = "Taux de Financement (Funding Rate)"
    override val telemetryFundingRateDesc: String = "Frais périodiques entre acheteurs et vendeurs. Des taux très positifs signalent des positions longues surendettées vulnérables."
    override val marketIntelligenceUnderstood: String = "Compris"

    // Completed translations for remaining screens
    override val navLearn: String = "Apprendre"
    override val refreshTooltip: String = "Actualiser les flux de marché"
    override val refreshingFeeds: String = "Actualisation des données marché et futures…"
    override val feedsUpdated: String = "Flux de marché à jour"
    override val cycleDaysTeaserTitle: String = "Jours de cycle et comparaison baissière"
    override val cycleDaysTeaserBadge: String = "HORLOGE DE CYCLE"
    override val cycleDaysTeaserDaysPostAth: String = "Jours depuis l’ATH selon la date listée"
    override val cycleDaysTeaserCompare: String = "Comparer les jours depuis l’ATH aux cycles précédents →"
    override val cycleDaysCardTitle: String = "Jours de cycle et analogie historique"
    override val cycleDaysCardSubtitle: String = "Où se situait le prix ce jour-là lors des précédents marchés baissiers"
    override val cycleChartTapToInspect: String = "Touchez ou faites glisser pour inspecter jours et prix"
    override val cycleChartDayLabel: String = "Jour"
    override val cycleChartFractalScore: String = "Mouvement de fenêtre"
    override val cycleChartModeAll: String = "Tous les cycles"
    override val cycleChartModeProjection: String = "Couloir de comparaison"
    override val cycleChartMode2020: String = "2020-24"
    override val cycleChartMode2016: String = "2016-20"
    override val cycleChartMilestoneHalving: String = "Halving"
    override val cycleChartMilestoneBreakout: String = "Cassure ATH"
    override val cycleChartMilestonePeak: String = "Sommet de cycle"
    override val cycleChartMilestoneFloor: String = "Plancher de cycle"
    override val cycleChartCurrentPoint: String = "Position actuelle"
    override val cycleChartProjectedPath: String = "Trajectoire de comparaison"
    override val cycleChartProjectedZone: String = "Couloir de prix"
    override val latestNewsTitle: String = "Dernières actualités"
    override val latestNewsSubtitle: String = "Titres live et intelligence de marché"
    override val futuresAllPairs: String = "Toutes les paires"
    override val futuresSearchPair: String = "Rechercher une paire crypto…"
    override val futuresSwitchPair: String = "Changer de paire"
    override val futuresPerpetualContract: String = "Contrat perpétuel"
    override val intelligenceLayerTitle: String = "COUCHE D’INTELLIGENCE MARCHÉ"
    override val whyAssetMovingHeader: String = "Pourquoi %s bouge-t-il ?"
    override val marketStateHeader: String = "ÉTAT DU MARCHÉ"
    override val confidenceHeader: String = "Confiance"
    override val driversHeader: String = "Principaux moteurs du marché"
    override val driverSpotDemand: String = "Demande spot"
    override val driverOpenInterest: String = "Open Interest"
    override val driverFundingSkew: String = "Biais de funding"
    override val driverLiquidations: String = "Pression de liquidation"
    override val driverMacroSentiment: String = "Régime macro"
    override val interpretationLabel: String = "Interprétation : "
    override val cascadeRiskLabel: String = "Risque de cascade : "
    override val invalidationLabel: String = "Invalidation : "
    override val expandDeepDive: String = "Toucher pour le détail et l’invalidation"
    override val collapseDeepDive: String = "Masquer le détail"
    override val liquidationMapHeader: String = "POOLS DE LIQUIDATION AGRÉGÉS"
    override val liquidationMapSub: String = "Clusters de liquidation estimés et liquidité de balayage"
    override val shortLiquidationPools: String = "Pools de liquidation short (au-dessus du prix)"
    override val longLiquidationPools: String = "Pools de liquidation long (sous le prix)"
    override val currentPriceAnchor: String = "PRIX ACTUEL"
    override val estimatedPoolSuffix: String = "liquidité estimée"
    override val tabClustersMap: String = "Carte des clusters"
    override val tabLiveStream: String = "Flux live"
    override val homeSubtitle: String = "Comprendre. Analyser. Trader plus intelligemment."
    override val bullishState: String = "Haussier"
    override val bearishState: String = "Baissier"
    override val neutralState: String = "Neutre"
    override val highRiskBadge: String = "Risque élevé"
    override val moderateRiskBadge: String = "Risque modéré"
    override val lowRiskBadge: String = "Risque faible"
    override val threeThingsThatMatter: String = "3 points qui comptent maintenant"
    override val tabOverview: String = "Aperçu"
    override val tabCoins: String = "Pièces"
    override val tabWatchlist: String = "Watchlist"
    override val tabSectors: String = "Secteurs"
    override val totalMarketCapLabel: String = "Capitalisation totale"
    override val volume24hLabel: String = "Volume 24h"
    override val explainAction: String = "Expliquer >"
    override val spotBuyingLabel: String = "Achats spot"
    override val fundingRateLabel: String = "Taux de funding"
    override val tabAnalytics: String = "Analyse"
    override val tabOnChain: String = "On-Chain"
    override val tabEvents: String = "Événements"
    override val onChainNetworkHeader: String = "Réseau et données on-chain"
    override val eventsMilestonesHeader: String = "Jalons du protocole et catalyseurs"
    override val upcomingTag: String = "À VENIR"
    override val completedTag: String = "TERMINÉ"
    override val activeTag: String = "ACTIF"
    override val whaleConcentrationLabel: String = "Concentration des baleines"
    override val exchangeNetFlowLabel: String = "Flux des réserves d’exchange"
    override val netOutflowBias: String = "Sorties nettes (accumulation)"
    override val activeAddressesEstimate: String = "Wallets réseau actifs (24h)"
    override val cycleMomentumTitle: String = "Momentum de cycle et santé relative"
    override val circulatingSupplyTitle: String = "Offre en circulation"
    override val maxSupplyLabel: String = "Offre maximale"
    override val tabTopSignals: String = "Meilleurs signaux"
    override val tabMySignals: String = "Mes signaux"
    override val tabPerformance: String = "Performance"
    override val scoreLabel: String = "Score"
    override val timeframeLabel: String = "Horizon"
    override val expectedScenarioLabel: String = "Scénario attendu"
    override val viewFullAnalysisBtn: String = "Voir l’analyse complète"
    override val tabCourses: String = "Cours"
    override val tabLessons: String = "Leçons"
    override val tabQuizzes: String = "Quiz"
    override val tabMyProgress: String = "Ma progression"
    override val commonMistakeLabel: String = "Erreur fréquente"
    override val backLabel: String = "Retour"
    override val nextLabel: String = "Suivant"
    override val alertsTitle: String = "Alertes"
    override val createAlertBtn: String = "Créer une alerte"
    override val tabActive: String = "Actives"
    override val tabHistory: String = "Historique"
    override val tabTemplates: String = "Modèles"
    override val alertInsightLabel: String = "Insight d’alerte"
    override val alertInsightText: String = "Les alertes n’utilisent que des prints live. Aucun taux de réussite historique inventé."
    override val whyBtn: String = "Pourquoi ?"
    override val marketCopilotTitle: String = "Analyste IA des données de marché"
    override val betaBadge: String = "Bêta"
    override val askAnythingMarket: String = "Posez une question sur le marché…"
    override val relatedDataLabel: String = "Données liées"
    override val liquidationMapTab: String = "Carte des liquidations"
    override val liquidationHeatmapTab: String = "Heatmap des liquidations"
    override val liquidationWarningText: String = "Clusters de liquidation élevés. Volatilité accrue si le support cède."
    override val exchangeBinance: String = "Binance"
    override val savedCoinsTitle: String = "Pièces enregistrées"
    override val largest24hMovesTitle: String = "Plus grands mouvements 24h"
    override val noSavedCoinsYet: String = "Aucune pièce enregistrée. Ajoutez une étoile pour la garder ici."
    override val unlockProForSymbol: String = "Débloquer Pro pour %s"
    override val live24hMoveLabel: String = "Mouvement live 24h"
    override val live24hMoveDisclaimer: String = "La barre montre uniquement le print live 24h. Pas une prévision."
    override val windowLowLabel: String = "Plus bas de fenêtre :"
    override val windowLowDisclaimer: String = "Minimum de la sparkline live. Pas une prévision ATR."
    override val noInventedInvalidation: String = "Aucun niveau d’invalidation inventé. Prints live uniquement."
    override val notInvestmentAdvice: String = "Ce n’est pas un conseil d’investissement personnalisé."
    override val weekSinceAthFmt: String = "semaine %1\$d depuis l’ATH · %2\$d jours"
    override val live24hTag: String = "live 24h"
    override val liveSparkTag: String = "live 7j"
    override val fromAthTag: String = "depuis l’ATH"
    override val liveRealizedHint: String = "Mouvements live réalisés · pas une prévision"
    override val liveRealizedDisclaimer: String = "Les cartes montrent des mouvements live réalisés. Aucun taux de réussite inventé."
    override val awaitingSparkline: String = "En attente de sparkline"
    override val bullishMomentumShort: String = "Momentum haussier"
    override val oversoldWeakShort: String = "Survendu / faible"
    override val neutralConsolidationShort: String = "Consolidation neutre"
    override val distanceFromAth: String = "Distance à l’ATH"
    override val fromLivePriceAth: String = "Depuis le prix live / ATH"
    override val sinceAthSuffix: String = "depuis l’ATH"
    override val realMarketFeed: String = "Flux de marché réel"
    override val noLiveFeed: String = "Pas de flux live"
    override val noWalletConcentrationFeed: String = "Aucun flux public pour la concentration des wallets. Affichage de — plutôt qu’un chiffre inventé."
    override val genesisHeritageTitle: String = "Genèse et origine"
    override val consensusProtocolLabel: String = "Protocole de consensus :"
    override val rsi14Label: String = "RSI 14j"
    override val delta24hLabel: String = "Delta 24h"
    override val liveMoves24hLabel: String = "24h"
    override val liveMovesSparkLabel: String = "Spark"
    override val currentPhaseScoreFmt: String = "Phase actuelle : %1\$s avec un score de cycle live de %2\$d/100."
}
