package com.example.util

import com.example.data.model.AppLanguage

class GermanAppStrings : AppStrings(AppLanguage.GERMAN) {
    // Navigation & Core
    override val navMarkets: String = "Zyklus"
    override val navCoins: String = "Coins"
    override val navFutures: String = "Futures"
    override val navSignals: String = "Tape"
    override val navSettings: String = "Einstellungen"
    override val navMacro: String = "Makro"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO AKTIV"
    override val backToFree: String = "Zurück zu Free"
    override val upgradeToPro: String = "Auf Pro upgraden"
    override val proRequired: String = "Pro erforderlich"
    override val searchPlaceholder: String = "100+ Krypto-Assets suchen..."
    override val cryptocurrenciesCount: String = "KRYPTOWÄHRUNGEN"
    override val cryptocurrencySingular: String = "KRYPTOWÄHRUNG"
    override val turboEngineActive: String = "Turbo-Engine aktiv"
    override val rankPrefix: String = "Rang"
    override val closeButton: String = "Schließen"
    override val institutionalTerminal: String = "Zyklus- und Derivate-Terminal"
    override val trustBarFeed: String = "Institutioneller Feed: Direktes Orderbuch"
    override val latencyMs: String = "%dms Latenz"
    override val realtimeFeed: String = "LIVE-FEED"
    override val neutralPhase: String = "Neutrale Phase"
    override val avg7d: String = "7T Schnitt"
    override val avg30d: String = "30T Schnitt"
    override val daysHigh: String = "T Hoch"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Layer 1"
    override val catLayer2: String = "Layer 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "KI & Infra"
    override val catMeme: String = "Memes"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Utility"
    override val catFavorites: String = "Favoriten"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Marktübersicht"
    override val marketsHeadline: String = "100+ Nützliche Real-World Assets & Zyklus-Blueprints"
    override val marketsSubtitle: String = "Wohin sich jeder Coin bewegt, historische Muster, Zukunftsprognosen & Whitepapers."
    override val fromAth: String = "vom ATH"
    override val tapForCycleAnalog: String = "Tippen für Zyklus-Analogon, Prognosen & Whitepaper"
    override val heroSubtitle: String = "HISTORISCHES ZYKLUS-ANALOGON"
    override val currentPrice: String = "Aktueller Preis"
    override val analogMatch: String = "Historische Übereinstimmung"
    override val cyclePhase: String = "Zyklusphase"
    override val daysSinceAth: String = "Tage seit ATH"
    override val tapToViewCycles: String = "Tippen, um Zyklen & Whitepaper anzuzeigen"

    // Markets Screen Teaser Cards
    override val marketsOrderFlowTeaserTitle: String = "Orderflow & Futures-Tiefe"
    override val marketsOrderFlowTeaserSummary: String = "Funding · OI · Liquidationen 24h"
    override val marketsOrderFlowTeaserLocked: String = "Gesperrt"
    override val marketsOrderFlowTeaserLockedDesc: String = "Live-Hebel & Liquidationsfluss freischalten"
    override val marketsOrderFlowTeaserUnlockedDesc: String = "Live-DOM-Leiter & Orderbuch"
    override val marketsOrderFlowTeaserUpgrade: String = "Upgrade →"
    override val marketsOrderFlowTeaserOpenFutures: String = "Futures öffnen →"
    override val marketsSignalsTeaserTitle: String = "Wal-Radar & Fraktal-Signale"
    override val marketsSignalsTeaserLiveTag: String = "LIVE-FEED"
    override val marketsSignalsTeaserSample: String = "BTC: $148M Netto-Akkumulation auf Coinbase Prime"
    override val marketsSignalsTeaserAccumulationTag: String = "AKKUMULATION"
    override val marketsSignalsTeaserSub: String = "Liquidationskarten & 2016/2020 Zyklusfraktale"
    override val marketsSignalsTeaserOpen: String = "Signals-Tab öffnen →"
    override val marketsMacroTeaserNextEvent: String = "Nächstes Event: US Jobs (NFP) Freitag 15:30 UTC"
    override val marketsMacroTeaserOpen: String = "Makro öffnen →"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "HISTORISCHES ZYKLUS-ANALOGON"
    override val historicalAnalogProUnlockedTitle: String = "Pro-Zyklusanalyse freigeschaltet"
    override val historicalAnalogProTitle: String = "Historisches Zyklus-Analogon"
    override val historicalAnalogProUnlockedDesc: String = "Live-Börsenhistorie und realisierte Bewegungen sind aktiv."
    override val historicalAnalogProDesc: String = "Live-Historiencharts und Karten realisierter Bewegungen freischalten."
    override val historicalAnalogManagePro: String = "Pro verwalten"
    override val historicalAnalogProPrice: String = "Pro freischalten (2,99 €/Monat)"
    override val movementAnalysisHeader: String = "BEWEGUNGSANALYSE & ZYKLUSHISTORIE"
    override val whereItMovesNowLabel: String = "Wohin er sich jetzt bewegt:"
    override val whereItMovedPastLabel: String = "Wohin er sich in vergangenen Zyklen bewegte:"
    override val nextMoveHeader: String = "LIVE REALISIERTE BEWEGUNGEN"
    override val cycleFractalLabel: String = "Zyklus-Fraktaltag"
    override val historicalMatchLabel: String = "Wie der Preis von Halving zu Halving gelaufen ist"
    override val target1w: String = "1 Woche"
    override val target2w: String = "2 Wochen"
    override val target4w: String = "4 Wochen"
    override val strategyGuideTitle: String = "📖 Strategieleitfaden: Wann Kaufen & Verkaufen"
    override val buyMomentTitle: String = "🟢 Historischer Pi-Cycle-Boden"
    override val buyMomentRules: String = "1. Wenn der Bitcoin-Preis den 200W MA-Boden berührt oder sich ihm nähert (<15% Abstand). Dies markiert historische Zyklustiefs.\n2. Wenn 111 DMA weit unter (>40%) 350 DMA x 2 liegt. Minimales Abwärtsrisiko bei maximalem Ertrag (DCA In)."
    override val sellMomentTitle: String = "🔴 Wann ist der beste Zeitpunkt zum VERKAUFEN (Zyklus-Höhepunkt)"
    override val sellMomentRules: String = "1. Wenn 111 DMA über 350 DMA x 2 kreuzt. Dies signalisiert eine hohe Wahrscheinlichkeit eines Zyklus-Tops.\n2. Wenn der Rainbow Chart die roten 'Maximum Bubble'-Zonen erreicht. Historische Daten zeigen, dass massive Einbrüche folgen (90%+ bei Altcoins)."
    override val rainbowFeatureLabel: String = "🌈 Bitcoin Rainbow Chart (Dynamisches Power-Law-Modell)"
    override val altSeasonFeatureLabel: String = "⚡ Altcoin Season Index (0-100) & Top 50 Outperformer"
    override val piCycleFeatureLabel: String = "🎯 Pi Cycle Top Indikator & 200W MA-Boden (historische Kreuze)"
    override val fearGreedFeatureLabel: String = "😱 Fear & Greed Multi-Timeframe Stimmungsanalyse"
    override val proAnalyticsTitle: String = "Pro-Zyklusanalyse"
    override val proAnalyticsDesc: String = "Die Linien 2016 und 2020 auf demselben Zyklustag freischalten für"
    override val proAnalyticsButton: String = "Pro freischalten (2,99 €/Monat)"
    override val projectedPeakLabel: String = "ATH"
    override val projectedBottomLabel: String = "ATL"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "MARKTSTATISTIKEN & TOKEN-ANGEBOT"
    override val circulatingSupplyLabel: String = "Umlaufendes Angebot:"
    override val circulatingShort: String = "Im Umlauf"
    override val infiniteDeflationary: String = "Unbegrenzt (Deflationär)"
    override val marketCapMetric: String = "MARKTKAPITALISIERUNG"
    override val volume24hMetric: String = "24H-VOLUMEN"
    override val tradingVolumeSub: String = "Handelsvolumen"
    override val fdvMetric: String = "FDV (BEWERTUNG)"
    override val fdvSub: String = "Vollständig verwässerte Bewertung"
    override val athMetric: String = "ALLZEITHOCH (ATH)"
    override val atlMetric: String = "ALLZEITTIEF (ATL)"
    override val drawdownAthMetric: String = "RÜCKGANG VOM ATH"
    override val fromPeakSub: String = "Vom Höchststand"
    override val allTimeLowMetric: String = "Allzeittief"
    override val allTimeHighMetric: String = "Allzeithoch"
    override val startMetric: String = "Start"
    override val liveYearsMetric: String = "6443T · 17.64 Jahre aktiv"
    override val daysSinceHighMetric: String = "Tage seit dem Hoch"
    override val dropFromHighMetric: String = "-36.0% Rückgang vom Hoch"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & TECHNOLOGIE-BLUEPRINT"
    override val founderLabel: String = "SCHÖPFER / GRÜNDER"
    override val genesisDateLabel: String = "GENESIS-DATUM"
    override val whatCoinDoesLabel: String = "Was der Coin macht (Core Whitepaper Blueprint)"
    override val consensusLabel: String = "Konsensmechanismus & Architektur"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Emission"
    override val useCasesLabel: String = "Zentrale Ökosystem-Anwendungsfälle"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Historisch bärische Vergleichswoche (Stichprobe: n=2 Zyklen)"
    override val weekOfFallSub: String = "Woche 46 · typischerweise 16 Wo."
    override val cycleAnalysisHeader: String = "Zyklusanalyse"
    override val fromHighToLowTitle: String = "VOM HOCH ZU EINEM MÖGLICHEN TIEF"
    override val daysAfterAthLabel: String = "Tage nach dem Allzeithoch"
    override val daysToBottomLabel: String = "Tage bis zu einem möglichen Tief"
    override val highMarker: String = "Hoch"
    override val typical383dMarker: String = "typisch 383T"
    override val lowMarker: String = "Tief"
    override val fromHighToLowNarrative: String = "Wir befinden uns 319 Tage nach dem Allzeithoch. Historisch dauerte es vom Hoch bis zum Tief etwa 383 Tage. Es verbleiben ca. 64 Tage bis zu einem möglichen Tief."
    override val fromHighToLowDetails: String = "06. Okt 2025 · \$124,752.53 · -36.0% vom Hoch"
    override val fromHighToLowDisclaimer: String = "Das haben vergangene Zyklen gezeigt. Keine Garantie — nur eine Orientierungsuhr."
    override val thisCycleVsLastTitle: String = "DIESER ZYKLUS VS VERGANGENE"
    override val daysAfterHighTitle: String = "Tage nach dem Hoch"
    override val daysAfterHighSub: String = "Wir sind 319 Tage nach dem Hoch. Frühere Rückgänge bis zum Tief dauerten ca. 383 Tage."
    override val nowLabel: String = "Jetzt"
    override val daysOfRiseTitle: String = "Tage des Anstiegs, historisch"
    override val daysOfRiseSub: String = "Frühere Anstiege vom Tief zum nächsten Hoch dauerten ca. 1059 Tage."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "Tage bis zum nächsten Halving"
    override val halvingHoursLabel: String = "verbleibende Stunden"
    override val whatCameNextTitle: String = "Was an entsprechenden Tagen früherer Zyklen geschah"
    override val timeframe1wk: String = "in 1 Wo."
    override val timeframe2wk: String = "in 2 Wo."
    override val timeframe4wk: String = "in 4 Wo."
    override val winRate71: String = "Live 24h"
    override val winRate79: String = "Live Sparkline"
    override val winRate86: String = "Vom ATH"
    override val whyWeSayThisTitle: String = "Historischer Kontext & Zyklus-Vorbehalte"
    override val whyPoint1: String = "Diese Zykluswoche ähnelt dem 28. Jun 2018 — gleiche Phase, ähnliche Bewegung."
    override val whyPoint2: String = "Wir haben 14 ähnliche Wochen in der Historie analysiert. In den folgenden 4 Wochen stieg der Preis in 12 von 14 Fällen (typischerweise +29.5%)."
    override val whyPoint3: String = "Wir sind in Woche 46 des Rückgangs. In der Vergangenheit dauerte eine solche Phase etwa 16 Wochen."
    override val whyPoint4: String = "Sowohl die Zyklusposition als auch die historischen Wochen deuten auf die grüne Zone hin."

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Asset auswählen"
    override val signalsAllCoins: String = "Alle 100+ Kryptowährungen"
    override val timeframe1D: String = "1T"
    override val timeframe1W: String = "1W"
    override val timeframe1M: String = "1M"
    override val timeframe1Y: String = "1J"
    override val timeframeCycle: String = "Makro-Zyklus"
    override val signalBullish: String = "24h HOCH"
    override val signalBearish: String = "24h RUNTER"
    override val signalAccumulation: String = "AKKUMULATIONS-AUSBRUCH"
    override val signalConfidence: String = "Historische Bezugsfrequenz"
    override val signalLiveFeed: String = "Live CoinGecko Feed • 1s Ticks"
    override val analogComparisonHeader: String = "HISTORISCHE PREISAKTION-ÜBERLAGERUNG"
    override val analogExplanation: String = "Abgleich der Preisbewegung mit Daten vergangener Zyklen. Keine Prognose."
    override val highAccuracyNotice: String = "Historisches Backtest-Referenzprotokoll"

    // Settings Screen
    override val settingsHeader: String = "Einstellungen"
    override val languageTitle: String = "Sprache"
    override val languageDesc: String = "Wählen Sie Ihre bevorzugte Sprache"
    override val appearanceTitle: String = "Erscheinungsbild"
    override val themeGalaxyDark: String = "Galaxy Dark (Standard)"
    override val themeGalaxyDarkSub: String = "Tiefblauer OLED-Hintergrund mit Cyan-Akzenten"
    override val themePureBlack: String = "Pures Schwarz"
    override val themePureBlackSub: String = "Echtes OLED-Schwarz für maximale Akkulaufzeit"
    override val themeCleanWhite: String = "Klares Weiß"
    override val themeCleanWhiteSub: String = "Helles Design für Umgebungen mit viel Tageslicht"
    override val optionsTitle: String = "Optionen"
    override val soundEffectsTitle: String = "Krypto-Soundeffekte (SFX)"
    override val soundEffectsSub: String = "Haptisches Feedback bei Navigation & Benachrichtigungen"
    override val soundTestTitle: String = "Soundeffekte testen"
    override val soundTestLaunch: String = "Dur-Tonleiter Aufstieg 🎵"
    override val soundTestClick: String = "Tech-Klick"
    override val soundTestToggle: String = "Schalter-Ton"
    override val soundTestChime: String = "Münz-Glockenton"
    override val hideMemecoinsTitle: String = "Memecoins ausblenden"
    override val hideMemecoinsSub: String = "Nur fundamentale Projekte mit hoher Marktkapitalisierung anzeigen"
    override val logChartsTitle: String = "Logarithmische Charts"
    override val logChartsSub: String = "Preise auf logarithmischer Skala darstellen"
    override val proMembershipTitle: String = "Pro-Mitgliedschaft"
    override val proMembershipPrice: String = "2,99 € / Monat · 24,99 € / Jahr"
    override val manageProSubscription: String = "Pro-Abo verwalten"
    override val proPriceTrialLine: String = "2,99 € / Monat · 7 Tage kostenlos testen"
    override val proTapeTitle: String = "PRO BANDLESUNG"
    override val proTapeDesc: String = "Live-Lesung von RSI, EMA, ATR, Funding und ETF aus täglichen Schlusskursen. Keine Prognose."
    override val proBenefit1: String = "Linien 2016 und 2020 auf demselben Zyklustag"
    override val proBenefit2: String = "Tagesprotokoll der Live-Zahlen, die die App zeigte"
    override val proBenefit3: String = "Optionale Tageszähl-Benachrichtigung, die das Chart öffnet"
    override val proBenefit4: String = "Live-Tape aus Schlusskursen, Funding und ETF — keine Prognose"
    override val proBenefit5: String = "KI, die nur den Bildschirm-Snapshot liest"
    override val proBenefit6: String = "Extra-Lektionen zu Hebel, Funding und Orderbuch — kein Trade-Aufruf"
    override val currencyDisplayTitle: String = "Anzeigewährung"
    override val howWeReadItTitle: String = "Wie wir es lesen — in einfachen Worten"
    override val plainItem1Title: String = "1. Geschichte wiederholt sich in Zyklen"
    override val plainItem1Desc: String = "Krypto folgt ca. 4-jährigen Halving-Zyklen. Wir gleichen den aktuellen Verlauf mit 2020 und 2016 ab."
    override val plainItem2Title: String = "2. Historische Analoga"
    override val plainItem2Desc: String = "Die orange Kurve zeigt 2020; die Cyan-Kurve 2016. Die weiße Linie ist die aktuelle Flugbahn."
    override val plainItem3Title: String = "3. Historische Zykluszonen"
    override val plainItem3Desc: String = "Mittels logarithmischer Regression berechnen wir historische Zonen zu Studienzwecken. Alle Tools sind bildend und keine Finanzberatung."
    override val plainItem4Title: String = "4. Fundamentale Whitepapers"
    override val plainItem4Desc: String = "Jedes Profil enthält Konsensmodell, Tokenomics, Gründer und echte Anwendungsfälle."
    override val plainItem5Title: String = "5. Risikohinweis"
    override val plainItem5Desc: String = "Vergangene Gewinne garantieren keine zukünftigen Erträge. Investieren Sie mit Bedacht."
    override val privacyPolicyTitle: String = "Nutzungsbedingungen & Datenschutzerklärung"
    override val privacyPolicyView: String = "Unsere Datenrichtlinie einsehen"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Du zahlst für die Linien 2016/2020, das Tagesprotokoll, den Tagesalarm, das Live-Tape und die Extra-Lektionen. Preis, Cap, Fear & Greed und ETF 1 Tag bleiben frei. Keine Prognose."
    override val proModalFeature1: String = "Linien 2016 und 2020 auf demselben Zyklustag"
    override val proModalFeature2: String = "Tagesprotokoll der Live-Zahlen, die die App zeigte"
    override val proModalFeature3: String = "Optionale Tageszähl-Benachrichtigung, die das Chart öffnet"
    override val proModalFeature4: String = "Live-Tape aus Schlusskursen, Funding und ETF — keine Prognose"
    override val proModalFeature5: String = "KI, die nur den Bildschirm-Snapshot liest"
    override val proModalFeature6: String = "Extra-Lektionen zu Hebel, Funding und Orderbuch — kein Trade-Aufruf"
    override val planMonthlyTitle: String = "Monatlich"
    override val planMonthlyPrice: String = "2,99 €"
    override val planMonthlyPeriod: String = "/ Monat"
    override val planMonthlyBadge: String = "7 Tage kostenlos testen"
    override val planAnnualTitle: String = "Jährlich"
    override val planAnnualPrice: String = "24,99 €"
    override val planAnnualPeriod: String = "/ Jahr"
    override val planAnnualBadge: String = "~2,08 €/Monat · etwa 3 Monate geschenkt"
    override val subscribeProBtn: String = "7 Tage kostenlos testen"
    override val startFreeTrialBtn: String = "7 Tage kostenlos testen"
    override val startFreeTrialSub: String = "7 Tage gratis, danach 2,99 € / Monat. Jederzeit kündbar."
    override val continueYearlyBtn: String = "Mit Jährlich fortfahren (24,99 €/Jahr)"
    override val continueYearlySub: String = "Sofortiger Pro-Zugang • 24,99 € jährlich abgerechnet (~2,08 €/Monat)"
    override val restorePurchases: String = "Käufe wiederherstellen"
    override val restoringPurchases: String = "Google Play Käufe werden überprüft..."
    override val cancelAnytime: String = "Jederzeit in Google Play kündbar"
    override val playTermsDisclosure: String = "Die Zahlung wird nach Bestätigung über Ihr Google Play-Konto abgewickelt. Das Abonnement verlängert sich automatisch, sofern es nicht mindestens 24 Stunden vor Ablauf gekündigt wird."
    override val financialDisclaimerTitle: String = "Finanz- und Regulierungshinweis"
    override val financialDisclaimerText: String = "Bildungsgeschichte vergangener Zyklen. Keine Prognose und keine Beratung. CryptoCycles ist keine Börse, verwahrt kein Geld und sagt nicht, dass man kaufen oder verkaufen soll."
    override val privacySheetTitle: String = "CryptoCycles Datenschutz"
    override val privacyLastUpdated: String = "Zuletzt aktualisiert: 2026"
    override val privSection1Title: String = "1. Datenerhebung"
    override val privSection1Body: String = "Kauf-/Verkaufsfenster basieren auf historischen Mustern und stellen keine Anlageberatung dar."
    override val privSection2Title: String = "2. Minderjährige"
    override val privSection2Body: String = "CryptoCycles richtet sich nicht an Personen unter 13 Jahren."
    override val privSection3Title: String = "3. Kontakt"
    override val privSection3Body: String = "Für Datenschutzanfragen nutzen Sie die E-Mail im Google Play Store."
    override val privSection4Title: String = "4. Lokale Speicherung"
    override val privSection4Body: String = "CryptoCycles erstellt keine Benutzerkonten und verkauft keine persönlichen Daten. Alle Einstellungen verbleiben lokal auf Ihrem Gerät."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO Zykluslinien und Bandlesung"
    override val signalsProLockedSubtitle: String = "Die Überlagerungen 2016 und 2020 und die Lesung täglicher Schlusskurse. Keine Prognose."
    override val signalsProLockedFeature1: String = "Linien 2016 und 2020 auf demselben Zyklustag"
    override val signalsProLockedFeature2: String = "Live-Lesung (RSI, EMA, ATR aus täglichen Schlusskursen)"
    override val signalsProLockedFeature3: String = "Tägliches Zyklusprotokoll dessen, was die App zeigte"
    override val signalsProLockedFeature4: String = "Bildung. Keine Prognose und kein Rat."
    override val signalsGateTitle: String = "Zyklusüberlagerungen und Bandlesung"
    override val signalsGateDesc: String = "Linien 2016 und 2020 und die Live-Lesung täglicher Schlusskurse. Kein Signal und keine Prognose."
    override val signalsGateBadge: String = "Live-Schlusskurse · Live-Funding · Live-ETF"

    // Zone Playbook Strings
    override val zonePlaybookTitle: String = "ZYKLUS-ZONEN PLAYBOOK"
    override val zonePlaybookSub: String = "Leitfaden zum Risikomanagement basierend auf Makro-Zykluszonen"
    override val zoneGreenAction: String = "Grüne Zone • Schrittweiser Einstieg (Akkumulieren)"
    override val zoneGreenDesc: String = "Historisch günstiges Chance-Risiko-Verhältnis. Systematisches Dollar-Cost-Averaging in Kern-Assets."
    override val zoneYellowAction: String = "Gelbe Zone • Halten & Rebalancieren"
    override val zoneYellowDesc: String = "Bewertungszone im mittleren Zyklus. Bestehende Positionen halten, FOMO vermeiden."
    override val zoneRedAction: String = "Rote Zone • Schrittweiser Ausstieg (Risiko reduzieren)"
    override val zoneRedDesc: String = "Überkaufte Bewertungszone. Historisch ratsam, Teilgewinne mitzunehmen und Kapital zu sichern."
    override val zonePlaybookDisclaimer: String = "Nur zu Bildungs- und Studienzwecken. Keine Finanzberatung."

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "WÖCHENTLICHES MAKRO-BRIEFING"
    override val weeklyBriefingSub: String = "Wöchentliche institutionelle Zyklus-Synthese & Risikohaltung"
    override val weeklyBriefingCurrentZone: String = "Aktuelle Makro-Zone"
    override val weeklyBriefingActionTitle: String = "Empfohlene Haltung"
    override val weeklyBriefingActionAccumulate: String = "AKKUMULIEREN"
    override val weeklyBriefingActionHold: String = "HALTEN"
    override val weeklyBriefingActionReduce: String = "REDUZIEREN"
    override val weeklyBriefingReasonTitle: String = "3-Punkte-Synthese"
    override val weeklyBriefingLine1: String = "1. Makro-Bewertungskennzahlen befinden sich weiterhin im unteren Akkumulationskorridor."
    override val weeklyBriefingLine2: String = "2. Der 200-Wochen-SMA-Boden und die Halving-Angebotsdynamik bieten weiterhin langfristige strukturelle Unterstützung."
    override val weeklyBriefingLine3: String = "3. Die Akkumulation in On-Chain-Wallets zeigt eine stetige Absorption während Konsolidierungsphasen."
    override val weeklyBriefingProUnlockText: String = "Schalten Sie das institutionelle wöchentliche Briefing, das Zonen-Playbook und Makro-Analoga mit Pro frei."

    // Historical Analog Card Strings
    override val historicalAnalogCardTitle: String = "HISTORISCHES ZYKLUS-ANALOGON"
    override val historicalAnalogPhaseText: String = "Wir befinden uns in der gleichen Zyklusphase wie am %s."
    override val historicalAnalogFollowThrough: String = "Nach diesem Punkt war die typische Bewegung: 30T: %s • 90T: %s • 180T: %s"
    override val historicalAnalogNotFinancialAdvice: String = "Bildungsmodell basierend auf der Fraktalhistorie von 2016 & 2020. Keine Finanzberatung."
    override val historicalAnalogProUnlockText: String = "Linien 2016 und 2020 auf demselben Zyklustag. Nur Historie — kein projizierter Pfad."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Zyklus- & Indikator-Push-Alerts"
    override val alertSettingsSub: String = "Sofortige Benachrichtigungen für kritische Marktzyklus-Schwellenwerte"
    override val alertZoneChangeTitle: String = "Zonenwechsel-Alarm"
    override val alertZoneChangeDesc: String = "Benachrichtigung, wenn Bitcoin zwischen Grüner, Gelber und Roter Zone wechselt"
    override val alertPiCycleTitle: String = "Pi Cycle Top Abstand & Kreuzung"
    override val alertPiCycleDesc: String = "Benachrichtigung, wenn sich der Abstand zwischen 111DMA und 350DMA x 2 verengt oder kreuzt"
    override val alertRainbowTitle: String = "Rainbow-Bänder-Übergang"
    override val alertRainbowDesc: String = "Benachrichtigung, wenn Bitcoin zwischen Rainbow-Bewertungsbändern wechselt"
    override val alert200WTitle: String = "Abstand zum 200-Wochen-SMA"
    override val alert200WDesc: String = "Benachrichtigung, wenn sich der Preis dem 200W SMA nähert oder stark abweicht"
    override val alertFreeLimitNotice: String = "Die Free-Version umfasst bis zu 2 aktive Alerts. Upgraden Sie auf Pro für unbegrenzte Alerts."
    override val alertProUnlockNotice: String = "PRO-Funktion: Unbegrenzte Push-Alerts für Zyklen, Pi Cycle und Rainbow."

    // Widget Strings
    override val widgetSettingsTitle: String = "Startbildschirm-Widget"
    override val widgetSettingsDesc: String = "Aktuelle Zykluszone, BTC-Preis und Tage seit ATH auf Ihrem Startbildschirm anzeigen"
    override val widgetZoneLabel: String = "Zone"
    override val widgetBtcPriceLabel: String = "BTC-Preis"
    override val widgetDaysSinceAthLabel: String = "Tage seit ATH"

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "GROSSE BINANCE-USDT-M-PRINTS (PRO)"
    override val whaleRadarSub: String = "Binance USDT-M Futures-Prints ab $100k. Keine On-Chain-Wallet-Transfers."
    override val whaleNotificationsTitle: String = "Wal-Alarm Push-Benachrichtigungen"
    override val whaleNotificationsDesc: String = "Erhalten Sie sofortige Benachrichtigungen bei massiven Wal-Käufen oder Börsen-Dumps."
    override val whaleNotificationsProLockedDesc: String = "Pro: Hinweis, wenn ein Binance-USDT-M-Print den Filter überschreitet. Keine On-Chain-Transfers."
    override val whaleThresholdTitle: String = "Mindestgröße für Wal-Alerts"
    override val whaleFilterAll: String = "Alle Wale"
    override val whaleFilterInflow: String = "🚨 Zuflüsse / Dumps"
    override val whaleFilterOutflow: String = "🟢 Akkumulation"
    override val whaleFilterBuy: String = "🚀 Mega-Käufe"
    override val whaleCollapse: String = "Einklappen"
    override val whaleViewAll: String = "Alle anzeigen (%d)"
    override val timeJustNow: String = "Gerade eben"
    override val timeMinsAgo: String = "vor %d Min."
    override val timeHoursAgo: String = "vor %d Std."
    override val liveOrderFlowTitle: String = "24/7 LIVE ORDERFLOW (BINANCE)"
    override val liveOrderFlowSub: String = "Echtzeit-Tickstream: Kauf- vs. Verkaufsdruck-Oszillator"
    override val buyDominanceLabel: String = "KAUFDRUCK"
    override val sellDominanceLabel: String = "VERKAUFSDRUCK"
    override val netVolumeDelta: String = "NETTOFLUSS 24H"
    override val liveExecutionFeed: String = "LIVE-AUSFÜHRUNGEN"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Makro- & Zyklusindizes"
    override val macroScreenSubtitle: String = "Institutionelle Bewertungsmodelle, Rainbow Power-Law & Marktstimmung"
    override val macroUpdated4m: String = "Aktualisiert vor 4 Min."
    override val macroProLockedTitle: String = "PRO historische Zykluswerkzeuge"
    override val macroProLockedSubtitle: String = "Rainbow-Bänder, Pi-Cycle-Kreuze und das wöchentliche Faktenbriefing. Kein Kauf- oder Verkaufssignal."
    override val macroGateTitle: String = "Historische Zykluswerkzeuge"
    override val macroGateDesc: String = "Rainbow-Bänder, Pi-Cycle-Kreuze und wöchentliche Fakten. Nur Historie — kein Trade."

    // Macro Filters
    override val macroFilterAll: String = "Alle Makro"
    override val macroFilterEconomicCalendar: String = "📅 NFP & CPI Kalender"
    override val macroFilterRiskBackdrop: String = "🌐 DXY, 10Y & FedWatch"
    override val macroFilterRainbow: String = "🌈 Rainbow Chart"
    override val macroFilterAltSeason: String = "⚡ Alt Season"
    override val macroFilterFearGreed: String = "😱 Fear & Greed"
    override val macroFilterPiCycle: String = "🎯 Pi Cycle & 200W"

    // Macro Economic Calendar & Risk Cards
    override val macroEconomicCalendarCardTitle: String = "📅 Wirtschaftsdaten & NFP / CPI"
    override val macroEconomicCalendarCardSub: String = "Nächstes: US Jobs (NFP) Freitag 15:30 UTC"
    override val macroNfpFridayBadge: String = "NFP FREITAG"
    override val macroRiskBackdropCardTitle: String = "🌐 DXY, 10Y Renditen & FedWatch"
    override val macroRiskBackdropCardSub: String = "Globale USD-Liquidität & Staatsanleiherenditen"
    override val macroRiskBackdropBadge: String = "MAKRO-HINTERGRUND"
    override val macroRainbowCardTitle: String = "🌈 Bitcoin Rainbow Preismodell"
    override val macroRainbowCardSub: String = "Logarithmische Bewertungsbänder"
    override val macroRainbowBadge: String = "HISTORIE"
    override val macroAltSeasonCardTitle: String = "⚡ Altcoin Season Index"
    override val macroAltSeasonCardSub: String = "42/100 · Neutrale Zone (Bitcoin Season)"
    override val macroFearGreedCardTitle: String = "😱 Fear & Greed Index"
    override val macroFearGreedCardSub: String = "68/100 · Gier-Stimmung"

    override val macroUsJobsTitle: String = "US Jobs: Non-Farm Payrolls (NFP)"
    override val macroUsJobsTime: String = "Freitag 15:30 UTC"
    override val macroCpiTitle: String = "US Verbraucherpreisindex (CPI)"
    override val macroCpiTime: String = "Nächster Mi 13:30 UTC"
    override val macroForecastLabel: String = "Prognose"
    override val macroPreviousLabel: String = "Vorherig"
    override val macroVolatilityLabel: String = "Volatilität"
    override val macroConsensusYoyLabel: String = "Konsens YoY"
    override val macroPriorYoyLabel: String = "Vorher YoY"
    override val macroProOnly: String = "🔒 Nur Pro"
    override val macroProHigh: String = "🔒 Hoch"
    override val macroProLockedBadge: String = "🔒 Pro Gesperrt"

    override val macroFedWatchTitle: String = "CME FedWatch: Zinssenkungswahrscheinlichkeit"
    override val macroDxyTitle: String = "DXY: US-Dollar-Index"
    override val macroUs10yTitle: String = "US 10Y: Rendite 10-jähriger US-Staatsanleihen"
    override val macroBrentTitle: String = "Brent Rohöl"

    // Rainbow Chart Strings
    override val rainbowHeaderTitle: String = "Bitcoin Rainbow Chart"
    override val rainbowHeaderSubtitle: String = "Dynamischer Rainbow Chart"
    override val rainbowFormulaTag: String = "Dynamisches Power-Law (94.3% R² Fit)"
    override val rainbowDescription: String = "Dynamisches logarithmisches Regressionsmodell, das die gesamte Preishistorie von Bitcoin seit 2012 abbildet."
    override val rainbowCurrentBandLabel: String = "Aktuelles Bewertungsband"
    override val rainbowCyclePeakTarget: String = "Zyklus-Top-Ziel"
    override val rainbowFireSaleTarget: String = "Fire-Sale-Boden"
    override val rainbowFilterAll: String = "Alle Bänder"
    override val rainbowInspectHelp: String = "Auf dem Chart tippen und ziehen, um historische Preise & Bänder zu prüfen"
    override val halvingVerticalLabel: String = "Halving"
    override val halving2032Est: String = "Halving 2032 (Geschätzt)"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Altcoin Season Index"
    override val altSeasonSubtitle: String = "75% der Top 50 Coins gegenüber Bitcoin über 90 Tage"
    override val altSeasonScoreLabel: String = "Altcoin Season Score"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Neutrale Zone"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val altSeasonOutperformedCount: String = "%d von %d Coins übertrafen BTC"
    override val topPerformers90d: String = "Top 90T Outperformer vs BTC"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Fear & Greed Index"
    override val fearGreedSubtitle: String = "Marktstimmung, Euphorie & Akkumulationsuhr"
    override val fearGreedNow: String = "Jetzt"
    override val fearGreedYesterday: String = "Gestern"
    override val fearGreedLastWeek: String = "Letzte Woche"
    override val fearGreedLastMonth: String = "Letzter Monat"
    override val extremeFearLabel: String = "Extreme Angst"
    override val fearLabel: String = "Angst"
    override val neutralLabel: String = "Neutral"
    override val greedLabel: String = "Gier"
    override val extremeGreedLabel: String = "Extreme Gier"
    override val fearGreedAccumulationTip: String = "Live-Stimmungsablesung. Fehlende Werte erscheinen als Gedankenstrich. Kein Kauf- oder Verkaufsfenster."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Pi Cycle Indikatoren (Top & Boden)"
    override val piCycleSubtitle: String = "Top (111SMA vs 350SMA×2) & Boden (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (HISTORISCHES KREUZ)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BODEN (HISTORISCHES KREUZ)"
    override val piCycleDma111: String = "111-Tage SMA"
    override val piCycleDma350x2: String = "350-Tage SMA × 2 (Top-Schwelle)"
    override val piCycleEma150: String = "150-Tage EMA"
    override val piCycleSma471x0745: String = "471-Tage SMA × 0.745 (Boden-Schwelle)"
    override val piCycleMa200w: String = "200-Wochen SMA Boden"
    override val piCycleDistanceToCross: String = "Abstand zur Pi Top Kreuzung"
    override val piCycleDistanceToBottomCross: String = "Abstand zur Boden-Kreuzung"
    override val piCycleStatusSafeText: String = "Akkumulations- & Expansionsphase (Sichere Zone)"
    override val piCycleStatusAlertText: String = "🚨 PI CYCLE TOP KREUZUNG ERKANNT (Zyklus-Höchststand-Risiko)"
    override val piCycleBottomStatusSafeText: String = "Über dem historischen Boden (Expansionsphase)"
    override val piCycleBottomStatusAlertText: String = "🚨 PI CYCLE BODEN KREUZUNG ERKANNT (historischer Boden)"
    override val piCycleGenerationalSupport: String = "Historische Generations-Unterstützung"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "FUTURES TERMINAL"
    override val futuresOfficialFeedsSub: String = "Offizielle Binance USDT-M Feeds · Keine simulierten Daten"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "VERALTET"
    override val futuresStateOffline: String = "OFFLINE"
    override val futuresStateUnavailable: String = "NICHT VERFÜGBAR"
    override val futuresLastMarkIndexTitle: String = "LAST / MARK / INDEX PREISE"
    override val futuresLastTradedPrice: String = "Letzter Handelspreis"
    override val futuresMarkPrice: String = "Mark-Preis"
    override val futuresIndexPrice: String = "Index-Preis"
    override val futuresBasis: String = "Basis (Mark - Index)"
    override val futuresHigh24h: String = "24h Hoch"
    override val futuresLow24h: String = "24h Tief"
    override val futuresVolume24h: String = "24h Volumen (USDT)"
    override val futuresBboSpreadTitle: String = "BESTES GEBOT / ANGEBOT (BBO) & SPREAD"
    override val futuresBestBid: String = "BESTES GEBOT (BID)"
    override val futuresBestAsk: String = "BESTES ANGEBOT (ASK)"
    override val futuresOrderbookSpread: String = "Orderbuch-Spread:"
    override val futuresPerpFundingTitle: String = "FUNDING-RATE & COUNTDOWN"
    override val futuresCurrentFundingRate: String = "Aktuelle Funding-Rate"
    override val futuresNextFundingIn: String = "Nächste Abrechnung in"
    override val futuresApproxAprLabel: String = "Geschätzter APR (Rate × 3 × 365):"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (15S AKTUALISIERT)"
    override val futuresContracts: String = "Kontrakte"
    override val futuresNoOpenInterest: String = "Keine Open-Interest-Daten"
    override val futuresFearGreed5m: String = "Angst & Gier (5m)"
    override val futuresBtcDominance60s: String = "BTC-Dominanz (60s)"
    override val futuresLiquidationsTapeTitle: String = "🚨 Binance Zwangsschließungen (Liquidationen)"
    override val futuresLiquidationsListening: String = "Live-Stream für Binance-Liquidationen aktiv..."
    override val futuresCaptured: String = "erfasst"
    override val futuresLongLiq: String = "LONG LIQUIDATION (VERKAUF)"
    override val futuresShortLiq: String = "SHORT LIQUIDATION (KAUF)"
    override val futuresTradesTapeTitle: String = "⚡ ECHTZEIT-HANDELSBAND"
    override val futuresTradesAwaiting: String = "Warten auf Handelsfluss..."
    override val futuresPriceHeader: String = "Preis (USDT)"
    override val futuresQtyHeader: String = "Menge"
    override val futuresTimeHeader: String = "Zeit"
    override val futuresLockedTitle: String = "Gesperrtes Pro-Futures-Paar"
    override val futuresLockedDesc: String = "%s (%s) gehört zum Pro-Bereich. Schalten Sie das Orderbuch, Basis-Arbitrage und Perpetual-Daten frei."
    override val futuresLockedButton: String = "Pro-Zugang freischalten"
    override val futuresProPair: String = "Pro-Paar"
    override val futuresSizePrefix: String = "Größe:"

    // Structured 3-Line Metric Explainers (Headers & Micro-copy)
    override val explainerWhatItIsLabel: String = "Was es ist: "
    override val explainerWhatItShowsLabel: String = "Was es zeigt: "
    override val explainerNotASignalLabel: String = "Kein Signal: "

    // Macro Metric Explainers
    override val explainerNfpWhat: String = "Monatliche Veränderung der US-Beschäftigung außerhalb der Landwirtschaft, gemeldet vom Bureau of Labor Statistics."
    override val explainerNfpShows: String = "Lage am Arbeitsmarkt und Wirtschaftsaktivität, die Zinsentscheidungen der Federal Reserve direkt beeinflussen."
    override val explainerNfpNotMean: String = "Makro-Liquiditätskontext für Zinsen, kein direktes Richtungssignal für Kryptomärkte."

    override val explainerCpiWhat: String = "Wichtige Inflationskennzahl zur Erfassung von Preisänderungen bei Waren und Dienstleistungen."
    override val explainerCpiShows: String = "Kaufkraftverlust der Verbraucher und Annäherung an das 2%-Ziel der Fed."
    override val explainerCpiNotMean: String = "Inflationsverlaufskontext, kein automatischer Handelsauslöser."

    override val explainerFedWatchWhat: String = "Implizite Zinssenkungswahrscheinlichkeit, berechnet aus 30-Tage-Fed-Funds-Futures."
    override val explainerFedWatchShows: String = "Marktkonsens bezüglich geldpolitischer Lockerungen der Federal Reserve."
    override val explainerFedWatchNotMean: String = "Marktwahrscheinlichkeitsverteilung, keine garantierte Zusage der Zentralbank."

    override val explainerDxyWhat: String = "Geometrisch gewichteter Index zur Messung der USD-Stärke gegenüber 6 wichtigen Fiat-Währungen."
    override val explainerDxyShows: String = "Globale Dollar-Liquiditätsbedingungen, Kapitalflucht und relative Dollar-Kaufkraft."
    override val explainerDxyNotMean: String = "Makro-Liquiditätsströmung, kein isolierter Bestimmungsfaktor für Krypto-Tiefs oder -Höchststände."

    override val explainerUs10yWhat: String = "Jährliche Rendite für 10-jährige Schuldtitel der US-Regierung."
    override val explainerUs10yShows: String = "Risikofreie globale Kapitalkosten und langfristige Wachstums-/Inflationserwartungen."
    override val explainerUs10yNotMean: String = "Makro-Diskontierungsrate für Risiko-Assets, kein kurzfristiger Auslöser."

    override val explainerBrentWhat: String = "Internationaler Preis-Benchmark für physische Rohöl-Kontrakte."
    override val explainerBrentShows: String = "Energieinflationsdruck bei Rohstoffen und globale Industrieaktivität."
    override val explainerBrentNotMean: String = "Komponente von Inflationsindizes, kein direkter Krypto-Preistreiber."

    // Futures Metric Explainers
    override val explainerFundingWhat: String = "Periodische Finanzierungsgebühr zwischen Longs und Shorts bei Perpetual-Kontrakten."
    override val explainerFundingShows: String = "Positionierungskonzentration der Händler und Hebel-Schieflage an Derivatebörsen."
    override val explainerFundingNotMean: String = "Hohe Schieflage spiegelt Hebel wider, keine unmittelbare oder garantierte Preisumkehr."

    override val explainerOiWhat: String = "Gesamte offene Kontraktpositionen und Dollar-Bewertung in aktiven Perpetual-Verträgen."
    override val explainerOiShows: String = "Netto-Zufluss oder -Abfluss von Derivatekapital und fortlaufende Hebel-Expansion."
    override val explainerOiNotMean: String = "Maß für ausstehende Derivatebindung, kein Richtungsergebnis ohne Preiskontext."

    override val explainerSentimentWhat: String = "Stimmungsindex (0-100) und Marktanteil von Bitcoin an der Gesamtkapitalisierung."
    override val explainerSentimentShows: String = "Risikobereitschaft des Marktes und Kapitalrotation zwischen Bitcoin und Altcoins."
    override val explainerSentimentNotMean: String = "Allgemeine Makro-Markthaltung, kein kurzfristiges Ausführungssignal."

    override val explainerLiqWhat: String = "Zwangsschließungen von Positionen bei Verletzung der Margin-Anforderungen."
    override val explainerLiqShows: String = "Konzentrierte Preisbereiche, an denen überhebelte Konten von der Börse glattgestellt werden."
    override val explainerLiqNotMean: String = "Erzwungene Schließungskaskaden, keine organische institutionelle Akkumulation."

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "KI-Marktanalyst"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Echtzeit-Zyklus-, Futures- & Wal-Intelligenz"
    override val aiPromptPlaceholder: String = "Frage zu BTC-Zyklus, Funding, Support, Altseason..."
    override val aiAskButton: String = "Analysieren"
    override val aiQuickActionCycle: String = "Zyklus & Halving-Risiko"
    override val aiQuickActionFutures: String = "Funding & Hebel-Fluss"
    override val aiQuickActionWhales: String = "Wal-Akkumulation"
    override val aiQuickActionAltseason: String = "Altseason-Bereitschaft"
    override val aiDisclaimer: String = "Unterstützt durch Live-Gemini-KI-Modelle & Echtzeit-Telemetrie. Keine Finanzberatung."
    override val aiThinking: String = "Analysiere Live-Telemetrie & Orderbuch..."
    override val aiGreeting: String = "Ich bin da. Was möchten Sie uns ansehen?"
    override val aiClearHistory: String = "Löschen"
    override val aiLiveContextTag: String = "Live-Daten Verknüpft"
    override val aiPromptPrefixCycle: String = "Analysiere die aktuelle Halving-Zyklusphase, das Risiko und historische Analoga."
    override val aiPromptPrefixFutures: String = "Interpretiere aktuelle Funding-Raten, Open Interest und Liquidationsrisiken."
    override val aiPromptPrefixWhales: String = "Was deuten die jüngsten Wal-Meldungen auf institutionelle Akkumulation oder Distribution hin?"
    override val aiPromptPrefixAltseason: String = "Beurteile, ob Marktbedingungen, BTC-Dominanz und Stimmung aktuell eine Altseason begünstigen."
    override val backtestBadgeText: String = "Live whale radar · live order flow · live liquidations"
    override val derivativesRiskGuardrail: String = "Dieser Bildschirm liest das Perpetual-Tape. Kein Handelsschalter und keine Positionsgröße."

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Market Intelligence Layer: Wie es funktioniert"
    override val marketIntelligenceInfoButton: String = "Was ist das?"
    override val marketIntelligenceConfidenceTitle: String = "Konfidenzwert (z.B. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Misst die quantitative Stärke der aktuellen Futures-Positionierung basierend auf Volumen, Open Interest und Momentum."
    override val marketIntelligenceRegimesHeader: String = "Marktregime (Was die Signale bedeuten)"
    override val regimeShortSqueezeTitle: String = "Short Squeeze Druck"
    override val regimeShortSqueezeDesc: String = "Starke Short-Positionen sind gefangen. Eine minimale Aufwärtsbewegung kann kaskadierende Liquidationen und scharfe Spitzen auslösen."
    override val regimeSpotAccumulationTitle: String = "Spot-Akkumulation"
    override val regimeSpotAccumulationDesc: String = "Echte Spot-Kaufabsorption statt riskantem Hebel. Signalisiert eine gesunde, nachhaltige Marktstruktur."
    override val regimeBalancedConsolidationTitle: String = "Ausgeglichene Konsolidierung"
    override val regimeBalancedConsolidationDesc: String = "Derivate-Hebel und Spot-Nachfrage halten sich die Waage, was auf eine Seitwärtsbewegung hinweist."
    override val marketIntelligenceTelemetryHeader: String = "Wichtigste Telemetrie"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Gesamtes Kapital, das in aktiven Derivatekontrakten gebunden ist."
    override val telemetryFundingRateTitle: String = "Funding Rate"
    override val telemetryFundingRateDesc: String = "Periodische Gebühr zwischen Longs und Shorts. Stark positive Raten warnen vor überhebelten Longs, die anfällig für Liquidationen sind."
    override val marketIntelligenceUnderstood: String = "Verstanden"
}
