package com.example.util

import com.example.data.model.AppLanguage

class GermanAppStrings : AppStrings(AppLanguage.GERMAN) {
    // Navigation & Core
    override val navMarkets: String = "Zyklus"
    override val navCoins: String = "Coins"
    override val navSignals: String = "Tape"
    override val navSettings: String = "Einstellungen"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO AKTIV"
    override val upgradeToPro: String = "Auf Pro upgraden"
    override val searchPlaceholder: String = "100+ Krypto-Assets suchen..."
    override val cryptocurrenciesCount: String = "KRYPTOWÄHRUNGEN"
    override val cryptocurrencySingular: String = "KRYPTOWÄHRUNG"
    override val rankPrefix: String = "Rang"
    override val closeButton: String = "Schließen"
    override val institutionalTerminal: String = "Zyklus- und Derivate-Terminal"
    override val latencyMs: String = "%dms Latenz"
    override val realtimeFeed: String = "LIVE-FEED"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Layer 1"
    override val catLayer2: String = "Layer 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "KI & Infra"
    override val catMeme: String = "Memes"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Utility"
    override val catFavorites: String = "Favoriten"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Marktübersicht"
    override val marketsSubtitle: String = "Wohin sich jeder Coin bewegt, historische Muster, Zukunftsprognosen & Whitepapers."
    override val currentPrice: String = "Aktueller Preis"
    override val analogMatch: String = "Historische Übereinstimmung"
    override val cyclePhase: String = "Zyklusphase"
    override val daysSinceAth: String = "Tage seit ATH"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "HISTORISCHES ZYKLUS-ANALOGON"
    override val historicalAnalogProTitle: String = "Historisches Zyklus-Analogon"
    override val historicalAnalogProUnlockedDesc: String = "Live-Börsenhistorie und realisierte Bewegungen sind aktiv."
    override val historicalAnalogProDesc: String = "Live-Historiencharts und Karten realisierter Bewegungen freischalten."
    override val movementAnalysisHeader: String = "BEWEGUNGSANALYSE & ZYKLUSHISTORIE"
    override val nextMoveHeader: String = "LIVE REALISIERTE BEWEGUNGEN"
    override val cycleFractalLabel: String = "Zyklus-Fraktaltag"
    override val historicalMatchLabel: String = "Wie der Preis von Halving zu Halving gelaufen ist"
    override val proAnalyticsDesc: String = "Die Linien 2016 und 2020 auf demselben Zyklustag freischalten für"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "MARKTSTATISTIKEN & TOKEN-ANGEBOT"
    override val circulatingSupplyLabel: String = "Umlaufendes Angebot:"
    override val circulatingShort: String = "Im Umlauf"
    override val infiniteDeflationary: String = "Unbegrenzt (Deflationär)"
    override val marketCapMetric: String = "MARKTKAPITALISIERUNG"
    override val volume24hMetric: String = "24H-VOLUMEN"
    override val tradingVolumeSub: String = "Handelsvolumen"
    override val fdvMetric: String = "FDV (BEWERTUNG)"
    override val fdvSub: String = "Vollständig verwässerte Bewertung"
    override val athMetric: String = "ALLZEITHOCH (ATH)"
    override val atlMetric: String = "ALLZEITTIEF (ATL)"
    override val drawdownAthMetric: String = "RÜCKGANG VOM ATH"
    override val fromPeakSub: String = "Vom Höchststand"
    override val allTimeLowMetric: String = "Allzeittief"
    override val allTimeHighMetric: String = "Allzeithoch"
    override val startMetric: String = "Start"
    override val daysSinceHighMetric: String = "Tage seit dem Hoch"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & TECHNOLOGIE-BLUEPRINT"
    override val founderLabel: String = "SCHÖPFER / GRÜNDER"
    override val genesisDateLabel: String = "GENESIS-DATUM"
    override val whatCoinDoesLabel: String = "Was der Coin macht (Core Whitepaper Blueprint)"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Emission"
    override val useCasesLabel: String = "Zentrale Ökosystem-Anwendungsfälle"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Wochen seit dem Allzeithoch"
    override val cycleAnalysisHeader: String = "Zyklusanalyse"
    override val fromHighToLowTitle: String = "VOM HOCH ZU EINEM MÖGLICHEN TIEF"
    override val daysAfterAthLabel: String = "Tage nach dem Allzeithoch"
    override val daysToBottomLabel: String = "Tage, frühere Korrekturen (Ø)"
    override val highMarker: String = "Hoch"
    override val fromHighToLowDisclaimer: String = "Das haben vergangene Zyklen gezeigt. Keine Garantie — nur eine Orientierungsuhr."
    override val thisCycleVsLastTitle: String = "DIESER ZYKLUS VS VERGANGENE"
    override val daysAfterHighTitle: String = "Tage nach dem Hoch"
    override val nowLabel: String = "Jetzt"
    override val daysOfRiseTitle: String = "Tage des Anstiegs, historisch"
    override val daysOfRiseSub: String = "Frühere Anstiege vom Tief zum nächsten Hoch dauerten ca. 1059 Tage."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "Tage bis zum nächsten Halving"
    override val halvingHoursLabel: String = "verbleibende Stunden"
    override val whyWeSayThisTitle: String = "Historischer Kontext & Zyklus-Vorbehalte"

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Asset auswählen"
    override val signalsAllCoins: String = "Alle 100+ Kryptowährungen"
    override val timeframe1D: String = "1T"
    override val timeframe1W: String = "1W"
    override val timeframe1M: String = "1M"
    override val timeframe1Y: String = "1J"
    override val timeframeCycle: String = "Makro-Zyklus"
    override val signalBullish: String = "24h HOCH"
    override val signalBearish: String = "24h RUNTER"

    // Settings Screen
    override val settingsHeader: String = "Einstellungen"
    override val languageTitle: String = "Sprache"
    override val languageDesc: String = "Wählen Sie Ihre bevorzugte Sprache"
    override val optionsTitle: String = "Optionen"
    override val soundEffectsTitle: String = "Krypto-Soundeffekte (SFX)"
    override val soundEffectsSub: String = "Kurze Töne beim Tippen, Umschalten und Navigieren"
    override val soundTestTitle: String = "Soundeffekte testen"
    override val soundTestLaunch: String = "Dur-Tonleiter Aufstieg 🎵"
    override val soundTestClick: String = "Tech-Klick"
    override val soundTestToggle: String = "Schalter-Ton"
    override val soundTestChime: String = "Münz-Glockenton"
    override val logChartsTitle: String = "Logarithmische Charts"
    override val logChartsSub: String = "Preise auf logarithmischer Skala darstellen"
    override val proMembershipTitle: String = "Pro-Mitgliedschaft"
    override val manageProSubscription: String = "Pro-Abo verwalten"
    override val proTapeTitle: String = "PRO BANDLESUNG"
    override val proTapeDesc: String = "Live-Lesung von RSI, EMA, ATR, Funding und ETF aus täglichen Schlusskursen. Keine Prognose."
    override val proBenefit1: String = "Linien 2016 und 2020 auf demselben Zyklustag"
    override val proBenefit2: String = "Tagesprotokoll der Live-Zahlen, die die App zeigte"
    override val proBenefit3: String = "Optionale Tageszähl-Benachrichtigung, die das Chart öffnet"
    override val proBenefit4: String = "Live-Tape aus Schlusskursen, Funding und ETF — keine Prognose"
    override val proBenefit5: String = "KI, die nur den Bildschirm-Snapshot liest"
    override val proBenefit6: String = "Extra-Lektionen zu Hebel, Funding und Orderbuch — kein Trade-Aufruf"
    override val currencyDisplayTitle: String = "Anzeigewährung"
    override val howWeReadItTitle: String = "Wie wir es lesen — in einfachen Worten"
    override val plainItem1Title: String = "1. Geschichte wiederholt sich in Zyklen"
    override val plainItem1Desc: String = "Krypto folgt ca. 4-jährigen Halving-Zyklen. Wir vergleichen heute mit demselben Tag nach den Halvings 2012, 2016 und 2020."
    override val plainItem2Title: String = "2. Historische Analoga"
    override val plainItem2Desc: String = "Im Zyklus-Chart ist die violette Kurve 2020, die bernsteinfarbene 2016 und die cyanfarbene Linie der aktuelle Zyklus."
    override val plainItem3Title: String = "3. Historische Zykluszonen"
    override val plainItem3Desc: String = "Mittels logarithmischer Regression berechnen wir historische Zonen zu Studienzwecken. Alle Tools sind bildend und keine Finanzberatung."
    override val plainItem4Title: String = "4. Fundamentale Whitepapers"
    override val plainItem4Desc: String = "Jedes Profil enthält Konsensmodell, Tokenomics, Gründer und echte Anwendungsfälle."
    override val plainItem5Title: String = "5. Risikohinweis"
    override val plainItem5Desc: String = "Vergangene Gewinne garantieren keine zukünftigen Erträge. Investieren Sie mit Bedacht."
    override val privacyPolicyTitle: String = "Nutzungsbedingungen & Datenschutzerklärung"
    override val privacyPolicyView: String = "Unsere Datenrichtlinie einsehen"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Du zahlst für die Linien 2016/2020, das Tagesprotokoll, den Tagesalarm, das Live-Tape und die Extra-Lektionen. Preis, Cap, Fear & Greed und ETF 1 Tag bleiben frei. Keine Prognose."
    override val proModalFeature1: String = "Linien 2016 und 2020 auf demselben Zyklustag"
    override val proModalFeature2: String = "Tagesprotokoll der Live-Zahlen, die die App zeigte"
    override val proModalFeature3: String = "Optionale Tageszähl-Benachrichtigung, die das Chart öffnet"
    override val proModalFeature4: String = "Live-Tape aus Schlusskursen, Funding und ETF — keine Prognose"
    override val proModalFeature5: String = "KI, die nur den Bildschirm-Snapshot liest"
    override val proModalFeature6: String = "Extra-Lektionen zu Hebel, Funding und Orderbuch — kein Trade-Aufruf"
    override val planMonthlyTitle: String = "Monatlich"
    override val planMonthlyPeriod: String = "/ Monat"
    override val planAnnualTitle: String = "Jährlich"
    override val planAnnualPeriod: String = "/ Jahr"
    override val restorePurchases: String = "Käufe wiederherstellen"
    override val restoringPurchases: String = "Google Play Käufe werden überprüft..."
    override val playTermsDisclosure: String = "Die Zahlung wird nach Bestätigung über Ihr Google Play-Konto abgewickelt. Das Abonnement verlängert sich automatisch, sofern es nicht mindestens 24 Stunden vor Ablauf gekündigt wird."
    override val financialDisclaimerTitle: String = "Finanz- und Regulierungshinweis"
    override val financialDisclaimerText: String = "Bildungsgeschichte vergangener Zyklen. Keine Prognose und keine Beratung. CryptoCycles ist keine Börse, verwahrt kein Geld und sagt nicht, dass man kaufen oder verkaufen soll."
    override val privacySheetTitle: String = "CryptoCycles Datenschutz"
    override val privSection1Title: String = "1. Datenerhebung"
    override val privSection1Body: String = "Kauf-/Verkaufsfenster basieren auf historischen Mustern und stellen keine Anlageberatung dar."
    override val privSection2Title: String = "2. Minderjährige"
    override val privSection2Body: String = "CryptoCycles richtet sich nicht an Personen unter 13 Jahren."
    override val privSection3Title: String = "3. Kontakt"
    override val privSection3Body: String = "Für Datenschutzanfragen nutzen Sie die E-Mail im Google Play Store."
    override val privSection4Title: String = "4. Lokale Speicherung"
    override val privSection4Body: String = "CryptoCycles erstellt keine Benutzerkonten und verkauft keine persönlichen Daten. Alle Einstellungen verbleiben lokal auf Ihrem Gerät."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO Zykluslinien und Bandlesung"
    override val signalsProLockedSubtitle: String = "Die Überlagerungen 2016 und 2020 und die Lesung täglicher Schlusskurse. Keine Prognose."
    override val signalsProLockedFeature2: String = "Live-Lesung (RSI, EMA, ATR aus täglichen Schlusskursen)"
    override val signalsProLockedFeature3: String = "Tägliches Zyklusprotokoll dessen, was die App zeigte"
    override val signalsGateTitle: String = "Zyklusüberlagerungen und Bandlesung"
    override val signalsGateDesc: String = "Linien 2016 und 2020 und die Live-Lesung täglicher Schlusskurse. Kein Signal und keine Prognose."
    override val signalsGateBadge: String = "Live-Schlusskurse · Live-Funding · Live-ETF"

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "WÖCHENTLICHES MAKRO-BRIEFING"
    override val weeklyBriefingSub: String = "Wöchentliche institutionelle Zyklus-Synthese & Risikohaltung"
    override val weeklyBriefingCurrentZone: String = "Aktuelle Makro-Zone"
    override val weeklyBriefingActionTitle: String = "Empfohlene Haltung"
    override val weeklyBriefingReasonTitle: String = "3-Punkte-Synthese"
    override val weeklyBriefingProUnlockText: String = "Schalten Sie das institutionelle wöchentliche Briefing, das Zonen-Playbook und Makro-Analoga mit Pro frei."

    override val historicalAnalogProUnlockText: String = "Linien 2016 und 2020 auf demselben Zyklustag. Nur Historie — kein projizierter Pfad."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Zyklus- & Indikator-Push-Alerts"
    override val alertSettingsSub: String = "Sofortige Benachrichtigungen für kritische Marktzyklus-Schwellenwerte"
    override val alertZoneChangeTitle: String = "Zonenwechsel-Alarm"
    override val alertZoneChangeDesc: String = "Benachrichtigen, wenn sich die Stimmungszone ändert (Angst, Neutral, Heißes Funding, Extrem), aus Fear & Greed und Funding"
    override val alertPiCycleTitle: String = "Pi Cycle Top Abstand & Kreuzung"
    override val alertPiCycleDesc: String = "Benachrichtigen, wenn der 111DMA bis auf 10 % an den 350DMA × 2 heranrückt, ihn kreuzt oder sich entfernt. Tägliche Prüfung"
    override val alertRainbowTitle: String = "Rainbow-Bänder-Übergang"
    override val alertRainbowDesc: String = "Benachrichtigung, wenn Bitcoin zwischen Rainbow-Bewertungsbändern wechselt"
    override val alert200WTitle: String = "Abstand zum 200-Wochen-SMA"
    override val alert200WDesc: String = "Benachrichtigen, wenn der Preis unter den 200W SMA fällt, bis 10 % darüber liegt oder 2,5× darüber. Tägliche Prüfung"
    override val alertFreeLimitNotice: String = "Die Free-Version umfasst bis zu 2 aktive Alerts. Upgraden Sie auf Pro für unbegrenzte Alerts."
    override val alertProUnlockNotice: String = "PRO-Funktion: Unbegrenzte Push-Alerts für Zyklen, Pi Cycle und Rainbow."

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "GROSSE BINANCE-USDT-M-PRINTS (PRO)"
    override val whaleRadarSub: String = "Binance USDT-M Futures-Prints ab $100k. Keine On-Chain-Wallet-Transfers."
    override val whaleNotificationsTitle: String = "Wal-Alarm Push-Benachrichtigungen"
    override val whaleNotificationsDesc: String = "Push für einen einzelnen Binance-USDT-M-Futures-Trade über deiner Größe, solange die App offen ist."
    override val whaleNotificationsProLockedDesc: String = "Pro: Hinweis, wenn ein Binance-USDT-M-Print den Filter überschreitet. Keine On-Chain-Transfers."
    override val whaleThresholdTitle: String = "Mindestgröße für Wal-Alerts"
    override val whaleFilterAll: String = "Alle Wale"
    override val whaleFilterInflow: String = "🔻 Große Verkäufe"
    override val whaleFilterBuy: String = "🔺 Große Käufe"
    override val whaleCollapse: String = "Einklappen"
    override val whaleViewAll: String = "Alle anzeigen (%d)"
    override val timeJustNow: String = "Gerade eben"
    override val timeMinsAgo: String = "vor %d Min."
    override val timeHoursAgo: String = "vor %d Std."
    override val liveOrderFlowTitle: String = "24/7 LIVE ORDERFLOW (BINANCE)"
    override val liveOrderFlowSub: String = "Große Binance-USDT-M-Prints der Majors: Kauf- vs. Verkaufsdruck"
    override val buyDominanceLabel: String = "KAUFDRUCK"
    override val sellDominanceLabel: String = "VERKAUFSDRUCK"
    override val liveExecutionFeed: String = "LIVE-AUSFÜHRUNGEN"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Makro- & Zyklusindizes"
    override val macroScreenSubtitle: String = "Institutionelle Bewertungsmodelle, Rainbow Power-Law & Marktstimmung"
    override val macroProLockedTitle: String = "PRO historische Zykluswerkzeuge"
    override val macroProLockedSubtitle: String = "Rainbow-Bänder, Pi-Cycle-Kreuze und das wöchentliche Faktenbriefing. Kein Kauf- oder Verkaufssignal."
    override val macroGateTitle: String = "Historische Zykluswerkzeuge"
    override val macroGateDesc: String = "Rainbow-Bänder, Pi-Cycle-Kreuze und wöchentliche Fakten. Nur Historie — kein Trade."

    override val macroRainbowBadge: String = "HISTORIE"

    override val macroProLockedBadge: String = "🔒 Pro Gesperrt"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Altcoin Season Index"
    override val altSeasonSubtitle: String = "75% der Top 50 Coins gegenüber Bitcoin über 90 Tage"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Neutrale Zone"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val topPerformers90d: String = "Top 90T Outperformer vs BTC"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Fear & Greed Index"
    override val fearGreedSubtitle: String = "Marktstimmung, Euphorie & Akkumulationsuhr"
    override val fearGreedYesterday: String = "Gestern"
    override val fearGreedLastWeek: String = "Letzte Woche"
    override val fearGreedLastMonth: String = "Letzter Monat"
    override val extremeFearLabel: String = "Extreme Angst"
    override val fearLabel: String = "Angst"
    override val neutralLabel: String = "Neutral"
    override val greedLabel: String = "Gier"
    override val extremeGreedLabel: String = "Extreme Gier"
    override val fearGreedAccumulationTip: String = "Live-Stimmungsablesung. Fehlende Werte erscheinen als Gedankenstrich. Kein Kauf- oder Verkaufsfenster."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Pi Cycle Indikatoren (Top & Boden)"
    override val piCycleSubtitle: String = "Top (111SMA vs 350SMA×2) & Boden (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (HISTORISCHES KREUZ)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BODEN (HISTORISCHES KREUZ)"
    override val piCycleDma111: String = "111-Tage SMA"
    override val piCycleDma350x2: String = "350-Tage SMA × 2 (Top-Schwelle)"
    override val piCycleEma150: String = "150-Tage EMA"
    override val piCycleSma471x0745: String = "471-Tage SMA × 0.745 (Boden-Schwelle)"
    override val piCycleMa200w: String = "200-Wochen SMA Boden"
    override val piCycleStatusSafeText: String = "Akkumulations- & Expansionsphase (Sichere Zone)"
    override val piCycleStatusAlertText: String = "🚨 PI CYCLE TOP KREUZUNG ERKANNT (Zyklus-Höchststand-Risiko)"
    override val piCycleBottomStatusSafeText: String = "Über dem historischen Boden (Expansionsphase)"
    override val piCycleBottomStatusAlertText: String = "🚨 PI CYCLE BODEN KREUZUNG ERKANNT (historischer Boden)"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "FUTURES TERMINAL"
    override val futuresOfficialFeedsSub: String = "Offizielle Binance USDT-M Feeds · Keine simulierten Daten"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "VERALTET"
    override val futuresStateOffline: String = "OFFLINE"
    override val futuresStateUnavailable: String = "NICHT VERFÜGBAR"
    override val futuresLastMarkIndexTitle: String = "LAST / MARK / INDEX PREISE"
    override val futuresLastTradedPrice: String = "Letzter Handelspreis"
    override val futuresMarkPrice: String = "Mark-Preis"
    override val futuresIndexPrice: String = "Index-Preis"
    override val futuresBasis: String = "Basis (Mark - Index)"
    override val futuresHigh24h: String = "24h Hoch"
    override val futuresLow24h: String = "24h Tief"
    override val futuresVolume24h: String = "24h Volumen (USDT)"
    override val futuresBboSpreadTitle: String = "BESTES GEBOT / ANGEBOT (BBO) & SPREAD"
    override val futuresBestBid: String = "BESTES GEBOT (BID)"
    override val futuresBestAsk: String = "BESTES ANGEBOT (ASK)"
    override val futuresOrderbookSpread: String = "Orderbuch-Spread:"
    override val futuresPerpFundingTitle: String = "FUNDING-RATE & COUNTDOWN"
    override val futuresCurrentFundingRate: String = "Aktuelle Funding-Rate"
    override val futuresNextFundingIn: String = "Nächste Abrechnung in"
    override val futuresApproxAprLabel: String = "Geschätzter APR (Rate × 3 × 365):"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (15S AKTUALISIERT)"
    override val futuresContracts: String = "Kontrakte"
    override val futuresLiquidationsListening: String = "Live-Stream für Binance-Liquidationen aktiv..."
    override val futuresLongLiq: String = "LONG LIQUIDATION (VERKAUF)"
    override val futuresShortLiq: String = "SHORT LIQUIDATION (KAUF)"
    override val futuresTradesTapeTitle: String = "⚡ ECHTZEIT-HANDELSBAND"
    override val futuresTradesAwaiting: String = "Warten auf Handelsfluss..."
    override val futuresPriceHeader: String = "Preis (USDT)"
    override val futuresQtyHeader: String = "Menge"
    override val futuresTimeHeader: String = "Zeit"
    override val futuresLockedTitle: String = "Gesperrtes Pro-Futures-Paar"
    override val futuresLockedDesc: String = "%s (%s) gehört zum Pro-Bereich. Schalten Sie das Orderbuch, Basis-Arbitrage und Perpetual-Daten frei."
    override val futuresLockedButton: String = "Pro-Zugang freischalten"
    override val futuresSizePrefix: String = "Größe:"

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "KI-Marktanalyst"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Echtzeit-Zyklus-, Futures- & Wal-Intelligenz"
    override val aiPromptPlaceholder: String = "Frage zu BTC-Zyklus, Funding, Support, Altseason..."
    override val aiAskButton: String = "Analysieren"
    override val aiQuickActionCycle: String = "Zyklus & Halving-Risiko"
    override val aiQuickActionFutures: String = "Funding & Hebel-Fluss"
    override val aiQuickActionWhales: String = "Wal-Akkumulation"
    override val aiQuickActionAltseason: String = "Altseason-Bereitschaft"
    override val aiDisclaimer: String = "Unterstützt durch Live-Gemini-KI-Modelle & Echtzeit-Telemetrie. Keine Finanzberatung."
    override val aiThinking: String = "Analysiere Live-Telemetrie & Orderbuch..."
    override val aiGreeting: String = "Ich bin da. Was möchten Sie uns ansehen?"
    override val aiClearHistory: String = "Löschen"
    override val aiLiveContextTag: String = "Live-Daten Verknüpft"
    override val aiPromptPrefixCycle: String = "Analysiere die aktuelle Halving-Zyklusphase, das Risiko und historische Analoga."
    override val aiPromptPrefixFutures: String = "Interpretiere aktuelle Funding-Raten, Open Interest und Liquidationsrisiken."
    override val aiPromptPrefixWhales: String = "Was deuten die jüngsten Wal-Meldungen auf institutionelle Akkumulation oder Distribution hin?"
    override val aiPromptPrefixAltseason: String = "Beurteile, ob Marktbedingungen, BTC-Dominanz und Stimmung aktuell eine Altseason begünstigen."
    override val backtestBadgeText: String = "Live whale radar · live order flow · live liquidations"
    override val derivativesRiskGuardrail: String = "Dieser Bildschirm liest das Perpetual-Tape. Kein Handelsschalter und keine Positionsgröße."

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Market Intelligence Layer: Wie es funktioniert"
    override val marketIntelligenceInfoButton: String = "Was ist das?"
    override val marketIntelligenceConfidenceTitle: String = "Konfidenzwert (z.B. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Misst die quantitative Stärke der aktuellen Futures-Positionierung basierend auf Volumen, Open Interest und Momentum."
    override val marketIntelligenceRegimesHeader: String = "Marktregime (Was die Signale bedeuten)"
    override val regimeShortSqueezeTitle: String = "Short Squeeze Druck"
    override val regimeShortSqueezeDesc: String = "Starke Short-Positionen sind gefangen. Eine minimale Aufwärtsbewegung kann kaskadierende Liquidationen und scharfe Spitzen auslösen."
    override val regimeSpotAccumulationTitle: String = "Spot-Akkumulation"
    override val regimeSpotAccumulationDesc: String = "Echte Spot-Kaufabsorption statt riskantem Hebel. Signalisiert eine gesunde, nachhaltige Marktstruktur."
    override val regimeBalancedConsolidationTitle: String = "Ausgeglichene Konsolidierung"
    override val regimeBalancedConsolidationDesc: String = "Derivate-Hebel und Spot-Nachfrage halten sich die Waage, was auf eine Seitwärtsbewegung hinweist."
    override val marketIntelligenceTelemetryHeader: String = "Wichtigste Telemetrie"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Gesamtes Kapital, das in aktiven Derivatekontrakten gebunden ist."
    override val telemetryFundingRateTitle: String = "Funding Rate"
    override val telemetryFundingRateDesc: String = "Periodische Gebühr zwischen Longs und Shorts. Stark positive Raten warnen vor überhebelten Longs, die anfällig für Liquidationen sind."
    override val marketIntelligenceUnderstood: String = "Verstanden"
}
