package com.example.util

import com.example.data.model.AppLanguage

class GreekAppStrings : AppStrings(AppLanguage.GREEK) {
    // Navigation & Core
    override val navMarkets: String = "Κύκλος"
    override val navCoins: String = "Νομίσματα"
    override val navSignals: String = "Ταινία"
    override val navLearn: String = "Learn"
    override val navSettings: String = "Ρυθμίσεις"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO ΕΝΕΡΓΟ"
    override val upgradeToPro: String = "Αναβάθμιση σε Pro"
    override val viewDetails: String = "Προβολή λεπτομερειών"
    override val searchPlaceholder: String = "Αναζήτηση σε 100+ crypto..."
    override val cryptocurrenciesCount: String = "ΚΡΥΠΤΟΝΟΜΙΣΜΑΤΑ"
    override val cryptocurrencySingular: String = "ΚΡΥΠΤΟΝΟΜΙΣΜΑ"
    override val rankPrefix: String = "Κατάταξη"
    override val closeButton: String = "Κλείσιμο"
    override val institutionalTerminal: String = "Επαγγελματικό Τερματικό Κύκλων & Παραγώγων"
    override val latencyMs: String = "%dms καθυστέρηση"
    override val realtimeFeed: String = "ΖΩΝΤΑΝΗ ΡΟΗ"
    override val refreshTooltip: String = "Ανανέωση ροών αγοράς"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Layer 1"
    override val catLayer2: String = "Layer 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "AI & Υποδομές"
    override val catMeme: String = "Memes"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Χρησιμότητα"
    override val catFavorites: String = "Αγαπημένα"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Επισκόπηση Αγοράς"
    override val marketsSubtitle: String = "Πού κινείται κάθε coin, προηγούμενα ιστορικά μοτίβα, μελλοντικές προβολές & whitepapers."
    override val currentPrice: String = "Τρέχουσα Τιμή"
    override val analogMatch: String = "Ιστορικό Ταίριασμα"
    override val cyclePhase: String = "Φάση Κύκλου"
    override val daysSinceAth: String = "Ημέρες από το ATH"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "ΙΣΤΟΡΙΚΟ ΑΝΑΛΟΓΟ ΚΥΚΛΟΥ"
    override val historicalAnalogProTitle: String = "Ιστορικό Ανάλογο Κύκλου"
    override val historicalAnalogProUnlockedDesc: String = "Ζωντανό ιστορικό χρηματιστηρίου και πραγματοποιημένες κινήσεις είναι ενεργά."
    override val historicalAnalogProDesc: String = "Ξεκλειδώστε live γραφήματα ιστορικού και κάρτες πραγματοποιημένων κινήσεων."
    override val movementAnalysisHeader: String = "ΑΝΑΛΥΣΗ ΚΙΝΗΣΗΣ & ΙΣΤΟΡΙΚΟ ΚΥΚΛΩΝ"
    override val nextMoveHeader: String = "ΖΩΝΤΑΝΕΣ ΠΡΑΓΜΑΤΟΠΟΙΗΜΕΝΕΣ ΚΙΝΗΣΕΙΣ"
    override val cycleFractalLabel: String = "Ημέρα Fractal Κύκλου"
    override val historicalMatchLabel: String = "Πώς κινήθηκε η τιμή από halving μέχρι το επόμενο"
    override val cycleChartTapToInspect: String = "Αγγίξτε ή σύρετε για να δείτε την ημέρα του κύκλου"
    override val cycleChartDayLabel: String = "Ημέρα"
    override val cycleChartModeCurrent: String = "2024"
    override val cycleChartModeAll: String = "Όλα"
    override val cycleChartModeProjection: String = "Διάδρομος Πρόβλεψης"
    override val cycleChartCurrentPoint: String = "2024"
    override val cycleChartProjectedPath: String = "Προβλεπόμενη Πορεία Fractal"
    override val proAnalyticsDesc: String = "Ξεκλειδώστε τις γραμμές 2016 και 2020 στην ίδια ημέρα κύκλου για το"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "ΣΤΑΤΙΣΤΙΚΑ ΑΓΟΡΑΣ & ΠΡΟΣΦΟΡΑ TOKEN"
    override val circulatingSupplyLabel: String = "Κυκλοφορούσα Προσφορά:"
    override val circulatingShort: String = "Κυκλοφορία"
    override val infiniteDeflationary: String = "Άπειρη (Αποπληθωριστική)"
    override val marketCapMetric: String = "ΚΕΦΑΛΑΙΟΠΟΙΗΣΗ"
    override val volume24hMetric: String = "ΟΓΚΟΣ 24Ω"
    override val tradingVolumeSub: String = "Όγκος συναλλαγών"
    override val fdvMetric: String = "FDV (ΠΛΗΡΗΣ ΑΠΟΤΙΜΗΣΗ)"
    override val fdvSub: String = "Πλήρως αραιωμένη αξία"
    override val athMetric: String = "ΙΣΤΟΡΙΚΟ ΥΨΗΛΟ (ATH)"
    override val atlMetric: String = "ΙΣΤΟΡΙΚΟ ΧΑΜΗΛΟ (ATL)"
    override val drawdownAthMetric: String = "ΠΤΩΣΗ ΑΠΟ ATH"
    override val fromPeakSub: String = "Από την κορυφή"
    override val allTimeLowMetric: String = "Ιστορικό χαμηλό"
    override val allTimeHighMetric: String = "Ιστορικό υψηλό"
    override val startMetric: String = "Έναρξη"
    override val daysSinceHighMetric: String = "Ημέρες από το υψηλό"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & ΤΕΧΝΟΛΟΓΙΚΟ ΠΛΑΝΟ"
    override val founderLabel: String = "ΔΗΜΙΟΥΡΓΟΣ / ΙΔΡΥΤΗΣ"
    override val genesisDateLabel: String = "ΗΜΕΡΟΜΗΝΙΑ ΓΕΝΕΣΗΣ"
    override val whatCoinDoesLabel: String = "Τι κάνει το crypto (Core Whitepaper Blueprint)"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Έκδοση"
    override val useCasesLabel: String = "Κύριες Χρήσεις Οικοσυστήματος"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Εβδομάδες από το ιστορικό υψηλό"
    override val cycleAnalysisHeader: String = "Ανάλυση κύκλου"
    override val fromHighToLowTitle: String = "ΑΠΟ ΤΟ ΥΨΗΛΟ ΣΕ ΕΝΑ ΠΙΘΑΝΟ ΧΑΜΗΛΟ"
    override val daysAfterAthLabel: String = "ημέρες μετά το ιστορικό υψηλό"
    override val daysToBottomLabel: String = "ημέρες, μέσος όρος παλιών διορθώσεων"
    override val highMarker: String = "Υψηλό"
    override val fromHighToLowDisclaimer: String = "Αυτό έκαναν οι προηγούμενοι κύκλοι. Δεν είναι υπόσχεση — είναι απλώς ένα ρολόι."
    override val thisCycleVsLastTitle: String = "ΑΥΤΟΣ Ο ΚΥΚΛΟΣ VS ΟΙ ΠΡΟΗΓΟΥΜΕΝΟΙ"
    override val daysAfterHighTitle: String = "Ημέρες μετά το υψηλό"
    override val nowLabel: String = "Τώρα"
    override val daysOfRiseTitle: String = "Ημέρες ανόδου, ιστορικά"
    override val daysOfRiseSub: String = "Οι παλαιότερες άνοδοι από τον πάτο στο επόμενο υψηλό διήρκεσαν περίπου 1059 ημέρες."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "ημέρες μέχρι το επόμενο halving"
    override val halvingHoursLabel: String = "ώρες απομένουν"
    override val whyWeSayThisTitle: String = "Ζωντανό Πλαίσιο Αγοράς"

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Επιλογή Asset"
    override val signalsAllCoins: String = "Όλα τα 100+ Crypto"
    override val timeframe1D: String = "1Η"
    override val timeframe1W: String = "1Ε"
    override val timeframe1M: String = "1Μ"
    override val timeframe1Y: String = "1ΕΤ"
    override val timeframeCycle: String = "Κύκλος Macro"
    override val signalBullish: String = "24ω ΑΝΟΔΟΣ"
    override val signalBearish: String = "24ω ΠΤΩΣΗ"

    // Settings Screen
    override val settingsHeader: String = "Ρυθμίσεις"
    override val languageTitle: String = "Γλώσσα"
    override val languageDesc: String = "Επιλέξτε την προτιμώμενη γλώσσα σας"
    override val optionsTitle: String = "Επιλογές"
    override val soundEffectsTitle: String = "Ηχητικά Εφέ Crypto (SFX)"
    override val soundEffectsSub: String = "Σύντομοι ήχοι στα πατήματα, στους διακόπτες και στην πλοήγηση"
    override val soundTestTitle: String = "Δοκιμή Ήχων"
    override val soundTestLaunch: String = "Άνοδος Μείζονος Κλίμακας 🎵"
    override val soundTestClick: String = "Τεχνολογικό Πάτημα"
    override val soundTestToggle: String = "Ήχος Εναλλαγής"
    override val soundTestChime: String = "Ήχος Επιβράβευσης Coin"
    override val logChartsTitle: String = "Λογαριθμικά Διαγράμματα"
    override val logChartsSub: String = "Προβολή τιμών σε λογαριθμική κλίμακα για εξομάλυνση ποσοστιαίων μεταβολών"
    override val proMembershipTitle: String = "Συνδρομή Pro"
    override val manageProSubscription: String = "Διαχείριση συνδρομής Pro"
    override val proTapeTitle: String = "PRO ΑΝΑΓΝΩΣΗ ΤΑΙΝΙΑΣ"
    override val proTapeDesc: String = "Ξεκλειδώστε τη ζωντανή ανάγνωση RSI, EMA, ATR, funding και ETF από ημερήσια κλεισίματα. Όχι πρόβλεψη."
    override val proBenefit1: String = "Γραμμές 2016 και 2020 στην ίδια ημέρα κύκλου"
    override val proBenefit2: String = "Ημερολόγιο με τα ζωντανά νούμερα που έδειξε το app"
    override val proBenefit3: String = "Προαιρετική ειδοποίηση ημέρας που ανοίγει το γράφημα"
    override val proBenefit4: String = "Ζωντανή ταινία κλεισιμάτων, funding και ETF — όχι πρόβλεψη"
    override val proBenefit5: String = "AI που διαβάζει μόνο την οθόνη"
    override val proBenefit6: String = "Επιπλέον μαθήματα για μόχλευση, funding και βιβλίο εντολών — χωρίς εντολή συναλλαγής"
    override val currencyDisplayTitle: String = "Νόμισμα Προβολής"
    override val howWeReadItTitle: String = "Πώς το διαβάζουμε — με απλά λόγια"
    override val plainItem1Title: String = "1. Η ιστορία επαναλαμβάνεται σε κύκλους"
    override val plainItem1Desc: String = "Τα crypto ακολουθούν κύκλους halving περίπου 4 ετών. Συγκρίνουμε το σήμερα με την ίδια μέρα μετά τα halving του 2012, 2016 και 2020."
    override val plainItem2Title: String = "2. Ιστορικά Ανάλογα"
    override val plainItem2Desc: String = "Στο γράφημα κύκλου η μωβ καμπύλη είναι το 2020, η πορτοκαλί το 2016 και η κυανή γραμμή ο τρέχων κύκλος."
    override val plainItem3Title: String = "3. Ιστορικές Ζώνες Κύκλου"
    override val plainItem3Desc: String = "Μέσω λογαριθμικής παλινδρόμησης υπολογίζουμε ιστορικές ζώνες για εκπαιδευτική μελέτη. Όλα τα εργαλεία είναι εκπαιδευτικά και δεν αποτελούν οικονομική συμβουλή."
    override val plainItem4Title: String = "4. Θεμελιώδη Whitepapers"
    override val plainItem4Desc: String = "Κάθε προφίλ περιλαμβάνει μοντέλο συναίνεσης, tokenomics, ιδρυτές και πραγματικές χρήσεις."
    override val plainItem5Title: String = "5. Προειδοποίηση Κινδύνου"
    override val plainItem5Desc: String = "Οι παρελθοντικές αποδόσεις δεν εγγυώνται μελλοντικά αποτελέσματα. Επενδύετε με σύνεση."
    override val privacyPolicyTitle: String = "Όροι Χρήσης & Απόρρητο"
    override val privacyPolicyView: String = "Δείτε την πολιτική συλλογής & αποθήκευσης δεδομένων"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Πληρώνεις για τις γραμμές 2016/2020, το ημερολόγιο, την ειδοποίηση ημέρας, τη ζωντανή ταινία και τα επιπλέον μαθήματα. Τιμή, cap, Fear & Greed και ETF 1 ημέρας μένουν δωρεάν. Όχι πρόβλεψη."
    override val proModalFeature1: String = "Γραμμές 2016 και 2020 στην ίδια ημέρα κύκλου"
    override val proModalFeature2: String = "Ημερολόγιο με τα ζωντανά νούμερα που έδειξε το app"
    override val proModalFeature3: String = "Προαιρετική ειδοποίηση ημέρας που ανοίγει το γράφημα"
    override val proModalFeature4: String = "Ζωντανή ταινία κλεισιμάτων, funding και ETF — όχι πρόβλεψη"
    override val proModalFeature5: String = "AI που διαβάζει μόνο την οθόνη"
    override val proModalFeature6: String = "Επιπλέον μαθήματα για μόχλευση, funding και βιβλίο εντολών — χωρίς εντολή συναλλαγής"
    override val planMonthlyTitle: String = "Μηνιαίο"
    override val planMonthlyPeriod: String = "/ μήνα"
    override val planAnnualTitle: String = "Ετήσιο"
    override val planAnnualPeriod: String = "/ έτος"
    override val restorePurchases: String = "Επαναφορά Αγορών"
    override val restoringPurchases: String = "Έλεγχος αγορών από το Google Play..."
    override val playTermsDisclosure: String = "Η πληρωμή χρεώνεται στον λογαριασμό Google Play κατά την επιβεβαίωση. Η συνδρομή ανανεώνεται αυτόματα εκτός αν ακυρωθεί τουλάχιστον 24 ώρες πριν από το τέλος της περιόδου."
    override val financialDisclaimerTitle: String = "Οικονομική & Κανονιστική Αποποίηση Ευθύνης"
    override val financialDisclaimerText: String = "Εκπαιδευτικό ιστορικό παρελθόντων κύκλων. Δεν είναι πρόβλεψη και δεν είναι συμβουλή. Το CryptoCycles δεν είναι ανταλλακτήριο, δεν κρατά κεφάλαια και δεν λέει να αγοράσεις ή να πουλήσεις."
    override val privacySheetTitle: String = "Απόρρητο CryptoCycles"
    override val privSection1Title: String = "1. Συλλογή Δεδομένων & Απόρρητο"
    override val privSection1Body: String = "Το CryptoCycles δεν συλλέγει, δεν πωλεί και δεν εκμεταλλεύεται προσωπικά δεδομένα ταυτοποίησης. Τα δεδομένα αγοράς, τα ιστορικά αναλογικά και η τηλεμετρία αντλούνται ανώνυμα από δημόσιες πηγές blockchain και ανταλλακτηρίων. Όλα τα εργαλεία παρέχονται αποκλειστικά για εκπαιδευτική και ερευνητική χρήση και δεν αποτελούν επενδυτική συμβουλή."
    override val privSection2Title: String = "2. Ανηλίκοι"
    override val privSection2Body: String = "Το CryptoCycles δεν απευθύνεται σε παιδιά κάτω των 13 ετών."
    override val privSection3Title: String = "3. Επικοινωνία"
    override val privSection3Body: String = "Για απορίες απορρήτου, χρησιμοποιήστε το email επικοινωνίας στο Google Play."
    override val privSection4Title: String = "4. Τοπική Αποθήκευση"
    override val privSection4Body: String = "Το CryptoCycles δεν δημιουργεί λογαριασμούς ούτε πωλεί προσωπικά δεδομένα. Όλες οι προτιμήσεις παραμένουν στη συσκευή σας."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO γραμμές κύκλου και ανάγνωση ταινίας"
    override val signalsProLockedSubtitle: String = "Πληρώνεις για τις επικαλύψεις 2016 και 2020 και τη ζωντανή ταινία. Η τιμή και το 24ω μένουν δωρεάν. Όχι πρόβλεψη."
    override val signalsProLockedFeature2: String = "Ζωντανή ταινία κλεισιμάτων, funding και ETF"
    override val signalsProLockedFeature3: String = "Ημερολόγιο με τα ζωντανά νούμερα που έδειξε το app"
    override val signalsGateTitle: String = "Επικαλύψεις κύκλου και ανάγνωση ταινίας"
    override val signalsGateDesc: String = "Ξεκλειδώνει τις γραμμές 2016 και 2020 και τη ζωντανή ανάγνωση ημερήσιων κλεισιμάτων. Όχι σήμα και όχι πρόβλεψη."
    override val signalsGateBadge: String = "Ζωντανά κλεισίματα · live funding · live ETF"

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "ΕΒΔΟΜΑΔΙΑΙΑ ΕΝΗΜΕΡΩΣΗ MACRO"
    override val weeklyBriefingSub: String = "Εβδομαδιαία θεσμική σύνθεση κύκλου & στάση κινδύνου"
    override val weeklyBriefingCurrentZone: String = "Τρέχουσα Ζώνη Macro"
    override val weeklyBriefingActionTitle: String = "Προτεινόμενη Στάση"
    override val weeklyBriefingReasonTitle: String = "Σύνθεση 3 Σημείων"
    override val weeklyBriefingProUnlockText: String = "Ξεκλειδώστε τη θεσμική Εβδομαδιαία Ενημέρωση, το πλάνο ζωνών και τα ανάλογα macro με Pro."

    override val historicalAnalogProUnlockText: String = "Ξεκλειδώνει τις γραμμές 2016 και 2020 στην ίδια ημέρα κύκλου. Μόνο ιστορικό — χωρίς προβλεπόμενη γραμμή."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Ειδοποιήσεις Push Κύκλων & Δεικτών"
    override val alertSettingsSub: String = "Άμεσες ειδοποιήσεις στη συσκευή για κρίσιμα όρια του κύκλου της αγοράς"
    override val alertZoneChangeTitle: String = "Ειδοποίηση Αλλαγής Ζώνης"
    override val alertZoneChangeDesc: String = "Ενημέρωση όταν αλλάζει η ζώνη κλίματος αγοράς (Φόβος, Ουδέτερο, Ζεστό funding, Ακραίο), από Fear & Greed και funding"
    override val alertPiCycleTitle: String = "Απόκλιση & Διασταύρωση Pi Cycle Top"
    override val alertPiCycleDesc: String = "Ενημέρωση όταν ο 111DMA φτάνει σε απόσταση 10% από τον 350DMA × 2, τον περνά ή απομακρύνεται. Έλεγχος μία φορά τη μέρα"
    override val alertRainbowTitle: String = "Μετάβαση Ζώνης Rainbow"
    override val alertRainbowDesc: String = "Ενημέρωση όταν το Bitcoin μεταβαίνει μεταξύ των ζωνών αποτίμησης Rainbow"
    override val alert200WTitle: String = "Απόσταση από 200W SMA"
    override val alert200WDesc: String = "Ενημέρωση όταν η τιμή πέφτει κάτω από τον 200W SMA, είναι έως 10% πάνω του ή 2.5× πάνω του. Έλεγχος μία φορά τη μέρα"
    override val alertFreeLimitNotice: String = "Η δωρεάν έκδοση περιλαμβάνει έως 2 ενεργές ειδοποιήσεις. Αναβαθμίστε σε Pro για απεριόριστες."
    override val alertProUnlockNotice: String = "PRO λειτουργία: Απεριόριστες ειδοποιήσεις push για κύκλους, Pi Cycle και Rainbow."

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "ΜΕΓΑΛΑ PRINTS BINANCE USDT-M (PRO)"
    override val whaleRadarSub: String = "Prints Binance USDT-M από $100k. Όχι μεταφορές on-chain πορτοφολιών."
    override val whaleNotificationsTitle: String = "Ειδοποιήσεις Push Ραντάρ Φαλαινών"
    override val whaleNotificationsDesc: String = "Ειδοποίηση για μία συναλλαγή Binance USDT-M futures πάνω από το όριό σου, όσο η εφαρμογή είναι ανοιχτή."
    override val whaleNotificationsProLockedDesc: String = "Pro: ειδοποίηση όταν ένα print Binance USDT-M περνά το φίλτρο μεγέθους. Όχι μεταφορές on-chain."
    override val whaleThresholdTitle: String = "Ελάχιστο Μέγεθος Ειδοποίησης Φαλαινών"
    override val whaleFilterAll: String = "Όλες οι Φάλαινες"
    override val whaleFilterInflow: String = "🔻 Μεγάλες πωλήσεις"
    override val whaleFilterBuy: String = "🔺 Μεγάλες αγορές"
    override val whaleCollapse: String = "Σύμπτυξη"
    override val whaleViewAll: String = "Προβολή όλων (%d)"
    override val timeJustNow: String = "Μόλις τώρα"
    override val timeMinsAgo: String = "πριν %dλ"
    override val timeHoursAgo: String = "πριν %dω"
    override val liveOrderFlowTitle: String = "24/7 LIVE ΡΟΗ ΕΝΤΟΛΩΝ (BINANCE)"
    override val liveOrderFlowSub: String = "Μεγάλα prints Binance USDT-M από τα βασικά νομίσματα: πίεση αγοράς vs πώλησης"
    override val buyDominanceLabel: String = "ΠΙΕΣΗ ΑΓΟΡΩΝ"
    override val sellDominanceLabel: String = "ΠΙΕΣΗ ΠΩΛΗΣΕΩΝ"
    override val liveExecutionFeed: String = "LIVE ΕΚΤΕΛΕΣΕΙΣ"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Δείκτες Macro & Κύκλων"
    override val macroScreenSubtitle: String = "Επαγγελματικά μοντέλα αποτίμησης, Rainbow power law & συναίσθημα αγοράς"
    override val macroProLockedTitle: String = "PRO ιστορικά εργαλεία κύκλου"
    override val macroProLockedSubtitle: String = "Ξεκλειδώνει ζώνες Rainbow, διασταυρώσεις Pi Cycle και την εβδομαδιαία ενημέρωση γεγονότων. Όχι σήμα αγοράς ή πώλησης."
    override val macroGateTitle: String = "Ιστορικά εργαλεία κύκλου"
    override val macroGateDesc: String = "Ζώνες Rainbow, διασταυρώσεις Pi Cycle και εβδομαδιαία γεγονότα. Μόνο ιστορικό — όχι συναλλαγή."

    override val macroRainbowBadge: String = "ΙΣΤΟΡΙΚΟ"

    override val macroProLockedBadge: String = "🔒 Pro Κλειδωμένο"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Δείκτης Altcoin Season"
    override val altSeasonSubtitle: String = "75% των Top 50 νομισμάτων έναντι Bitcoin σε διάστημα 90 ημερών"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Ουδέτερη Ζώνη"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val topPerformers90d: String = "Κορυφαία 90D Νομίσματα έναντι BTC"

    // Latest News Strings
    override val latestNewsTitle: String = "Τελευταία Νέα"
    override val latestNewsSubtitle: String = "Ζωντανά επιλεγμένα νέα και ειδήσεις αγοράς"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Δείκτης Fear & Greed"
    override val fearGreedSubtitle: String = "Συναίσθημα αγοράς, ευφορία & ρολόι συσσώρευσης"
    override val fearGreedYesterday: String = "Χθες"
    override val fearGreedLastWeek: String = "Προηγούμενη Εβδομάδα"
    override val fearGreedLastMonth: String = "Προηγούμενος Μήνας"
    override val extremeFearLabel: String = "Ακραίος Φόβος"
    override val fearLabel: String = "Φόβος"
    override val neutralLabel: String = "Ουδέτερο"
    override val greedLabel: String = "Απληστία"
    override val extremeGreedLabel: String = "Ακραία Απληστία"
    override val fearGreedAccumulationTip: String = "Ζωντανή μέτρηση συναισθήματος. Αν λείπει ο αριθμός, εμφανίζεται παύλα. Όχι εντολή αγοράς ή πώλησης."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Δείκτες Pi Cycle (Κορυφή & Πυθμένας)"
    override val piCycleSubtitle: String = "Κορυφή (111SMA vs 350SMA×2) & Πυθμένας (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (ΙΣΤΟΡΙΚΗ ΔΙΑΣΤΑΥΡΩΣΗ)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BOTTOM (ΙΣΤΟΡΙΚΗ ΔΙΑΣΤΑΥΡΩΣΗ)"
    override val piCycleDma111: String = "111-Ημερών SMA"
    override val piCycleDma350x2: String = "350-Ημερών SMA × 2 (Όριο Κορυφής)"
    override val piCycleEma150: String = "150-Ημερών EMA"
    override val piCycleSma471x0745: String = "471-Ημερών SMA × 0.745 (Όριο Πυθμένα)"
    override val piCycleMa200w: String = "Πυθμένας 200-Εβδομάδων SMA"
    override val piCycleStatusSafeText: String = "Φάση Συσσώρευσης & Επέκτασης (Ασφαλής Ζώνη)"
    override val piCycleStatusAlertText: String = "🚨 ΑΝΙΧΝΕΥΤΗΚΕ ΔΙΑΣΤΑΥΡΩΣΗ PI CYCLE TOP (Κίνδυνος Κορυφής Κύκλου)"
    override val piCycleBottomStatusSafeText: String = "Πάνω από τον Ιστορικό Πυθμένα (Φάση Επέκτασης)"
    override val piCycleBottomStatusAlertText: String = "🚨 ΑΝΙΧΝΕΥΤΗΚΕ ΔΙΑΣΤΑΥΡΩΣΗ PI CYCLE BOTTOM (ιστορικός πυθμένας)"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "ΤΕΡΜΑΤΙΚΟ FUTURES"
    override val futuresOfficialFeedsSub: String = "Επίσημες ροές Binance USDT-M · Μηδενικά προσομοιωμένα δεδομένα"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "ΠΑΡΩΧΗΜΕΝΟ"
    override val futuresStateOffline: String = "OFFLINE"
    override val futuresStateUnavailable: String = "ΜΗ ΔΙΑΘΕΣΙΜΟ"
    override val futuresLastMarkIndexTitle: String = "ΤΙΜΕΣ LAST / MARK / INDEX"
    override val futuresLastTradedPrice: String = "Τελευταία Τιμή Διαπραγμάτευσης"
    override val futuresMarkPrice: String = "Τιμή Mark"
    override val futuresIndexPrice: String = "Τιμή Δείκτη (Index)"
    override val futuresBasis: String = "Βάση (Mark - Index)"
    override val futuresHigh24h: String = "Υψηλό 24ω"
    override val futuresLow24h: String = "Χαμηλό 24ω"
    override val futuresVolume24h: String = "Όγκος 24ω (USDT)"
    override val futuresBboSpreadTitle: String = "ΒΕΛΤΙΣΤΗ ΠΡΟΣΦΟΡΑ / ΖΗΤΗΣΗ (BBO) & SPREAD"
    override val futuresBestBid: String = "ΚΑΛΥΤΕΡΗ ΠΡΟΣΦΟΡΑ (BID)"
    override val futuresBestAsk: String = "ΚΑΛΥΤΕΡΗ ΖΗΤΗΣΗ (ASK)"
    override val futuresOrderbookSpread: String = "Spread Βιβλίου Εντολών:"
    override val futuresPerpFundingTitle: String = "ΕΠΙΤΟΚΙΟ ΧΡΗΜΑΤΟΔΟΤΗΣΗΣ & ΑΝΤΙΣΤΡΟΦΗ ΜΕΤΡΗΣΗ"
    override val futuresCurrentFundingRate: String = "Τρέχον Επιτόκιο Χρηματοδότησης (Funding Rate)"
    override val futuresNextFundingIn: String = "Επόμενος Διακανονισμός σε"
    override val futuresApproxAprLabel: String = "Εκτιμώμενο APR (επιτόκιο × 3 × 365):"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (ΕΝΗΜΕΡΩΣΗ ΚΑΘΕ 15S)"
    override val futuresContracts: String = "συμβόλαια"
    override val futuresLiquidationsListening: String = "Ακρόαση ζωντανής ροής ρευστοποιήσεων Binance..."
    override val futuresLongLiq: String = "LONG ΡΕΥΣΤΟΠΟΙΗΣΗ (ΠΩΛΗΣΗ)"
    override val futuresShortLiq: String = "SHORT ΡΕΥΣΤΟΠΟΙΗΣΗ (ΑΓΟΡΑ)"
    override val futuresTradesTapeTitle: String = "⚡ ΡΟΗ ΣΥΝΑΛΛΑΓΩΝ ΠΡΑΓΜΑΤΙΚΟΥ ΧΡΟΝΟΥ"
    override val futuresTradesAwaiting: String = "Αναμονή ροής συναλλαγών..."
    override val futuresPriceHeader: String = "Τιμή (USDT)"
    override val futuresQtyHeader: String = "Ποσότητα"
    override val futuresTimeHeader: String = "Ώρα"
    override val futuresLockedTitle: String = "Κλειδωμένο Ζεύγος Pro Futures"
    override val futuresLockedDesc: String = "Το %s (%s) είναι μέρος του επιπέδου Pro. Ξεκλειδώστε πλήρη ροή εντολών, arbitrage βάσης και δεδομένα perpetuals."
    override val futuresLockedButton: String = "Ξεκλείδωμα Πρόσβασης Pro"
    override val futuresSizePrefix: String = "Μέγεθος:"
    override val futuresAllPairs: String = "Όλα τα Ζεύγη"
    override val futuresSearchPair: String = "Αναζήτηση κρυπτονομίσματος..."
    override val futuresSwitchPair: String = "Αλλαγή Ζεύγους"

    // Market Intelligence & "Why is Asset Moving?" (ChatGPT 5.6 Luna Product Upgrade)
    override val intelligenceLayerTitle: String = "ΕΠΙΠΕΔΟ INTELLIGENCE ΑΓΟΡΑΣ"
    override val whyAssetMovingHeader: String = "Γιατί κινείται το %s;"
    override val interpretationLabel: String = "Ερμηνεία: "
    override val cascadeRiskLabel: String = "Κίνδυνος Καταρράκτη: "
    override val invalidationLabel: String = "Ακύρωση Σεναρίου: "
    override val expandDeepDive: String = "Πάτημα για Πλήρη Ανάλυση & Ακύρωση"
    override val collapseDeepDive: String = "Απόκρυψη Ανάλυσης"
    override val liquidationMapHeader: String = "ΣΥΓΚΕΝΤΡΩΤΙΚΑ POOLS ΡΕΥΣΤΟΠΟΙΗΣΕΩΝ"
    override val liquidationMapSub: String = "Εκτιμώμενα επίπεδα ρευστότητας & στόχοι εκκαθάρισης"
    override val shortLiquidationPools: String = "Pools Ρευστοποίησης Shorts (Πάνω από την Τιμή)"
    override val longLiquidationPools: String = "Pools Ρευστοποίησης Longs (Κάτω από την Τιμή)"
    override val currentPriceAnchor: String = "ΤΡΕΧΟΥΣΑ ΤΙΜΗ"
    override val tabClustersMap: String = "Χάρτης Ρευστότητας"
    override val tabLiveStream: String = "Ζωντανή Ροή"

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Επίπεδο Market Intelligence: Πώς Λειτουργεί"
    override val marketIntelligenceInfoButton: String = "Τι είναι αυτό;"
    override val marketIntelligenceConfidenceTitle: String = "Δείκτης Εμπιστοσύνης (π.χ. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Μετρά την ποσοτική ισχύ της τρέχουσας τοποθέτησης στα futures βάσει όγκου, ανοικτού ενδιαφέροντος (OI) και ορμής."
    override val marketIntelligenceRegimesHeader: String = "Καθεστώτα Αγοράς (Τι σημαίνουν τα σήματα)"
    override val regimeShortSqueezeTitle: String = "Πίεση Short Squeeze"
    override val regimeShortSqueezeDesc: String = "Μεγάλες θέσεις short είναι παγιδευμένες. Μια μικρή ανοδική κίνηση μπορεί να πυροδοτήσει αλυσιδωτές ρευστοποιήσεις και απότομα spikes."
    override val regimeSpotAccumulationTitle: String = "Συσσώρευση Spot"
    override val regimeSpotAccumulationDesc: String = "Πραγματική απορρόφηση αγορών spot αντί για επισφαλές leverage. Σηματοδοτεί υγιή, βιώσιμη δομή αγοράς."
    override val regimeBalancedConsolidationTitle: String = "Ισορροπημένη Συσσώρευση"
    override val regimeBalancedConsolidationDesc: String = "Η μόχλευση παραγώγων και η ζήτηση spot βρίσκονται σε ισορροπία, υποδεικνύοντας διακύμανση σε εύρος τιμών."
    override val marketIntelligenceTelemetryHeader: String = "Βασική Τηλεμετρία"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Συνολικό κεφάλαιο κλειδωμένο σε ενεργά συμβόλαια παραγώγων."
    override val telemetryFundingRateTitle: String = "Funding Rate"
    override val telemetryFundingRateDesc: String = "Περιοδική αμοιβή μεταξύ longs και shorts. Πολύ θετικά ποσοστά προειδοποιούν για υπερμοχλευμένους longs επιρρεπείς σε καθαρισμό."
    override val marketIntelligenceUnderstood: String = "Κατάλαβα"

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "AI Αναλυτής Αγοράς"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Ζωντανή Ανάλυση Κύκλων, Futures & On-Chain Ροών"
    override val aiPromptPlaceholder: String = "Ρωτήστε για κύκλο BTC, funding, support, altseason..."
    override val aiAskButton: String = "Ανάλυση"
    override val aiQuickActionCycle: String = "Κύκλος & Ρίσκο Halving"
    override val aiQuickActionFutures: String = "Funding & Ροή Μόχλευσης"
    override val aiQuickActionWhales: String = "Συσσώρευση Φαλαινών"
    override val aiQuickActionAltseason: String = "Ετοιμότητα Altseason"
    override val aiDisclaimer: String = "Τροφοδοτείται από ζωντανά μοντέλα Gemini AI & on-chain τηλεμετρία. Δεν αποτελεί οικονομική συμβουλή."
    override val aiThinking: String = "Ανάλυση ζωντανών δεδομένων & order book..."
    override val aiGreeting: String = "Είμαι εδώ. Τι θα θέλατε να δούμε;"
    override val aiClearHistory: String = "Καθαρισμός"
    override val aiLiveContextTag: String = "Ζωντανά Δεδομένα Συνδεδεμένα"
    override val aiPromptPrefixCycle: String = "Κάνε ανάλυση της τρέχουσας φάσης του κύκλου halving, του ρίσκου και των ιστορικών αναλογικών."
    override val aiPromptPrefixFutures: String = "Εξήγησε τα τρέχοντα funding rates, το open interest και τους κινδύνους ρευστοποιήσεων στα futures."
    override val aiPromptPrefixWhales: String = "Τι δείχνουν τα πρόσφατα whale alerts για θεσμική συσσώρευση ή διανομή;"
    override val aiPromptPrefixAltseason: String = "Αξιολόγησε αν οι συνθήκες αγοράς, το BTC dominance και το συναίσθημα ευνοούν ένα Altseason αυτή τη στιγμή."

    override val tabOverview: String = "Επισκόπηση"
    override val tabAnalytics: String = "Αναλυτικά"
    override val tabOnChain: String = "On-Chain"
    override val tabEvents: String = "Γεγονότα"
    override val onChainNetworkHeader: String = "Δίκτυο & On-Chain Μετρικές"
    override val eventsMilestonesHeader: String = "Ορόσημα Πρωτοκόλλου & Καταλύτες"
    override val upcomingTag: String = "ΕΠΙΚΕΙΜΕΝΟ"
    override val completedTag: String = "ΟΛΟΚΛΗΡΩΘΗΚΕ"
    override val activeTag: String = "ΕΝΕΡΓΟ"
    override val whaleConcentrationLabel: String = "Συγκέντρωση Μεγάλων Κατόχων (Whales)"
    override val exchangeNetFlowLabel: String = "Ροές Αποθεμάτων Ανταλλακτηρίων"
    override val activeAddressesEstimate: String = "Ενεργά Πορτοφόλια (24ωρο)"
    override val cycleMomentumTitle: String = "Μομέντουμ Κύκλου & Τεχνική Υγεία"
    override val circulatingSupplyTitle: String = "Κυκλοφορούσα Προσφορά"
    override val liquidationWarningText: String = "Εντοπίστηκαν πυκνά pools ρευστοποιήσεων. Αυξημένος κίνδυνος μεταβλητότητας εάν σπάσει η στήριξη."
    override val backtestBadgeText: String = "Live whale radar · live order flow · live liquidations"
    override val derivativesRiskGuardrail: String = "Αυτή η οθόνη διαβάζει την ταινία των perpetuals. Δεν είναι γραφείο συναλλαγών και δεν ορίζει μέγεθος θέσης."
}
