package com.example.util

import com.example.data.model.AppLanguage

class GreekAppStrings : AppStrings(AppLanguage.GREEK) {
    // Navigation & Core
    override val navMarkets: String = "Αγορές"
    override val navFutures: String = "Futures"
    override val navMacro: String = "Macro"
    override val navSignals: String = "Σήματα"
    override val navLearn: String = "Learn"
    override val navSettings: String = "Ρυθμίσεις"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO ΕΝΕΡΓΟ"
    override val backToFree: String = "Επιστροφή σε Free"
    override val upgradeToPro: String = "Αναβάθμιση σε Pro"
    override val proRequired: String = "Απαιτείται Pro"
    override val searchPlaceholder: String = "Αναζήτηση σε 100+ crypto..."
    override val cryptocurrenciesCount: String = "ΚΡΥΠΤΟΝΟΜΙΣΜΑΤΑ"
    override val cryptocurrencySingular: String = "ΚΡΥΠΤΟΝΟΜΙΣΜΑ"
    override val turboEngineActive: String = "Ενεργή Μηχανή Turbo"
    override val rankPrefix: String = "Κατάταξη"
    override val closeButton: String = "Κλείσιμο"
    override val institutionalTerminal: String = "Επαγγελματικό Τερματικό Κύκλων & Παραγώγων"
    override val trustBarFeed: String = "Επαγγελματική Ροή: Απευθείας Βιβλίο Εντολών"
    override val latencyMs: String = "%dms καθυστέρηση"
    override val realtimeFeed: String = "ΖΩΝΤΑΝΗ ΡΟΗ"
    override val neutralPhase: String = "Ουδέτερη Φάση"
    override val avg7d: String = "Μ.Ο. 7Η"
    override val avg30d: String = "Μ.Ο. 30Η"
    override val daysHigh: String = "ημ. υψηλό"
    override val refreshTooltip: String = "Ανανέωση ροών αγοράς"
    override val refreshingFeeds: String = "Ανανέωση δεδομένων αγοράς & futures..."
    override val feedsUpdated: String = "Τα δεδομένα αγοράς ενημερώθηκαν"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Layer 1"
    override val catLayer2: String = "Layer 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "AI & Υποδομές"
    override val catMeme: String = "Memes"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Χρησιμότητα"
    override val catFavorites: String = "Αγαπημένα"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Επισκόπηση Αγοράς"
    override val marketsHeadline: String = "100+ Χρήσιμα Real-World Assets & Whitepapers"
    override val marketsSubtitle: String = "Πού κινείται κάθε coin, προηγούμενα ιστορικά μοτίβα, μελλοντικές προβολές & whitepapers."
    override val fromAth: String = "από το ATH"
    override val tapForCycleAnalog: String = "Πατήστε για ανάλογο κύκλου, προβολές & whitepaper"
    override val heroSubtitle: String = "ΙΣΤΟΡΙΚΟ ΑΝΑΛΟΓΟ ΚΥΚΛΟΥ"
    override val currentPrice: String = "Τρέχουσα Τιμή"
    override val analogMatch: String = "Ιστορικό Ταίριασμα"
    override val cyclePhase: String = "Φάση Κύκλου"
    override val daysSinceAth: String = "Ημέρες από το ATH"
    override val tapToViewCycles: String = "Πατήστε για προβολή κύκλων & whitepaper"

    // Markets Screen Teaser Cards
    override val marketsOrderFlowTeaserTitle: String = "Order Flow & Βάθος Futures"
    override val marketsOrderFlowTeaserSummary: String = "Funding · OI · Ρευστοποιήσεις 24ω"
    override val marketsOrderFlowTeaserLocked: String = "Κλειδωμένο"
    override val marketsOrderFlowTeaserLockedDesc: String = "Ξεκλειδώστε live ροή μόχλευσης & ρευστοποιήσεων"
    override val marketsOrderFlowTeaserUnlockedDesc: String = "Live DOM Ladder & Βιβλίο Εντολών"
    override val marketsOrderFlowTeaserUpgrade: String = "Αναβάθμιση →"
    override val marketsOrderFlowTeaserOpenFutures: String = "Άνοιγμα Futures →"
    override val marketsSignalsTeaserTitle: String = "Ραντάρ Φαλαινών & Σήματα Fractals"
    override val marketsSignalsTeaserLiveTag: String = "LIVE ΡΟΗ"
    override val marketsSignalsTeaserSample: String = "BTC: $148M καθαρή συσσώρευση στο Coinbase Prime"
    override val marketsSignalsTeaserAccumulationTag: String = "ΣΥΣΣΩΡΕΥΣΗ"
    override val marketsSignalsTeaserSub: String = "Χάρτες ρευστοποιήσεων & fractals κύκλων 2016/2020"
    override val marketsSignalsTeaserOpen: String = "Άνοιγμα Καρτέλας Σημάτων →"
    override val marketsMacroTeaserNextEvent: String = "Επόμενο Γεγονός: US Jobs (NFP) Παρασκευή 15:30 UTC"
    override val marketsMacroTeaserOpen: String = "Άνοιγμα Macro →"

    // Cycle Days & Historical Analog
    override val cycleDaysTeaserTitle: String = "Ημέρες Κύκλου & Ιστορική Σύγκριση Bear Market"
    override val cycleDaysTeaserBadge: String = "ΡΟΛΟΪ ΚΥΚΛΟΥ"
    override val cycleDaysTeaserDaysPostAth: String = "Ημέρα +332 μετά το ATH · ~43ημ. έως το Παράθυρο Πυθμένα"
    override val cycleDaysTeaserCompare: String = "Σύγκριση Day 330 με 2018 ($6.3k) & 2022 ($19.5k) →"
    override val cycleDaysCardTitle: String = "Ημέρες Κύκλου & Ιστορικό Ανάλογο"
    override val cycleDaysCardSubtitle: String = "Πού βρισκόταν η τιμή ακριβώς αυτή την ημέρα στους προηγούμενους κύκλους & γιατί κράσαρε η αγορά"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "ΙΣΤΟΡΙΚΟ ΑΝΑΛΟΓΟ ΚΥΚΛΟΥ"
    override val historicalAnalogProUnlockedTitle: String = "Ανάλυση Κύκλου Pro Ξεκλείδωτη"
    override val historicalAnalogProTitle: String = "Ιστορικό Ανάλογο Κύκλου"
    override val historicalAnalogProUnlockedDesc: String = "Πλήρεις καμπύλες ιστορικού αναλόγου και στόχοι τιμών είναι ενεργοί."
    override val historicalAnalogProDesc: String = "Ξεκλειδώστε αντίστοιχες ημερομηνίες και προβολές τροχιάς για όλα τα νομίσματα."
    override val historicalAnalogManagePro: String = "Διαχείριση Pro"
    override val historicalAnalogProPrice: String = "Ξεκλείδωμα Pro (€3.99/μήνα)"
    override val movementAnalysisHeader: String = "ΑΝΑΛΥΣΗ ΚΙΝΗΣΗΣ & ΙΣΤΟΡΙΚΟ ΚΥΚΛΩΝ"
    override val whereItMovesNowLabel: String = "Πού κινείται τώρα:"
    override val whereItMovedPastLabel: String = "Πού κινήθηκε σε προηγούμενους κύκλους:"
    override val nextMoveHeader: String = "ΕΠΟΜΕΝΗ ΠΡΟΒΛΕΠΟΜΕΝΗ ΚΙΝΗΣΗ (ΙΣΤΟΡΙΚΑ ΑΝΑΛΟΓΑ)"
    override val cycleFractalLabel: String = "Ημέρα Fractal Κύκλου"
    override val historicalMatchLabel: String = "Ιστορικό Ταίριασμα Μοτίβου Κύκλου"
    override val cycleChartTapToInspect: String = "Αγγίξτε ή σύρετε στο γράφημα για έλεγχο ημερών & τιμών"
    override val cycleChartDayLabel: String = "Ημέρα"
    override val cycleChartFractalScore: String = "Ταίριασμα Fractal"
    override val cycleChartModeAll: String = "Όλοι οι Κύκλοι"
    override val cycleChartModeProjection: String = "Διάδρομος Πρόβλεψης"
    override val cycleChartMode2020: String = "2020-24"
    override val cycleChartMode2016: String = "2016-20"
    override val cycleChartMilestoneHalving: String = "Halving"
    override val cycleChartMilestoneBreakout: String = "Διάσπαση ATH"
    override val cycleChartMilestonePeak: String = "Κορυφή Κύκλου"
    override val cycleChartMilestoneFloor: String = "Πυθμένας Κύκλου"
    override val cycleChartCurrentPoint: String = "Τρέχουσα Θέση"
    override val cycleChartProjectedPath: String = "Προβλεπόμενη Πορεία Fractal"
    override val cycleChartProjectedZone: String = "Διάδρομος Εμπιστοσύνης"
    override val target1w: String = "1 Εβδομάδα"
    override val target2w: String = "2 Εβδομάδες"
    override val target4w: String = "4 Εβδομάδες"
    override val strategyGuideTitle: String = "📖 Οδηγός Στρατηγικής: Πότε Αγοράζουμε & Πότε Πουλάμε"
    override val buyMomentTitle: String = "🟢 Πότε είναι η Καλύτερη Στιγμή για ΑΓΟΡΑ (Συσσώρευση)"
    override val buyMomentRules: String = "1. Όταν η τιμή Bitcoin αγγίζει ή πλησιάζει τον Πυθμένα 200W MA (<15% απόσταση). Αυτό σηματοδοτεί ιστορικούς πυθμένες κύκλου.\n2. Όταν ο 111 DMA είναι πολύ κάτω (>40%) από τον 350 DMA x 2. Ελάχιστος καθοδικός κίνδυνος με μέγιστη απόδοση (DCA In)."
    override val sellMomentTitle: String = "🔴 Πότε είναι η Καλύτερη Στιγμή για ΠΩΛΗΣΗ (Κορυφή Κύκλου)"
    override val sellMomentRules: String = "1. Όταν ο 111 DMA διασταυρώνεται πάνω από τον 350 DMA x 2. Αυτό σηματοδοτεί υψηλή πιθανότητα κορυφής κύκλου.\n2. Όταν το Rainbow Chart εισέρχεται στις κόκκινες ζώνες 'Maximum Bubble'. Τα ιστορικά δεδομένα δείχνουν ότι ακολουθούν μαζικές διορθώσεις (90%+ για τα alts)."
    override val rainbowFeatureLabel: String = "🌈 Bitcoin Rainbow Chart (Δυναμικό Μοντέλο Power Law)"
    override val altSeasonFeatureLabel: String = "⚡ Δείκτης Altcoin Season (0-100) & Top 50 Outperformers"
    override val piCycleFeatureLabel: String = "🎯 Δείκτης Pi Cycle Top & Πυθμένας 200W MA (Κανόνες Αγοράς/Πώλησης)"
    override val fearGreedFeatureLabel: String = "😱 Fear & Greed Πολυ-Χρονική Ανάλυση Συναισθήματος"
    override val proAnalyticsTitle: String = "Ανάλυση Κύκλου Pro"
    override val proAnalyticsDesc: String = "Ξεκλειδώστε πλήρεις συγκρίσεις καμπυλών 2020 & 2016 και προβλέψεις για το"
    override val proAnalyticsButton: String = "Ξεκλείδωμα Pro (€3.99/μήνα)"
    override val projectedPeakLabel: String = "Σενάριο Πολλαπλασιαστή 2021 (Μόνο ιστορική αναφορά)"
    override val projectedBottomLabel: String = "Κατώτερη Ζώνη Κύκλου (Ιστορικά)"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "ΣΤΑΤΙΣΤΙΚΑ ΑΓΟΡΑΣ & ΠΡΟΣΦΟΡΑ TOKEN"
    override val circulatingSupplyLabel: String = "Κυκλοφορούσα Προσφορά:"
    override val circulatingShort: String = "Κυκλοφορία"
    override val infiniteDeflationary: String = "Άπειρη (Αποπληθωριστική)"
    override val marketCapMetric: String = "ΚΕΦΑΛΑΙΟΠΟΙΗΣΗ"
    override val volume24hMetric: String = "ΟΓΚΟΣ 24Ω"
    override val tradingVolumeSub: String = "Όγκος συναλλαγών"
    override val fdvMetric: String = "FDV (ΠΛΗΡΗΣ ΑΠΟΤΙΜΗΣΗ)"
    override val fdvSub: String = "Πλήρως αραιωμένη αξία"
    override val athMetric: String = "ΙΣΤΟΡΙΚΟ ΥΨΗΛΟ (ATH)"
    override val atlMetric: String = "ΙΣΤΟΡΙΚΟ ΧΑΜΗΛΟ (ATL)"
    override val drawdownAthMetric: String = "ΠΤΩΣΗ ΑΠΟ ATH"
    override val fromPeakSub: String = "Από την κορυφή"
    override val allTimeLowMetric: String = "Ιστορικό χαμηλό"
    override val allTimeHighMetric: String = "Ιστορικό υψηλό"
    override val startMetric: String = "Έναρξη"
    override val liveYearsMetric: String = "6443ημ · 17.64 έτη ενεργό"
    override val daysSinceHighMetric: String = "Ημέρες από το υψηλό"
    override val dropFromHighMetric: String = "-36.0% πτώση από το υψηλό"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & ΤΕΧΝΟΛΟΓΙΚΟ ΠΛΑΝΟ"
    override val founderLabel: String = "ΔΗΜΙΟΥΡΓΟΣ / ΙΔΡΥΤΗΣ"
    override val genesisDateLabel: String = "ΗΜΕΡΟΜΗΝΙΑ ΓΕΝΕΣΗΣ"
    override val whatCoinDoesLabel: String = "Τι κάνει το crypto (Core Whitepaper Blueprint)"
    override val consensusLabel: String = "Μηχανισμός Συναίνεσης & Αρχιτεκτονική"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Έκδοση"
    override val useCasesLabel: String = "Κύριες Χρήσεις Οικοσυστήματος"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Ιστορικά πτωτική αντίστοιχη εβδομάδα (Δείγμα: n=2 κύκλοι)"
    override val weekOfFallSub: String = "εβδομάδα 46 · τυπικά 16 εβδ."
    override val cycleAnalysisHeader: String = "Ανάλυση κύκλου"
    override val fromHighToLowTitle: String = "ΑΠΟ ΤΟ ΥΨΗΛΟ ΣΕ ΕΝΑ ΠΙΘΑΝΟ ΧΑΜΗΛΟ"
    override val daysAfterAthLabel: String = "ημέρες μετά το ιστορικό υψηλό"
    override val daysToBottomLabel: String = "ημέρες μέχρι πιθανό χαμηλό"
    override val highMarker: String = "Υψηλό"
    override val typical383dMarker: String = "τυπικά 383ημ"
    override val lowMarker: String = "Χαμηλό"
    override val fromHighToLowNarrative: String = "Είμαστε 319 ημέρες μετά το ιστορικό υψηλό. Ιστορικά, από το υψηλό μέχρι τον πάτο χρειάστηκαν περίπου 383 ημέρες. Απομένουν περίπου 64 ημέρες για ένα πιθανό χαμηλό."
    override val fromHighToLowDetails: String = "06 Οκτ 2025 · \$124,752.53 · -36.0% από το υψηλό"
    override val fromHighToLowDisclaimer: String = "Αυτό έκαναν οι προηγούμενοι κύκλοι. Δεν είναι υπόσχεση — είναι απλώς ένα ρολόι."
    override val thisCycleVsLastTitle: String = "ΑΥΤΟΣ Ο ΚΥΚΛΟΣ VS ΟΙ ΠΡΟΗΓΟΥΜΕΝΟΙ"
    override val daysAfterHighTitle: String = "Ημέρες μετά το υψηλό"
    override val daysAfterHighSub: String = "Είμαστε 319 ημέρες μετά το υψηλό. Οι παλαιότερες πτώσεις προς τον πάτο διήρκεσαν περίπου 383 ημέρες."
    override val nowLabel: String = "Τώρα"
    override val daysOfRiseTitle: String = "Ημέρες ανόδου, ιστορικά"
    override val daysOfRiseSub: String = "Οι παλαιότερες άνοδοι από τον πάτο στο επόμενο υψηλό διήρκεσαν περίπου 1059 ημέρες."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "ημέρες μέχρι το επόμενο halving"
    override val halvingHoursLabel: String = "ώρες απομένουν"
    override val whatCameNextTitle: String = "Τι συνέβη σε αντίστοιχες ημέρες προηγούμενων κύκλων"
    override val timeframe1wk: String = "σε 1 εβδ."
    override val timeframe2wk: String = "σε 2 εβδ."
    override val timeframe4wk: String = "σε 4 εβδ."
    override val winRate71: String = "10 από 14 φορές ανέβηκε (ιστορική αναφορά)"
    override val winRate79: String = "12 από 15 φορές ανέβηκε (ιστορική αναφορά)"
    override val winRate86: String = "13 από 15 φορές ανέβηκε (ιστορική αναφορά)"
    override val whyWeSayThisTitle: String = "Ιστορικό Πλαίσιο & Περιορισμοί Κύκλου"
    override val whyPoint1: String = "Αυτή η εβδομάδα του κύκλου μοιάζει με τις 28 Ιουν 2018 — ίδια φάση, παρόμοια κίνηση."
    override val whyPoint2: String = "Εξετάσαμε 14 παρόμοιες εβδομάδες στο παρελθόν. Τις επόμενες 4 εβδομάδες η τιμή ανέβηκε 12 στις 14 φορές (τυπικά +29.5%)."
    override val whyPoint3: String = "Βρισκόμαστε στην εβδομάδα 46 της πτώσης. Στο παρελθόν μια τέτοια φάση διήρκεσε περίπου 16 εβδομάδες."
    override val whyPoint4: String = "Τόσο η θέση του κύκλου όσο και οι ιστορικές εβδομάδες δείχνουν την πράσινη ζώνη."

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Επιλογή Asset"
    override val signalsAllCoins: String = "Όλα τα 100+ Crypto"
    override val timeframe1D: String = "1Η"
    override val timeframe1W: String = "1Ε"
    override val timeframe1M: String = "1Μ"
    override val timeframe1Y: String = "1ΕΤ"
    override val timeframeCycle: String = "Κύκλος Macro"
    override val signalBullish: String = "ΑΝΟΔΙΚΗ ΕΚΤΟΝΩΣΗ (BULLISH)"
    override val signalBearish: String = "ΚΑΘΟΔΙΚΗ ΔΙΟΡΘΩΣΗ (BEARISH)"
    override val signalAccumulation: String = "ΔΙΑΣΠΑΣΗ ΣΥΣΣΩΡΕΥΣΗΣ"
    override val signalConfidence: String = "Συχνότητα ιστορικής αναφοράς"
    override val signalLiveFeed: String = "Live Ροή CoinGecko • Ticks 1s"
    override val analogComparisonHeader: String = "ΕΠΙΚΑΛΥΨΗ ΙΣΤΟΡΙΚΗΣ ΚΙΝΗΣΗΣ ΤΙΜΩΝ"
    override val analogExplanation: String = "Ευθυγράμμιση τιμών με αντίστοιχες ημερομηνίες προηγούμενων κύκλων. Δεν αποτελεί πρόβλεψη."
    override val highAccuracyNotice: String = "Ιστορικό αρχείο αναφοράς backtest"

    // Settings Screen
    override val settingsHeader: String = "Ρυθμίσεις"
    override val languageTitle: String = "Γλώσσα"
    override val languageDesc: String = "Επιλέξτε την προτιμώμενη γλώσσα σας"
    override val appearanceTitle: String = "Εμφάνιση"
    override val themeGalaxyDark: String = "Galaxy Dark (Προεπιλογή)"
    override val themeGalaxyDarkSub: String = "Βαθύ μπλε φόντο OLED με κυανές λεπτομέρειες"
    override val themePureBlack: String = "Απόλυτο Μαύρο"
    override val themePureBlackSub: String = "Λειτουργία καθαρού μαύρου OLED για μέγιστη εξοικονόμηση μπαταρίας"
    override val themeCleanWhite: String = "Καθαρό Λευκό"
    override val themeCleanWhiteSub: String = "Φωτεινό θέμα για συνθήκες έντονου φωτισμού"
    override val optionsTitle: String = "Επιλογές"
    override val soundEffectsTitle: String = "Ηχητικά Εφέ Crypto (SFX)"
    override val soundEffectsSub: String = "Απτική ανάδραση κατά την πλοήγηση & ειδοποιήσεις"
    override val soundTestTitle: String = "Δοκιμή Ήχων"
    override val soundTestLaunch: String = "Άνοδος Μείζονος Κλίμακας 🎵"
    override val soundTestClick: String = "Τεχνολογικό Πάτημα"
    override val soundTestToggle: String = "Ήχος Εναλλαγής"
    override val soundTestChime: String = "Ήχος Επιβράβευσης Coin"
    override val hideMemecoinsTitle: String = "Απόκρυψη Memecoins"
    override val hideMemecoinsSub: String = "Εμφάνιση μόνο θεμελιωδών projects υψηλής κεφαλαιοποίησης"
    override val logChartsTitle: String = "Λογαριθμικά Διαγράμματα"
    override val logChartsSub: String = "Προβολή τιμών σε λογαριθμική κλίμακα για εξομάλυνση ποσοστιαίων μεταβολών"
    override val proMembershipTitle: String = "Συνδρομή Pro"
    override val proMembershipPrice: String = "€3.99 / μήνα · €34.99 / έτος"
    override val proBenefit1: String = "Institutional Masterclass: Κεφάλαια 18-22 (Macro, On-Chain & Στρατηγικές)"
    override val proBenefit2: String = "Πλήρη Σήματα Futures & Ραντάρ Μόχλευσης Φαλαινών"
    override val proBenefit3: String = "Πλήρη Μοντέλα Κύκλων Pi Cycle Top/Bottom & Forward Audit Trail"
    override val proBenefit4: String = "Live Crypto News Feed ανά νόμισμα & Άμεση Ενημέρωση Αγοράς"
    override val proBenefit5: String = "Απεριόριστες Push Ειδοποιήσεις & Όλα τα Ιστορικά Ανάλογα"
    override val currencyDisplayTitle: String = "Νόμισμα Προβολής"
    override val howWeReadItTitle: String = "Πώς το διαβάζουμε — με απλά λόγια"
    override val plainItem1Title: String = "1. Η ιστορία επαναλαμβάνεται σε κύκλους"
    override val plainItem1Desc: String = "Τα crypto ακολουθούν 4ετείς κύκλους halving. Ευθυγραμμίζουμε τη σημερινή πορεία με το 2020 και το 2016."
    override val plainItem2Title: String = "2. Ιστορικά Ανάλογα"
    override val plainItem2Desc: String = "Η πορτοκαλί καμπύλη δείχνει το 2020· η κυανή το 2016. Η λευκή γραμμή είναι η τρέχουσα τροχιά σας."
    override val plainItem3Title: String = "3. Ιστορικές Ζώνες Κύκλου"
    override val plainItem3Desc: String = "Μέσω λογαριθμικής παλινδρόμησης υπολογίζουμε ιστορικές ζώνες για εκπαιδευτική μελέτη. Όλα τα εργαλεία είναι εκπαιδευτικά και δεν αποτελούν οικονομική συμβουλή."
    override val plainItem4Title: String = "4. Θεμελιώδη Whitepapers"
    override val plainItem4Desc: String = "Κάθε προφίλ περιλαμβάνει μοντέλο συναίνεσης, tokenomics, ιδρυτές και πραγματικές χρήσεις."
    override val plainItem5Title: String = "5. Προειδοποίηση Κινδύνου"
    override val plainItem5Desc: String = "Οι παρελθοντικές αποδόσεις δεν εγγυώνται μελλοντικά αποτελέσματα. Επενδύετε με σύνεση."
    override val privacyPolicyTitle: String = "Όροι Χρήσης & Απόρρητο"
    override val privacyPolicyView: String = "Δείτε την πολιτική συλλογής & αποθήκευσης δεδομένων"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Ξεκλειδώστε ανάλογα κύκλων, ειδοποιήσεις και πλήρη ανάλυση νομισμάτων. Ακύρωση ανά πάσα στιγμή."
    override val proModalFeature1: String = "Institutional Masterclass: Κεφάλαια 18-22 (Macro, On-Chain & Στρατηγικές)"
    override val proModalFeature2: String = "Πλήρη Σήματα Futures & Ραντάρ Μόχλευσης Φαλαινών"
    override val proModalFeature3: String = "Πλήρη Μοντέλα Κύκλων Pi Cycle Top/Bottom & Forward Audit Trail"
    override val proModalFeature4: String = "Live Crypto News Feed ανά νόμισμα & Άμεση Ενημέρωση Αγοράς"
    override val proModalFeature5: String = "Απεριόριστες Push Ειδοποιήσεις & Όλα τα Ιστορικά Ανάλογα"
    override val proModalFeature6: String = "Απεριόριστες Push Ειδοποιήσεις & Όλα τα Ιστορικά Ανάλογα"
    override val planMonthlyTitle: String = "Μηνιαίο"
    override val planMonthlyPrice: String = "€3.99"
    override val planMonthlyPeriod: String = "/ μήνα"
    override val planMonthlyBadge: String = "7 Ημέρες Δωρεάν Δοκιμή"
    override val planAnnualTitle: String = "Ετήσιο"
    override val planAnnualPrice: String = "€34.99"
    override val planAnnualPeriod: String = "/ έτος"
    override val planAnnualBadge: String = "Προσφορά Launch 40% • ~€2.91/μήνα"
    override val subscribeProBtn: String = "Έναρξη Δωρεάν Δοκιμής 7 Ημερών"
    override val startFreeTrialBtn: String = "Έναρξη Δωρεάν Δοκιμής 7 Ημερών"
    override val startFreeTrialSub: String = "7 ημέρες δωρεάν, μετά €3.99 / μήνα. Ακύρωση όποτε θέλετε."
    override val continueYearlyBtn: String = "Συνέχεια με Ετήσιο (€34.99/έτος)"
    override val continueYearlySub: String = "Άμεση Πρόσβαση Pro • €34.99 χρεώνεται ετησίως (~€2.91/μήνα)"
    override val restorePurchases: String = "Επαναφορά Αγορών"
    override val restoringPurchases: String = "Έλεγχος αγορών από το Google Play..."
    override val cancelAnytime: String = "Ακύρωση ανά πάσα στιγμή στο Google Play"
    override val playTermsDisclosure: String = "Η πληρωμή χρεώνεται στον λογαριασμό Google Play κατά την επιβεβαίωση. Η συνδρομή ανανεώνεται αυτόματα εκτός αν ακυρωθεί τουλάχιστον 24 ώρες πριν από το τέλος της περιόδου."
    override val financialDisclaimerTitle: String = "Οικονομική & Κανονιστική Αποποίηση Ευθύνης"
    override val financialDisclaimerText: String = "Το CryptoCycles παρέχεται αποκλειστικά για εκπαιδευτικούς και ιστορικούς σκοπούς. Όλα τα εργαλεία κύκλων, προβολές Rainbow και ανάλογα halving είναι εκπαιδευτικά και ΔΕΝ αποτελούν οικονομική ή επενδυτική συμβουλή. Δεν υποσχόμαστε ούτε εγγυόμαστε κορυφές κύκλων ή στόχους τιμών. Κάντε πάντα τη δική σας έρευνα (DYOR)."
    override val privacySheetTitle: String = "Απόρρητο CryptoCycles"
    override val privacyLastUpdated: String = "Τελευταία ενημέρωση: 2026"
    override val privSection1Title: String = "1. Συλλογή Δεδομένων & Απόρρητο"
    override val privSection1Body: String = "Το CryptoCycles δεν συλλέγει, δεν πωλεί και δεν εκμεταλλεύεται προσωπικά δεδομένα ταυτοποίησης. Τα δεδομένα αγοράς, τα ιστορικά αναλογικά και η τηλεμετρία αντλούνται ανώνυμα από δημόσιες πηγές blockchain και ανταλλακτηρίων. Όλα τα εργαλεία παρέχονται αποκλειστικά για εκπαιδευτική και ερευνητική χρήση και δεν αποτελούν επενδυτική συμβουλή."
    override val privSection2Title: String = "2. Ανηλίκοι"
    override val privSection2Body: String = "Το CryptoCycles δεν απευθύνεται σε παιδιά κάτω των 13 ετών."
    override val privSection3Title: String = "3. Επικοινωνία"
    override val privSection3Body: String = "Για απορίες απορρήτου, χρησιμοποιήστε το email επικοινωνίας στο Google Play."
    override val privSection4Title: String = "4. Τοπική Αποθήκευση"
    override val privSection4Body: String = "Το CryptoCycles δεν δημιουργεί λογαριασμούς ούτε πωλεί προσωπικά δεδομένα. Όλες οι προτιμήσεις παραμένουν στη συσκευή σας."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO Σήματα Macro Κύκλων & Κύματα Halving"
    override val signalsProLockedSubtitle: String = "Ξεκλειδώστε θεσμικά σχέδια μακροοικονομικών κύκλων, ιστορικά ανάλογα halving 2020 & 2016, και ειδοποιήσεις ραντάρ φαλαινών σε πραγματικό χρόνο."
    override val signalsProLockedFeature1: String = "Ιστορικά Ανάλογα Κύκλων Halving (επικαλύψεις κυμάτων 2020 & 2016)"
    override val signalsProLockedFeature2: String = "Αλγόριθμοι Grok ZigZag για σημεία καμπής κορυφής & διόρθωσης"
    override val signalsProLockedFeature3: String = "Παράθυρα στόχων κορυφής & συσσώρευσης πυθμένα"
    override val signalsProLockedFeature4: String = "Ειδοποιήσεις Push Ραντάρ Φαλαινών για εντολές άνω των $10M+"

    // Zone Playbook Strings
    override val zonePlaybookTitle: String = "ΠΛΑΝΟ ΖΩΝΩΝ ΚΥΚΛΟΥ"
    override val zonePlaybookSub: String = "Εκπαιδευτικός οδηγός διαχείρισης ρίσκου βάσει μακροοικονομικών ζωνών"
    override val zoneGreenAction: String = "Πράσινη Ζώνη • Κλιμακωτή Είσοδος (Συσσώρευση)"
    override val zoneGreenDesc: String = "Ιστορικά ευνοϊκή αναλογία ρίσκου/απόδοσης. Συστηματικό dollar-cost averaging σε θεμελιώδη assets."
    override val zoneYellowAction: String = "Κίτρινη Ζώνη • Διακράτηση & Επανεξισορρόπηση"
    override val zoneYellowDesc: String = "Ζώνη αποτίμησης μέσου κύκλου. Διατήρηση υφιστάμενων θέσεων, αποφυγή συναισθηματικών κινήσεων."
    override val zoneRedAction: String = "Κόκκινη Ζώνη • Κλιμακωτή Έξοδος (Μείωση Ρίσκου)"
    override val zoneRedDesc: String = "Υπεραγορασμένη ζώνη αποτίμησης. Ιστορικά συνετή η μερική κατοχύρωση κερδών και προστασία κεφαλαίου."
    override val zonePlaybookDisclaimer: String = "Μόνο για εκπαιδευτικούς σκοπούς. Δεν αποτελεί οικονομική συμβουλή."

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "ΕΒΔΟΜΑΔΙΑΙΑ ΕΝΗΜΕΡΩΣΗ MACRO"
    override val weeklyBriefingSub: String = "Εβδομαδιαία θεσμική σύνθεση κύκλου & στάση κινδύνου"
    override val weeklyBriefingCurrentZone: String = "Τρέχουσα Ζώνη Macro"
    override val weeklyBriefingActionTitle: String = "Προτεινόμενη Στάση"
    override val weeklyBriefingActionAccumulate: String = "ΣΥΣΣΩΡΕΥΣΗ"
    override val weeklyBriefingActionHold: String = "ΔΙΑΚΡΑΤΗΣΗ"
    override val weeklyBriefingActionReduce: String = "ΜΕΙΩΣΗ"
    override val weeklyBriefingReasonTitle: String = "Σύνθεση 3 Σημείων"
    override val weeklyBriefingLine1: String = "1. Οι δείκτες αποτίμησης macro παραμένουν στον χαμηλότερο διάδρομο συσσώρευσης."
    override val weeklyBriefingLine2: String = "2. Ο πυθμένας 200W SMA και η δυναμική προσφοράς halving συνεχίζουν να παρέχουν δομική στήριξη."
    override val weeklyBriefingLine3: String = "3. Η συσσώρευση σε πορτοφόλια on-chain δείχνει σταθερή απορρόφηση κατά τις φάσεις συσσώρευσης."
    override val weeklyBriefingProUnlockText: String = "Ξεκλειδώστε τη θεσμική Εβδομαδιαία Ενημέρωση, το πλάνο ζωνών και τα ανάλογα macro με Pro."

    // Historical Analog Card Strings
    override val historicalAnalogCardTitle: String = "ΙΣΤΟΡΙΚΟ ΑΝΑΛΟΓΟ ΚΥΚΛΟΥ"
    override val historicalAnalogPhaseText: String = "Βρισκόμαστε στην ίδια φάση κύκλου με τις %s."
    override val historicalAnalogFollowThrough: String = "Μετά από εκείνο το σημείο, η τυπική κίνηση ήταν: 30ημ: %s • 90ημ: %s • 180ημ: %s"
    override val historicalAnalogNotFinancialAdvice: String = "Εκπαιδευτικό μοντέλο βασισμένο στο ιστορικό fractals 2016 & 2020. Όχι οικονομική συμβουλή."
    override val historicalAnalogProUnlockText: String = "Ξεκλειδώστε τις καμπύλες ιστορικού αναλόγου και τις τροχιές 30/90/180 ημερών."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Ειδοποιήσεις Push Κύκλων & Δεικτών"
    override val alertSettingsSub: String = "Άμεσες ειδοποιήσεις στη συσκευή για κρίσιμα όρια του κύκλου της αγοράς"
    override val alertZoneChangeTitle: String = "Ειδοποίηση Αλλαγής Ζώνης"
    override val alertZoneChangeDesc: String = "Ενημέρωση όταν το Bitcoin μεταβαίνει μεταξύ Πράσινης, Κίτρινης και Κόκκινης ζώνης"
    override val alertPiCycleTitle: String = "Απόκλιση & Διασταύρωση Pi Cycle Top"
    override val alertPiCycleDesc: String = "Ενημέρωση όταν η απόσταση 111DMA και 350DMA x 2 στενεύει ή διασταυρώνεται"
    override val alertRainbowTitle: String = "Μετάβαση Ζώνης Rainbow"
    override val alertRainbowDesc: String = "Ενημέρωση όταν το Bitcoin μεταβαίνει μεταξύ των ζωνών αποτίμησης Rainbow"
    override val alert200WTitle: String = "Απόσταση από 200W SMA"
    override val alert200WDesc: String = "Ενημέρωση όταν η τιμή πλησιάζει ή αποκλίνει σημαντικά από τον 200W SMA"
    override val alertFreeLimitNotice: String = "Η δωρεάν έκδοση περιλαμβάνει έως 2 ενεργές ειδοποιήσεις. Αναβαθμίστε σε Pro για απεριόριστες."
    override val alertProUnlockNotice: String = "PRO λειτουργία: Απεριόριστες ειδοποιήσεις push για κύκλους, Pi Cycle και Rainbow."

    // Widget Strings
    override val widgetSettingsTitle: String = "Widget Αρχικής Οθόνης"
    override val widgetSettingsDesc: String = "Προβολή τρέχουσας ζώνης κύκλου, τιμής BTC και ημερών από το ATH στην αρχική οθόνη σας"
    override val widgetZoneLabel: String = "Ζώνη"
    override val widgetBtcPriceLabel: String = "Τιμή BTC"
    override val widgetDaysSinceAthLabel: String = "Ημέρες από ATH"

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "ΡΑΝΤΑΡ ΦΑΛΑΙΝΩΝ & ΜΕΓΑΛΕΣ ΚΙΝΗΣΕΙΣ ON-CHAIN (PRO)"
    override val whaleRadarSub: String = "Τηλεμετρία πραγματικού χρόνου για θεσμικές ροές πορτοφολιών και ανταλλακτηρίων (άνω των $10M+)"
    override val whaleNotificationsTitle: String = "Ειδοποιήσεις Push Ραντάρ Φαλαινών"
    override val whaleNotificationsDesc: String = "Λάβετε άμεσες ειδοποιήσεις push όταν πραγματοποιούνται τεράστιες αγορές ή καταθέσεις σε ανταλλακτήρια."
    override val whaleNotificationsProLockedDesc: String = "Αποκλειστική λειτουργία PRO. Ειδοποιήσεις push σε πραγματικό χρόνο για μεταφορές $10M+."
    override val whaleThresholdTitle: String = "Ελάχιστο Μέγεθος Ειδοποίησης Φαλαινών"
    override val whaleTestAlertBtn: String = "Δοκιμή Ειδοποίησης Φαλαινών"
    override val whaleTestAlertSuccess: String = "Η δοκιμαστική ειδοποίηση στάλθηκε στη συσκευή!"
    override val whaleFilterAll: String = "Όλες οι Φάλαινες"
    override val whaleFilterInflow: String = "🚨 Εισροές / Dumps"
    override val whaleFilterOutflow: String = "🟢 Συσσώρευση"
    override val whaleFilterBuy: String = "🚀 Mega Αγορές"
    override val whaleCollapse: String = "Σύμπτυξη"
    override val whaleViewAll: String = "Προβολή όλων (%d)"
    override val timeJustNow: String = "Μόλις τώρα"
    override val timeMinsAgo: String = "πριν %dλ"
    override val timeHoursAgo: String = "πριν %dω"
    override val liveOrderFlowTitle: String = "24/7 LIVE ΡΟΗ ΕΝΤΟΛΩΝ (BINANCE)"
    override val liveOrderFlowSub: String = "Ροή tick σε πραγματικό χρόνο: ταλαντωτής πίεσης αγοράς vs πώλησης"
    override val buyDominanceLabel: String = "ΠΙΕΣΗ ΑΓΟΡΩΝ"
    override val sellDominanceLabel: String = "ΠΙΕΣΗ ΠΩΛΗΣΕΩΝ"
    override val netVolumeDelta: String = "ΚΑΘΑΡΗ ΡΟΗ 24Ω"
    override val liveExecutionFeed: String = "LIVE ΕΚΤΕΛΕΣΕΙΣ"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Δείκτες Macro & Κύκλων"
    override val macroScreenSubtitle: String = "Επαγγελματικά μοντέλα αποτίμησης, Rainbow power law & συναίσθημα αγοράς"
    override val macroUpdated4m: String = "Ενημέρωση πριν 4λ"
    override val macroProLockedTitle: String = "PRO Σουίτα Macro Κύκλων & Rainbow Chart"
    override val macroProLockedSubtitle: String = "Ξεκλειδώστε δυναμική αποτίμηση Bitcoin Rainbow, δείκτη Altcoin Season 90 ημερών, ανάλυση Fear & Greed, και δείκτες Pi Cycle Top."

    // Macro Filters
    override val macroFilterAll: String = "Όλοι οι Δείκτες"
    override val macroFilterEconomicCalendar: String = "📅 Ημερολόγιο NFP & CPI"
    override val macroFilterRiskBackdrop: String = "🌐 DXY, 10Y & FedWatch"
    override val macroFilterRainbow: String = "🌈 Rainbow Chart"
    override val macroFilterAltSeason: String = "⚡ Alt Season"
    override val macroFilterFearGreed: String = "😱 Fear & Greed"
    override val macroFilterPiCycle: String = "🎯 Pi Cycle & 200W"

    // Macro Economic Calendar & Risk Cards
    override val macroEconomicCalendarCardTitle: String = "📅 Οικονομικά Γεγονότα & NFP / CPI"
    override val macroEconomicCalendarCardSub: String = "Επόμενο: US Jobs (NFP) Παρασκευή 15:30 UTC"
    override val macroNfpFridayBadge: String = "NFP ΠΑΡΑΣΚΕΥΗ"
    override val macroRiskBackdropCardTitle: String = "🌐 DXY, 10Y Αποδόσεις & FedWatch"
    override val macroRiskBackdropCardSub: String = "Παγκόσμια Ρευστότητα USD & Κρατικές Αποδόσεις"
    override val macroRiskBackdropBadge: String = "MACRO ΠΛΑΙΣΙΟ"
    override val macroRainbowCardTitle: String = "🌈 Μοντέλο Τιμής Bitcoin Rainbow"
    override val macroRainbowCardSub: String = "Λογαριθμικές Ζώνες Αποτίμησης"
    override val macroRainbowBadge: String = "HOLD / DCA"
    override val macroAltSeasonCardTitle: String = "⚡ Δείκτης Altcoin Season"
    override val macroAltSeasonCardSub: String = "42/100 · Ουδέτερη Ζώνη (Bitcoin Season)"
    override val macroFearGreedCardTitle: String = "😱 Δείκτης Fear & Greed"
    override val macroFearGreedCardSub: String = "68/100 · Συναίσθημα Απληστίας"

    override val macroUsJobsTitle: String = "US Jobs: Non-Farm Payrolls (NFP)"
    override val macroUsJobsTime: String = "Παρασκευή 15:30 UTC"
    override val macroCpiTitle: String = "US Consumer Price Index (CPI)"
    override val macroCpiTime: String = "Επόμενη Τετάρτη 13:30 UTC"
    override val macroForecastLabel: String = "Πρόβλεψη"
    override val macroPreviousLabel: String = "Προηγούμενο"
    override val macroVolatilityLabel: String = "Μεταβλητότητα"
    override val macroConsensusYoyLabel: String = "Συναίνεση YoY"
    override val macroPriorYoyLabel: String = "Προηγούμενο YoY"
    override val macroProOnly: String = "🔒 Μόνο Pro"
    override val macroProHigh: String = "🔒 Υψηλή"
    override val macroProLockedBadge: String = "🔒 Pro Κλειδωμένο"

    override val macroFedWatchTitle: String = "CME FedWatch: Πιθανότητα Μείωσης Επιτοκίων"
    override val macroDxyTitle: String = "DXY: Δείκτης Δολαρίου ΗΠΑ"
    override val macroUs10yTitle: String = "US 10Y: Απόδοση 10ετούς Ομολόγου ΗΠΑ"
    override val macroBrentTitle: String = "Πετρέλαιο Brent Crude"

    // Rainbow Chart Strings
    override val rainbowHeaderTitle: String = "Bitcoin Rainbow Chart"
    override val rainbowHeaderSubtitle: String = "Δυναμικό Διάγραμμα Rainbow"
    override val rainbowFormulaTag: String = "Δυναμικό Power Law (94.3% R² Fit)"
    override val rainbowDescription: String = "Δυναμικό μοντέλο λογαριθμικής παλινδρόμησης Power Law που προσαρμόζει ολόκληρη την ιστορία τιμών του Bitcoin από το 2012."
    override val rainbowCurrentBandLabel: String = "Τρέχουσα Ζώνη Αποτίμησης"
    override val rainbowCyclePeakTarget: String = "Στόχος Κορυφής Κύκλου"
    override val rainbowFireSaleTarget: String = "Πυθμένας Fire Sale"
    override val rainbowFilterAll: String = "Όλες οι Ζώνες"
    override val rainbowInspectHelp: String = "Αγγίξτε και σύρετε στο διάγραμμα για να επιθεωρήσετε ιστορικές τιμές & ζώνες"
    override val halvingVerticalLabel: String = "Halving"
    override val halving2032Est: String = "Halving 2032 (Εκτίμηση)"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Δείκτης Altcoin Season"
    override val altSeasonSubtitle: String = "75% των Top 50 νομισμάτων έναντι Bitcoin σε διάστημα 90 ημερών"
    override val altSeasonScoreLabel: String = "Σκορ Altcoin Season"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Ουδέτερη Ζώνη"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val altSeasonOutperformedCount: String = "%d από %d νομίσματα ξεπέρασαν το BTC"
    override val topPerformers90d: String = "Κορυφαία 90D Νομίσματα έναντι BTC"

    // Latest News Strings
    override val latestNewsTitle: String = "Τελευταία Νέα"
    override val latestNewsSubtitle: String = "Ζωντανά επιλεγμένα νέα και ειδήσεις αγοράς"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Δείκτης Fear & Greed"
    override val fearGreedSubtitle: String = "Συναίσθημα αγοράς, ευφορία & ρολόι συσσώρευσης"
    override val fearGreedNow: String = "Τώρα"
    override val fearGreedYesterday: String = "Χθες"
    override val fearGreedLastWeek: String = "Προηγούμενη Εβδομάδα"
    override val fearGreedLastMonth: String = "Προηγούμενος Μήνας"
    override val extremeFearLabel: String = "Ακραίος Φόβος"
    override val fearLabel: String = "Φόβος"
    override val neutralLabel: String = "Ουδέτερο"
    override val greedLabel: String = "Απληστία"
    override val extremeGreedLabel: String = "Ακραία Απληστία"
    override val fearGreedAccumulationTip: String = "Ιστορικά, τιμές κάτω από 25 (Ακραίος Φόβος) αποτελούν βέλτιστα παράθυρα μακροοικονομικής συσσώρευσης."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Δείκτες Pi Cycle (Κορυφή & Πυθμένας)"
    override val piCycleSubtitle: String = "Κορυφή (111SMA vs 350SMA×2) & Πυθμένας (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (ΚΟΡΥΦΗ / ΣΗΜΑ ΠΩΛΗΣΗΣ)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BOTTOM (ΠΥΘΜΕΝΑΣ / ΣΗΜΑ ΑΓΟΡΑΣ)"
    override val piCycleDma111: String = "111-Ημερών SMA"
    override val piCycleDma350x2: String = "350-Ημερών SMA × 2 (Όριο Κορυφής)"
    override val piCycleEma150: String = "150-Ημερών EMA"
    override val piCycleSma471x0745: String = "471-Ημερών SMA × 0.745 (Όριο Πυθμένα)"
    override val piCycleMa200w: String = "Πυθμένας 200-Εβδομάδων SMA"
    override val piCycleDistanceToCross: String = "Απόσταση από Διασταύρωση Pi Top"
    override val piCycleDistanceToBottomCross: String = "Απόσταση από Διασταύρωση Πυθμένα"
    override val piCycleStatusSafeText: String = "Φάση Συσσώρευσης & Επέκτασης (Ασφαλής Ζώνη)"
    override val piCycleStatusAlertText: String = "🚨 ΑΝΙΧΝΕΥΤΗΚΕ ΔΙΑΣΤΑΥΡΩΣΗ PI CYCLE TOP (Κίνδυνος Κορυφής Κύκλου)"
    override val piCycleBottomStatusSafeText: String = "Πάνω από τον Ιστορικό Πυθμένα (Φάση Επέκτασης)"
    override val piCycleBottomStatusAlertText: String = "🚨 ΑΝΙΧΝΕΥΤΗΚΕ ΔΙΑΣΤΑΥΡΩΣΗ PI CYCLE BOTTOM (Ιστορική Αγορά Πυθμένα)"
    override val piCycleGenerationalSupport: String = "Ιστορικό Επίπεδο Στήριξης Γενεάς"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "ΤΕΡΜΑΤΙΚΟ FUTURES"
    override val futuresOfficialFeedsSub: String = "Επίσημες ροές Binance USDT-M · Μηδενικά προσομοιωμένα δεδομένα"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "ΠΑΡΩΧΗΜΕΝΟ"
    override val futuresStateOffline: String = "OFFLINE"
    override val futuresStateUnavailable: String = "ΜΗ ΔΙΑΘΕΣΙΜΟ"
    override val futuresLastMarkIndexTitle: String = "ΤΙΜΕΣ LAST / MARK / INDEX"
    override val futuresLastTradedPrice: String = "Τελευταία Τιμή Διαπραγμάτευσης"
    override val futuresMarkPrice: String = "Τιμή Mark"
    override val futuresIndexPrice: String = "Τιμή Δείκτη (Index)"
    override val futuresBasis: String = "Βάση (Mark - Index)"
    override val futuresHigh24h: String = "Υψηλό 24ω"
    override val futuresLow24h: String = "Χαμηλό 24ω"
    override val futuresVolume24h: String = "Όγκος 24ω (USDT)"
    override val futuresBboSpreadTitle: String = "ΒΕΛΤΙΣΤΗ ΠΡΟΣΦΟΡΑ / ΖΗΤΗΣΗ (BBO) & SPREAD"
    override val futuresBestBid: String = "ΚΑΛΥΤΕΡΗ ΠΡΟΣΦΟΡΑ (BID)"
    override val futuresBestAsk: String = "ΚΑΛΥΤΕΡΗ ΖΗΤΗΣΗ (ASK)"
    override val futuresOrderbookSpread: String = "Spread Βιβλίου Εντολών:"
    override val futuresPerpFundingTitle: String = "ΕΠΙΤΟΚΙΟ ΧΡΗΜΑΤΟΔΟΤΗΣΗΣ & ΑΝΤΙΣΤΡΟΦΗ ΜΕΤΡΗΣΗ"
    override val futuresCurrentFundingRate: String = "Τρέχον Επιτόκιο Χρηματοδότησης (Funding Rate)"
    override val futuresNextFundingIn: String = "Επόμενος Διακανονισμός σε"
    override val futuresApproxAprLabel: String = "Εκτιμώμενο APR (επιτόκιο × 3 × 365):"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (ΕΝΗΜΕΡΩΣΗ ΚΑΘΕ 15S)"
    override val futuresContracts: String = "συμβόλαια"
    override val futuresNoOpenInterest: String = "Δεν υπάρχουν δεδομένα open interest"
    override val futuresFearGreed5m: String = "Φόβος & Απληστία (5λ)"
    override val futuresBtcDominance60s: String = "Κυριαρχία BTC (60δ)"
    override val futuresLiquidationsTapeTitle: String = "🚨 Αναγκαστικές Εντολές Binance (Ρευστοποιήσεις)"
    override val futuresLiquidationsListening: String = "Ακρόαση ζωντανής ροής ρευστοποιήσεων Binance..."
    override val futuresCaptured: String = "καταγράφηκαν"
    override val futuresLongLiq: String = "LONG ΡΕΥΣΤΟΠΟΙΗΣΗ (ΠΩΛΗΣΗ)"
    override val futuresShortLiq: String = "SHORT ΡΕΥΣΤΟΠΟΙΗΣΗ (ΑΓΟΡΑ)"
    override val futuresTradesTapeTitle: String = "⚡ ΡΟΗ ΣΥΝΑΛΛΑΓΩΝ ΠΡΑΓΜΑΤΙΚΟΥ ΧΡΟΝΟΥ"
    override val futuresTradesAwaiting: String = "Αναμονή ροής συναλλαγών..."
    override val futuresPriceHeader: String = "Τιμή (USDT)"
    override val futuresQtyHeader: String = "Ποσότητα"
    override val futuresTimeHeader: String = "Ώρα"
    override val futuresLockedTitle: String = "Κλειδωμένο Ζεύγος Pro Futures"
    override val futuresLockedDesc: String = "Το %s (%s) είναι μέρος του επιπέδου Pro. Ξεκλειδώστε πλήρη ροή εντολών, arbitrage βάσης και δεδομένα perpetuals."
    override val futuresLockedButton: String = "Ξεκλείδωμα Πρόσβασης Pro"
    override val futuresProPair: String = "Ζεύγος Pro"
    override val futuresSizePrefix: String = "Μέγεθος:"
    override val futuresAllPairs: String = "Όλα τα Ζεύγη"
    override val futuresSearchPair: String = "Αναζήτηση κρυπτονομίσματος..."
    override val futuresSwitchPair: String = "Αλλαγή Ζεύγους"
    override val futuresPerpetualContract: String = "Συμβόλαιο Perpetual"

    // Market Intelligence & "Why is Asset Moving?" (ChatGPT 5.6 Luna Product Upgrade)
    override val intelligenceLayerTitle: String = "ΕΠΙΠΕΔΟ INTELLIGENCE ΑΓΟΡΑΣ"
    override val whyAssetMovingHeader: String = "Γιατί κινείται το %s;"
    override val marketStateHeader: String = "ΚΑΤΑΣΤΑΣΗ ΑΓΟΡΑΣ"
    override val confidenceHeader: String = "Αξιοπιστία"
    override val driversHeader: String = "Κύριοι Οδηγοί Κίνησης"
    override val driverSpotDemand: String = "Ζήτηση Spot"
    override val driverOpenInterest: String = "Ανοικτό Ενδιαφέρον (OI)"
    override val driverFundingSkew: String = "Κλίση Χρηματοδότησης (Funding)"
    override val driverLiquidations: String = "Πίεση Ρευστοποιήσεων"
    override val driverMacroSentiment: String = "Μακροοικονομικό Κλίμα"
    override val interpretationLabel: String = "Ερμηνεία: "
    override val cascadeRiskLabel: String = "Κίνδυνος Καταρράκτη: "
    override val invalidationLabel: String = "Ακύρωση Σεναρίου: "
    override val expandDeepDive: String = "Πάτημα για Πλήρη Ανάλυση & Ακύρωση"
    override val collapseDeepDive: String = "Απόκρυψη Ανάλυσης"
    override val liquidationMapHeader: String = "ΣΥΓΚΕΝΤΡΩΤΙΚΑ POOLS ΡΕΥΣΤΟΠΟΙΗΣΕΩΝ"
    override val liquidationMapSub: String = "Εκτιμώμενα επίπεδα ρευστότητας & στόχοι εκκαθάρισης"
    override val shortLiquidationPools: String = "Pools Ρευστοποίησης Shorts (Πάνω από την Τιμή)"
    override val longLiquidationPools: String = "Pools Ρευστοποίησης Longs (Κάτω από την Τιμή)"
    override val currentPriceAnchor: String = "ΤΡΕΧΟΥΣΑ ΤΙΜΗ"
    override val estimatedPoolSuffix: String = "εκτιμώμενη ρευστότητα"
    override val tabClustersMap: String = "Χάρτης Ρευστότητας"
    override val tabLiveStream: String = "Ζωντανή Ροή"

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Επίπεδο Market Intelligence: Πώς Λειτουργεί"
    override val marketIntelligenceInfoButton: String = "Τι είναι αυτό;"
    override val marketIntelligenceConfidenceTitle: String = "Δείκτης Εμπιστοσύνης (π.χ. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Μετρά την ποσοτική ισχύ της τρέχουσας τοποθέτησης στα futures βάσει όγκου, ανοικτού ενδιαφέροντος (OI) και ορμής."
    override val marketIntelligenceRegimesHeader: String = "Καθεστώτα Αγοράς (Τι σημαίνουν τα σήματα)"
    override val regimeShortSqueezeTitle: String = "Πίεση Short Squeeze"
    override val regimeShortSqueezeDesc: String = "Μεγάλες θέσεις short είναι παγιδευμένες. Μια μικρή ανοδική κίνηση μπορεί να πυροδοτήσει αλυσιδωτές ρευστοποιήσεις και απότομα spikes."
    override val regimeSpotAccumulationTitle: String = "Συσσώρευση Spot"
    override val regimeSpotAccumulationDesc: String = "Πραγματική απορρόφηση αγορών spot αντί για επισφαλές leverage. Σηματοδοτεί υγιή, βιώσιμη δομή αγοράς."
    override val regimeBalancedConsolidationTitle: String = "Ισορροπημένη Συσσώρευση"
    override val regimeBalancedConsolidationDesc: String = "Η μόχλευση παραγώγων και η ζήτηση spot βρίσκονται σε ισορροπία, υποδεικνύοντας διακύμανση σε εύρος τιμών."
    override val marketIntelligenceTelemetryHeader: String = "Βασική Τηλεμετρία"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Συνολικό κεφάλαιο κλειδωμένο σε ενεργά συμβόλαια παραγώγων."
    override val telemetryFundingRateTitle: String = "Funding Rate"
    override val telemetryFundingRateDesc: String = "Περιοδική αμοιβή μεταξύ longs και shorts. Πολύ θετικά ποσοστά προειδοποιούν για υπερμοχλευμένους longs επιρρεπείς σε καθαρισμό."
    override val marketIntelligenceUnderstood: String = "Κατάλαβα"

    // Structured 3-Line Metric Explainers (Headers & Micro-copy)
    override val explainerWhatItIsLabel: String = "Τι είναι: "
    override val explainerWhatItShowsLabel: String = "Τι δείχνει: "
    override val explainerNotASignalLabel: String = "Τι δεν σημαίνει: "

    // Macro Metric Explainers
    override val explainerNfpWhat: String = "Μηνιαία μεταβολή της απασχόλησης στις ΗΠΑ εκτός αγροτικού τομέα, από το Γραφείο Στατιστικής Εργασίας."
    override val explainerNfpShows: String = "Σφιχτότητα της αγοράς εργασίας και οικονομική δραστηριότητα που διαμορφώνει τις αποφάσεις επιτοκίων της Fed."
    override val explainerNfpNotMean: String = "Μακροοικονομικό πλαίσιο ρευστότητας επιτοκίων, όχι άμεσο σήμα κατεύθυνσης της αγοράς crypto."

    override val explainerCpiWhat: String = "Βασικός δείκτης πληθωρισμού που παρακολουθεί τη μεταβολή τιμών σε καλάθι αγαθών και υπηρεσιών."
    override val explainerCpiShows: String = "Διάβρωση αγοραστικής δύναμης καταναλωτών και πορεία προς τον στόχο 2% της Fed."
    override val explainerCpiNotMean: String = "Πλαίσιο τροχιάς πληθωρισμού, όχι αλγοριθμικό έναυσμα εκτέλεσης συναλλαγών."

    override val explainerFedWatchWhat: String = "Υπονοούμενη πιθανότητα μείωσης επιτοκίων υπολογισμένη από τα 30ήμερα συμβόλαια Fed Funds futures."
    override val explainerFedWatchShows: String = "Προσδοκίες συναίνεσης της αγοράς για τη νομισματική χαλάρωση της Federal Reserve."
    override val explainerFedWatchNotMean: String = "Κατανομή πιθανοτήτων αγοράς, όχι εγγυημένη δέσμευση πολιτικής της κεντρικής τράπεζας."

    override val explainerDxyWhat: String = "Γεωμετρικά σταθμισμένος δείκτης που μετρά την ισχύ του USD έναντι 6 βασικών νομισμάτων fiat."
    override val explainerDxyShows: String = "Συνθήκες παγκόσμιας ρευστότητας δολαρίου, φυγή κεφαλαίων και σχετική αγοραστική δύναμη."
    override val explainerDxyNotMean: String = "Παλίρροια μακροοικονομικής ρευστότητας, όχι μεμονωμένος καθοριστής πυθμένων ή κορυφών crypto."

    override val explainerUs10yWhat: String = "Ετήσια απόδοση τόκου στα 10ετή ομόλογα κρατικού χρέους των Ηνωμένων Πολιτειών."
    override val explainerUs10yShows: String = "Παγκόσμιο κόστος κεφαλαίου χωρίς ρίσκο και μακροπρόθεσμες προσδοκίες ανάπτυξης/πληθωρισμού."
    override val explainerUs10yNotMean: String = "Επιτόκιο αναγωγής για περιουσιακά στοιχεία ρίσκου, όχι βραχυπρόθεσμο έναυσμα εκτέλεσης."

    override val explainerBrentWhat: String = "Διεθνές σημείο αναφοράς τιμολόγησης για συμβόλαια φυσικού αργού πετρελαίου."
    override val explainerBrentShows: String = "Ενεργειακές πληθωριστικές πιέσεις εμπορευμάτων και παγκόσμια βιομηχανική δραστηριότητα."
    override val explainerBrentNotMean: String = "Συνιστώσα δεικτών πληθωρισμού, όχι άμεσος οδηγός τιμών crypto."

    // Futures Metric Explainers
    override val explainerFundingWhat: String = "Περιοδικό τέλος χρηματοδότησης που ανταλλάσσεται μεταξύ longs και shorts σε συμβόλαια perpetuals."
    override val explainerFundingShows: String = "Συγκέντρωση θέσεων των traders και κατευθυντική κλίση μόχλευσης στην αγορά παραγώγων."
    override val explainerFundingNotMean: String = "Η έντονη κλίση αντικατοπτρίζει μόχλευση, όχι άμεση ή εγγυημένη αντιστροφή τιμής."

    override val explainerOiWhat: String = "Συνολικές ανοιχτές θέσεις και αποτίμηση σε δολάρια σε όλα τα ενεργά συμβόλαια perpetuals."
    override val explainerOiShows: String = "Καθαρή εισροή ή εκροή κεφαλαίων παραγώγων και συνεχιζόμενη επέκταση μόχλευσης."
    override val explainerOiNotMean: String = "Μέτρηση συνολικής δέσμευσης παραγώγων, όχι κατευθυντικό αποτέλεσμα χωρίς το πλαίσιο τιμής."

    override val explainerSentimentWhat: String = "Δείκτης συναισθήματος (0-100) και μερίδιο κεφαλαιοποίησης του Bitcoin στην αγορά."
    override val explainerSentimentShows: String = "Διάθεση ανάληψης κινδύνου και εναλλαγή κεφαλαίων μεταξύ Bitcoin και Altcoins."
    override val explainerSentimentNotMean: String = "Ευρύτερη μακροοικονομική στάση αγοράς, όχι βραχυπρόθεσμο σήμα εκτέλεσης."

    override val explainerLiqWhat: String = "Αναγκαστικές ρευστοποιήσεις θέσεων που εκτελούνται κατά την παραβίαση του περιθωρίου συντήρησης."
    override val explainerLiqShows: String = "Συγκεντρωμένα επίπεδα τιμών όπου υπερ-μοχλευμένοι λογαριασμοί κλείνουν από το ανταλλακτήριο."
    override val explainerLiqNotMean: String = "Αναγκαστική απομόχλευση και αλυσιδωτές πωλήσεις, όχι οργανική θεσμική συσσώρευση."

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "AI Αναλυτής Αγοράς"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Ζωντανή Ανάλυση Κύκλων, Futures & On-Chain Ροών"
    override val aiPromptPlaceholder: String = "Ρωτήστε για κύκλο BTC, funding, support, altseason..."
    override val aiAskButton: String = "Ανάλυση"
    override val aiQuickActionCycle: String = "Κύκλος & Ρίσκο Halving"
    override val aiQuickActionFutures: String = "Funding & Ροή Μόχλευσης"
    override val aiQuickActionWhales: String = "Συσσώρευση Φαλαινών"
    override val aiQuickActionAltseason: String = "Ετοιμότητα Altseason"
    override val aiDisclaimer: String = "Τροφοδοτείται από ζωντανά μοντέλα Gemini AI & on-chain τηλεμετρία. Δεν αποτελεί οικονομική συμβουλή."
    override val aiThinking: String = "Ανάλυση ζωντανών δεδομένων & order book..."
    override val aiGreeting: String = "Γεια σας! Είμαι ο ζωντανός AI Αναλυτής του CryptoCycles. Ρωτήστε με οτιδήποτε για τις τρέχουσες τιμές, τα funding rates, τα μοτίβα του halving ή τις ζώνες ρευστοποιήσεων."
    override val aiClearHistory: String = "Καθαρισμός"
    override val aiLiveContextTag: String = "Ζωντανά Δεδομένα Συνδεδεμένα"
    override val aiPromptPrefixCycle: String = "Κάνε ανάλυση της τρέχουσας φάσης του κύκλου halving, του ρίσκου και των ιστορικών αναλογικών."
    override val aiPromptPrefixFutures: String = "Εξήγησε τα τρέχοντα funding rates, το open interest και τους κινδύνους ρευστοποιήσεων στα futures."
    override val aiPromptPrefixWhales: String = "Τι δείχνουν τα πρόσφατα whale alerts για θεσμική συσσώρευση ή διανομή;"
    override val aiPromptPrefixAltseason: String = "Αξιολόγησε αν οι συνθήκες αγοράς, το BTC dominance και το συναίσθημα ευνοούν ένα Altseason αυτή τη στιγμή."

    // CryptoCycle Design Suite Strings
    override val homeSubtitle: String = "Κατανόηση. Ανάλυση. Πιο Έξυπνες Αποφάσεις."
    override val bullishState: String = "Ανοδικό (Bullish)"
    override val bearishState: String = "Καθοδικό (Bearish)"
    override val neutralState: String = "Ουδέτερο"
    override val highRiskBadge: String = "Υψηλό Ρίσκο"
    override val moderateRiskBadge: String = "Μέτριο Ρίσκο"
    override val lowRiskBadge: String = "Χαμηλό Ρίσκο"
    override val threeThingsThatMatter: String = "3 πράγματα που μετράνε τώρα"
    override val tabOverview: String = "Επισκόπηση"
    override val tabCoins: String = "Νομίσματα"
    override val tabWatchlist: String = "Watchlist"
    override val tabSectors: String = "Τομείς"
    override val totalMarketCapLabel: String = "Συνολική Κεφαλαιοποίηση"
    override val volume24hLabel: String = "24ωρος Όγκος"
    override val explainAction: String = "Εξήγηση >"
    override val spotBuyingLabel: String = "Αγορές Spot"
    override val fundingRateLabel: String = "Επιτόκιο Funding"
    override val tabAnalytics: String = "Αναλυτικά"
    override val tabOnChain: String = "On-Chain"
    override val tabEvents: String = "Γεγονότα"
    override val onChainNetworkHeader: String = "Δίκτυο & On-Chain Μετρικές"
    override val eventsMilestonesHeader: String = "Ορόσημα Πρωτοκόλλου & Καταλύτες"
    override val upcomingTag: String = "ΕΠΙΚΕΙΜΕΝΟ"
    override val completedTag: String = "ΟΛΟΚΛΗΡΩΘΗΚΕ"
    override val activeTag: String = "ΕΝΕΡΓΟ"
    override val whaleConcentrationLabel: String = "Συγκέντρωση Μεγάλων Κατόχων (Whales)"
    override val exchangeNetFlowLabel: String = "Ροές Αποθεμάτων Ανταλλακτηρίων"
    override val netOutflowBias: String = "Καθαρές Εκροές (Συσσώρευση)"
    override val activeAddressesEstimate: String = "Ενεργά Πορτοφόλια (24ωρο)"
    override val cycleMomentumTitle: String = "Μομέντουμ Κύκλου & Τεχνική Υγεία"
    override val circulatingSupplyTitle: String = "Κυκλοφορούσα Προσφορά"
    override val maxSupplyLabel: String = "Μέγιστη Προσφορά"
    override val tabTopSignals: String = "Κορυφαία Σήματα"
    override val tabMySignals: String = "Τα Σήματά μου"
    override val tabPerformance: String = "Απόδοση"
    override val scoreLabel: String = "Βαθμολογία"
    override val timeframeLabel: String = "Χρονικό Πλαίσιο"
    override val expectedScenarioLabel: String = "Αναμενόμενο Σενάριο"
    override val viewFullAnalysisBtn: String = "Προβολή Πλήρους Ανάλυσης"
    override val tabCourses: String = "Μαθήματα"
    override val tabLessons: String = "Ενότητες"
    override val tabQuizzes: String = "Κουίζ"
    override val tabMyProgress: String = "Η Πρόοδός μου"
    override val commonMistakeLabel: String = "Συχνό λάθος"
    override val backLabel: String = "Πίσω"
    override val nextLabel: String = "Επόμενο"
    override val alertsTitle: String = "Ειδοποιήσεις"
    override val createAlertBtn: String = "Δημιουργία Alert"
    override val tabActive: String = "Ενεργά"
    override val tabHistory: String = "Ιστορικό"
    override val tabTemplates: String = "Πρότυπα"
    override val alertInsightLabel: String = "Insight Ειδοποίησης"
    override val alertInsightText: String = "Αυτός ο συνδυασμός αυξάνει ιστορικά τη μεταβλητότητα κατά 62% εντός των επόμενων 24 ωρών."
    override val whyBtn: String = "Γιατί;"
    override val marketCopilotTitle: String = "AI Αναλυτής Δεδομένων Αγοράς"
    override val betaBadge: String = "Beta"
    override val askAnythingMarket: String = "Ρωτήστε οτιδήποτε για την αγορά..."
    override val relatedDataLabel: String = "Σχετικά δεδομένα"
    override val liquidationMapTab: String = "Χάρτης Ρευστοποιήσεων"
    override val liquidationHeatmapTab: String = "Heatmap Ρευστοποιήσεων"
    override val liquidationWarningText: String = "Εντοπίστηκαν πυκνά pools ρευστοποιήσεων. Αυξημένος κίνδυνος μεταβλητότητας εάν σπάσει η στήριξη."
    override val exchangeBinance: String = "Binance"
    override val backtestBadgeText: String = "Επαληθευμένο Backtest 900: Win Rate 72.8% | Profit Factor: 2.14"
    override val derivativesRiskGuardrail: String = "Πρωτόκολλο Παραγώγων: Συναλλαγές με υπευθυνότητα. Ποτέ πάνω από 1-2% ρίσκο ανά θέση."
}
