package com.example.util

import com.example.data.model.AppLanguage

class ItalianAppStrings : AppStrings(AppLanguage.ITALIAN) {
    // Navigation & Core
    override val navMarkets: String = "Ciclo"
    override val navCoins: String = "Monete"
    override val navSignals: String = "Nastro"
    override val navSettings: String = "Impostazioni"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO ATTIVO"
    override val upgradeToPro: String = "Passa a Pro"
    override val searchPlaceholder: String = "Cerca oltre 100+ crypto..."
    override val cryptocurrenciesCount: String = "CRIPTOVALUTE"
    override val cryptocurrencySingular: String = "CRIPTOVALUTA"
    override val rankPrefix: String = "Posizione"
    override val closeButton: String = "Chiudi"
    override val institutionalTerminal: String = "Terminal Cicli e Derivati"
    override val latencyMs: String = "%dms latenza"
    override val realtimeFeed: String = "FEED IN TEMPO REALE"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Layer 1"
    override val catLayer2: String = "Layer 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "IA & Infra"
    override val catMeme: String = "Meme"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Utility"
    override val catFavorites: String = "Preferiti"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Panoramica di Mercato"
    override val marketsSubtitle: String = "Dove si muove ogni crypto, pattern storici, proiezioni future & whitepaper."
    override val currentPrice: String = "Prezzo Attuale"
    override val analogMatch: String = "Corrispondenza Storica"
    override val cyclePhase: String = "Fase del Ciclo"
    override val daysSinceAth: String = "Giorni dall'ATH"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "ANALOGO STORICO DEL CICLO"
    override val historicalAnalogProTitle: String = "Analogo Storico del Ciclo"
    override val historicalAnalogProUnlockedDesc: String = "Lo storico live e i movimenti realizzati sono attivi."
    override val historicalAnalogProDesc: String = "Sblocca i grafici di storico live e le schede dei movimenti realizzati."
    override val movementAnalysisHeader: String = "ANALISI DEL MOVIMENTO & STORIA DEL CICLO"
    override val nextMoveHeader: String = "MOVIMENTI LIVE REALIZZATI"
    override val cycleFractalLabel: String = "Giorno Frattale del Ciclo"
    override val historicalMatchLabel: String = "Come il prezzo si è mosso da un halving al successivo"
    override val proAnalyticsDesc: String = "Sblocca le linee 2016 e 2020 nello stesso giorno di ciclo per"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "STATISTICHE DI MERCATO & FORNITURA TOKEN"
    override val circulatingSupplyLabel: String = "Fornitura Circolante:"
    override val circulatingShort: String = "Circolante"
    override val infiniteDeflationary: String = "Infinita (Deflazionistica)"
    override val marketCapMetric: String = "CAPITALIZZAZIONE"
    override val volume24hMetric: String = "VOLUME 24H"
    override val tradingVolumeSub: String = "Volume di scambio"
    override val fdvMetric: String = "FDV (VALUTAZIONE)"
    override val fdvSub: String = "Valutazione completamente diluita"
    override val athMetric: String = "MASSIMO STORICO (ATH)"
    override val atlMetric: String = "MINIMO STORICO (ATL)"
    override val drawdownAthMetric: String = "CALO DALL'ATH"
    override val fromPeakSub: String = "Dal picco"
    override val allTimeLowMetric: String = "Minimo storico"
    override val allTimeHighMetric: String = "Massimo storico"
    override val startMetric: String = "Inizio"
    override val daysSinceHighMetric: String = "Giorni dal massimo"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & PIANO TECNOLOGICO"
    override val founderLabel: String = "CREATORE / FONDATORE"
    override val genesisDateLabel: String = "DATA DI GENESI"
    override val whatCoinDoesLabel: String = "Cosa fa la crypto (Core Whitepaper Blueprint)"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Emissione"
    override val useCasesLabel: String = "Casi d'Uso Principali dell'Ecosistema"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Settimane dal massimo storico"
    override val cycleAnalysisHeader: String = "Analisi del ciclo"
    override val fromHighToLowTitle: String = "DAL MASSIMO A UN POSSIBILE MINIMO"
    override val daysAfterAthLabel: String = "giorni dopo il massimo storico"
    override val daysToBottomLabel: String = "giorni, correzioni passate (media)"
    override val highMarker: String = "Alto"
    override val fromHighToLowDisclaimer: String = "Questo è ciò che hanno fatto i cicli passati. Non è una promessa: solo un orologio."
    override val thisCycleVsLastTitle: String = "QUESTO CICLO VS I PRECEDENTI"
    override val daysAfterHighTitle: String = "Giorni dopo il massimo"
    override val nowLabel: String = "Adesso"
    override val daysOfRiseTitle: String = "Giorni di rialzo, storicamente"
    override val daysOfRiseSub: String = "I rialzi passati dal fondo al massimo successivo sono durati circa 1059 giorni."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "giorni al prossimo halving"
    override val halvingHoursLabel: String = "ore rimanenti"
    override val whyWeSayThisTitle: String = "Contesto Storico e Avvertenze del Ciclo"

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Seleziona Asset"
    override val signalsAllCoins: String = "Tutte le 100+ Crypto"
    override val timeframe1D: String = "1G"
    override val timeframe1W: String = "1S"
    override val timeframe1M: String = "1M"
    override val timeframe1Y: String = "1A"
    override val timeframeCycle: String = "Ciclo Macro"
    override val signalBullish: String = "24h SU"
    override val signalBearish: String = "24h GIÙ"

    // Settings Screen
    override val settingsHeader: String = "Impostazioni"
    override val languageTitle: String = "Lingua"
    override val languageDesc: String = "Seleziona la tua lingua preferita"
    override val optionsTitle: String = "Opzioni"
    override val soundEffectsTitle: String = "Effetti Sonori Crypto (SFX)"
    override val soundEffectsSub: String = "Brevi suoni quando tocchi, cambi e navighi"
    override val soundTestTitle: String = "Test Effetti Audio"
    override val soundTestLaunch: String = "Scala Maggiore Ascendente 🎵"
    override val soundTestClick: String = "Tocco Tecnologico"
    override val soundTestToggle: String = "Suono Interruttore"
    override val soundTestChime: String = "Rintocco Premio Crypto"
    override val logChartsTitle: String = "Grafici Logaritmici"
    override val logChartsSub: String = "Visualizza i prezzi su scala logaritmica"
    override val proMembershipTitle: String = "Abbonamento Pro"
    override val manageProSubscription: String = "Gestisci abbonamento Pro"
    override val proTapeTitle: String = "LETTURA NASTRO PRO"
    override val proTapeDesc: String = "Sblocca la lettura live di RSI, EMA, ATR, funding ed ETF dalle chiusure giornaliere. Non è una previsione."
    override val proBenefit1: String = "Linee 2016 e 2020 nello stesso giorno di ciclo"
    override val proBenefit2: String = "Diario dei numeri live che l'app ha mostrato"
    override val proBenefit3: String = "Avviso opzionale del giorno di ciclo che apre il grafico"
    override val proBenefit4: String = "Nastro live di chiusure, funding e ETF — non è una previsione"
    override val proBenefit5: String = "IA che legge solo lo snapshot a schermo"
    override val proBenefit6: String = "Lezioni extra su leva, funding e order book — nessun ordine di trade"
    override val currencyDisplayTitle: String = "Valuta di Visualizzazione"
    override val howWeReadItTitle: String = "Come lo leggiamo — in parole semplici"
    override val plainItem1Title: String = "1. La storia si ripete in cicli"
    override val plainItem1Desc: String = "Le crypto seguono cicli di halving di circa 4 anni. Confrontiamo oggi con lo stesso giorno dopo gli halving del 2012, 2016 e 2020."
    override val plainItem2Title: String = "2. Analoghi Storici"
    override val plainItem2Desc: String = "Nel grafico del ciclo la curva viola è il 2020, quella ambra il 2016 e la linea ciano il ciclo attuale."
    override val plainItem3Title: String = "3. Fasce Storiche del Ciclo"
    override val plainItem3Desc: String = "Tramite regressione logaritmica calcoliamo zone storiche per finalità di studio. Tutti gli strumenti sono educativi e non costituiscono consulenza finanziaria."
    override val plainItem4Title: String = "4. Whitepaper Fondamentali"
    override val plainItem4Desc: String = "Ogni profilo include modello di consenso, tokenomics, fondatori e casi d'uso reali."
    override val plainItem5Title: String = "5. Avviso sul Rischio"
    override val plainItem5Desc: String = "I rendimenti passati non garantiscono risultati futuri. Investi con prudenza."
    override val privacyPolicyTitle: String = "Termini d'uso e Informativa sulla privacy"
    override val privacyPolicyView: String = "Consulta la nostra informativa sui dati e privacy"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Paghi le linee 2016/2020, il diario, l'avviso del giorno, il nastro live e le lezioni extra. Prezzo, cap, Fear & Greed e ETF 1 giorno restano gratis. Non è una previsione."
    override val proModalFeature1: String = "Linee 2016 e 2020 nello stesso giorno di ciclo"
    override val proModalFeature2: String = "Diario dei numeri live che l'app ha mostrato"
    override val proModalFeature3: String = "Avviso opzionale del giorno di ciclo che apre il grafico"
    override val proModalFeature4: String = "Nastro live di chiusure, funding e ETF — non è una previsione"
    override val proModalFeature5: String = "IA che legge solo lo snapshot a schermo"
    override val proModalFeature6: String = "Lezioni extra su leva, funding e order book — nessun ordine di trade"
    override val planMonthlyTitle: String = "Mensile"
    override val planMonthlyPeriod: String = "/ mese"
    override val planAnnualTitle: String = "Annuale"
    override val planAnnualPeriod: String = "/ anno"
    override val restorePurchases: String = "Ripristina Acquisti"
    override val restoringPurchases: String = "Verifica acquisti Google Play in corso..."
    override val playTermsDisclosure: String = "Il pagamento verrà addebitato sul tuo account Google Play alla conferma dell'acquisto. L'abbonamento si rinnova automaticamente a meno che non venga annullato almeno 24 ore prima della scadenza."
    override val financialDisclaimerTitle: String = "Disclaimer Finanziario e Normativo"
    override val financialDisclaimerText: String = "Storia educativa dei cicli passati. Non è una previsione e non è un consiglio. CryptoCycles non è un exchange, non detiene fondi e non dice di comprare o vendere."
    override val privacySheetTitle: String = "Privacy CryptoCycles"
    override val privSection1Title: String = "1. Raccolta Dati"
    override val privSection1Body: String = "I segnali e le finestre di acquisto/vendita sono pattern storici e non costituiscono consulenza finanziaria."
    override val privSection2Title: String = "2. Minori"
    override val privSection2Body: String = "CryptoCycles non è rivolto a minori di 13 anni."
    override val privSection3Title: String = "3. Contatti"
    override val privSection3Body: String = "Per domande sulla privacy, utilizza l'email fornita su Google Play."
    override val privSection4Title: String = "4. Archiviazione Locale"
    override val privSection4Body: String = "CryptoCycles non crea account utente né vende dati personali. Tutte le preferenze rimangono sul tuo dispositivo."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO linee di ciclo e lettura nastro"
    override val signalsProLockedSubtitle: String = "Sblocca le sovrapposizioni 2016 e 2020 e la lettura delle chiusure giornaliere. Non è una previsione."
    override val signalsProLockedFeature2: String = "Lettura live (RSI, EMA, ATR dalle chiusure giornaliere)"
    override val signalsProLockedFeature3: String = "Diario quotidiano di ciò che l'app ha mostrato"
    override val signalsGateTitle: String = "Sovrapposizioni di ciclo e lettura nastro"
    override val signalsGateDesc: String = "Sblocca le linee 2016 e 2020 e la lettura live delle chiusure. Non è un segnale e non è una previsione."
    override val signalsGateBadge: String = "Chiusure live · funding live · ETF live"

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "BRIEFING MACRO SETTIMANALE"
    override val weeklyBriefingSub: String = "Sintesi istituzionale settimanale del ciclo & orientamento al rischio"
    override val weeklyBriefingCurrentZone: String = "Zona Macro Attuale"
    override val weeklyBriefingActionTitle: String = "Orientamento Raccomandato"
    override val weeklyBriefingReasonTitle: String = "Sintesi in 3 Punti"
    override val weeklyBriefingProUnlockText: String = "Sblocca il Briefing Settimanale istituzionale, il playbook delle zone e gli analoghi macro con Pro."

    override val historicalAnalogProUnlockText: String = "Sblocca le linee 2016 e 2020 nello stesso giorno di ciclo. Solo storia."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Avvisi Push Cicli & Indicatori"
    override val alertSettingsSub: String = "Notifiche istantanee sul dispositivo per soglie critiche del ciclo di mercato"
    override val alertZoneChangeTitle: String = "Avviso Cambio Zona"
    override val alertZoneChangeDesc: String = "Avviso quando cambia la zona di umore del mercato (Paura, Neutro, Funding alto, Estremo), da Fear & Greed e funding"
    override val alertPiCycleTitle: String = "Distanza & Incrocio Pi Cycle Top"
    override val alertPiCycleDesc: String = "Avviso quando la 111DMA arriva entro il 10% della 350DMA × 2, la incrocia o se ne allontana. Controllo giornaliero"
    override val alertRainbowTitle: String = "Transizione Fascia Rainbow"
    override val alertRainbowDesc: String = "Notifica quando Bitcoin passa da una fascia di valutazione Rainbow all'altra"
    override val alert200WTitle: String = "Distanza dalla 200-Week SMA"
    override val alert200WDesc: String = "Avviso quando il prezzo scende sotto la 200W SMA, è fino al 10% sopra o 2,5× sopra. Controllo giornaliero"
    override val alertFreeLimitNotice: String = "La versione gratuita include fino a 2 avvisi attivi. Passa a Pro per avvisi illimitati."
    override val alertProUnlockNotice: String = "Funzionalità PRO: Avvisi push illimitati per cicli, Pi Cycle e Rainbow."

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "GRANDI PRINT BINANCE USDT-M (PRO)"
    override val whaleRadarSub: String = "Print futures Binance USDT-M da $100k. Non trasferimenti on-chain."
    override val whaleNotificationsTitle: String = "Notifiche Push Avviso Balene"
    override val whaleNotificationsDesc: String = "Notifica per un singolo trade Binance USDT-M futures sopra la tua soglia, mentre l'app è aperta."
    override val whaleNotificationsProLockedDesc: String = "Pro: avviso quando un print Binance USDT-M supera il filtro. Non trasferimenti on-chain."
    override val whaleThresholdTitle: String = "Soglia Minima Avviso Balene"
    override val whaleFilterAll: String = "Tutte le Balene"
    override val whaleFilterInflow: String = "🔻 Grandi vendite"
    override val whaleFilterBuy: String = "🔺 Grandi acquisti"
    override val whaleCollapse: String = "Comprimi"
    override val whaleViewAll: String = "Vedi tutti (%d)"
    override val timeJustNow: String = "Proprio ora"
    override val timeMinsAgo: String = "%d min fa"
    override val timeHoursAgo: String = "%d ore fa"
    override val liveOrderFlowTitle: String = "24/7 LIVE FLUSSO ORDINI (BINANCE)"
    override val liveOrderFlowSub: String = "Grandi print Binance USDT-M sui major: pressione acquisto vs vendita"
    override val buyDominanceLabel: String = "PRESSIONE ACQUISTI"
    override val sellDominanceLabel: String = "PRESSION VENDITE"
    override val liveExecutionFeed: String = "ESECUZIONI LIVE"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Indici Macro & Cicli"
    override val macroScreenSubtitle: String = "Modelli istituzionali di valutazione, Rainbow power law & sentiment di mercato"
    override val macroProLockedTitle: String = "Strumenti PRO di storia del ciclo"
    override val macroProLockedSubtitle: String = "Sblocca le bande Rainbow, gli incroci Pi Cycle e il briefing settimanale. Non è un segnale di acquisto o vendita."
    override val macroGateTitle: String = "Strumenti di storia del ciclo"
    override val macroGateDesc: String = "Bande Rainbow, incroci Pi Cycle e fatti settimanali. Solo storia — non è un trade."

    override val macroRainbowBadge: String = "STORIA"

    override val macroProLockedBadge: String = "🔒 Pro Bloccato"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Indice Altcoin Season"
    override val altSeasonSubtitle: String = "75% delle Top 50 monete che sovraperformano Bitcoin su 90 giorni"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Zona Neutra"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val topPerformers90d: String = "Top 90G Performer vs BTC"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Indice Fear & Greed"
    override val fearGreedSubtitle: String = "Sentiment di mercato, euforia & orologio di accumulo"
    override val fearGreedYesterday: String = "Ieri"
    override val fearGreedLastWeek: String = "Settimana Scorsa"
    override val fearGreedLastMonth: String = "Mese Scorso"
    override val extremeFearLabel: String = "Paura Estrema"
    override val fearLabel: String = "Paura"
    override val neutralLabel: String = "Neutro"
    override val greedLabel: String = "Avidità"
    override val extremeGreedLabel: String = "Avidità Estrema"
    override val fearGreedAccumulationTip: String = "Lettura del sentiment in diretta. Se manca il numero, appare un trattino. Non è un ordine di acquisto o vendita."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Indicatori Pi Cycle (Massimo & Fondo)"
    override val piCycleSubtitle: String = "Massimo (111SMA vs 350SMA×2) & Fondo (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (INCROCIO STORICO)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BOTTOM (INCROCIO STORICO)"
    override val piCycleDma111: String = "SMA 111 Giorni"
    override val piCycleDma350x2: String = "SMA 350 Giorni × 2 (Soglia Massimo)"
    override val piCycleEma150: String = "EMA 150 Giorni"
    override val piCycleSma471x0745: String = "SMA 471 Giorni × 0.745 (Soglia Fondo)"
    override val piCycleMa200w: String = "Fondo SMA 200 Settimane"
    override val piCycleStatusSafeText: String = "Fase di Accumulo & Espansione (Zona Sicura)"
    override val piCycleStatusAlertText: String = "🚨 INCROCIO PI CYCLE TOP RILEVATO (Rischio Massimo di Ciclo)"
    override val piCycleBottomStatusSafeText: String = "Sopra il Fondo Storico (Fase di Espansione)"
    override val piCycleBottomStatusAlertText: String = "🚨 INCROCIO PI CYCLE BOTTOM RILEVATO (fondo storico)"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "TERMINAL FUTURES"
    override val futuresOfficialFeedsSub: String = "Feed ufficiali Binance USDT-M · Zero dati simulati"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "OBSOLETO"
    override val futuresStateOffline: String = "OFFLINE"
    override val futuresStateUnavailable: String = "NON DISPONIBILE"
    override val futuresLastMarkIndexTitle: String = "PREZZI ULTIMO / MARK / INDEX"
    override val futuresLastTradedPrice: String = "Ultimo Prezzo Scambiato"
    override val futuresMarkPrice: String = "Prezzo Mark"
    override val futuresIndexPrice: String = "Prezzo Index"
    override val futuresBasis: String = "Base (Mark - Index)"
    override val futuresHigh24h: String = "Massimo 24h"
    override val futuresLow24h: String = "Minimo 24h"
    override val futuresVolume24h: String = "Volume 24h (USDT)"
    override val futuresBboSpreadTitle: String = "MIGLIORE OFFERTA / DOMANDA (BBO) & SPREAD"
    override val futuresBestBid: String = "MIGLIORE OFFERTA (BID)"
    override val futuresBestAsk: String = "MIGLIORE DOMANDA (ASK)"
    override val futuresOrderbookSpread: String = "Spread del book ordini:"
    override val futuresPerpFundingTitle: String = "TASSO DI FINANZIAMENTO & CONTO ALLA ROVESCIA"
    override val futuresCurrentFundingRate: String = "Tasso di Finanziamento Attuale"
    override val futuresNextFundingIn: String = "Prossimo Regolamento tra"
    override val futuresApproxAprLabel: String = "APR Stimato (tasso × 3 × 365):"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (AGGIORNATO OGNI 15S)"
    override val futuresContracts: String = "contratti"
    override val futuresLiquidationsListening: String = "In ascolto del flusso di liquidazioni Binance in tempo reale..."
    override val futuresLongLiq: String = "LIQUIDAZIONE LONG (VENDITA)"
    override val futuresShortLiq: String = "LIQUIDAZIONE SHORT (ACQUISTO)"
    override val futuresTradesTapeTitle: String = "⚡ NASTRO DEGLI SCAMBI IN TEMPO REALE"
    override val futuresTradesAwaiting: String = "In attesa del flusso di scambi..."
    override val futuresPriceHeader: String = "Prezzo (USDT)"
    override val futuresQtyHeader: String = "Q.tà"
    override val futuresTimeHeader: String = "Ora"
    override val futuresLockedTitle: String = "Coppia Futures Pro Bloccata"
    override val futuresLockedDesc: String = "%s (%s) fa parte del livello Pro. Sblocca il book ordini completo, l'arbitraggio di base e i dati dei perpetual."
    override val futuresLockedButton: String = "Sblocca Accesso Pro"
    override val futuresSizePrefix: String = "Dimensione:"

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "Analista di Mercato IA"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Intelligence in Tempo Reale su Cicli, Futures e Balene"
    override val aiPromptPlaceholder: String = "Chiedi sul ciclo BTC, funding, supporto, altseason..."
    override val aiAskButton: String = "Analizza"
    override val aiQuickActionCycle: String = "Ciclo e Rischio Halving"
    override val aiQuickActionFutures: String = "Funding e Flusso di Leva"
    override val aiQuickActionWhales: String = "Accumulo delle Balene"
    override val aiQuickActionAltseason: String = "Prontezza Altseason"
    override val aiDisclaimer: String = "Basato su modelli Gemini AI e telemetria in tempo reale. Non costituisce consulenza finanziaria."
    override val aiThinking: String = "Analisi della telemetria e dell'order book in tempo reale..."
    override val aiGreeting: String = "Sono qui. Cosa vorresti vedere?"
    override val aiClearHistory: String = "Cancella"
    override val aiLiveContextTag: String = "Dati in Tempo Reale Collegati"
    override val aiPromptPrefixCycle: String = "Analizza l'attuale fase del ciclo di halving, il rischio e gli analoghi storici."
    override val aiPromptPrefixFutures: String = "Interpreta gli attuali tassi di funding, open interest e rischi di liquidazione sui futures."
    override val aiPromptPrefixWhales: String = "Cosa indicano i recenti avvisi delle balene riguardo all'accumulo o alla distribuzione istituzionale?"
    override val aiPromptPrefixAltseason: String = "Valuta se le condizioni di mercato, la dominance di BTC e il sentiment favoriscono una Altseason adesso."
    override val backtestBadgeText: String = "Live whale radar · live order flow · live liquidations"
    override val derivativesRiskGuardrail: String = "Questa schermata legge il nastro dei perpetual. Non è un desk e non dimensiona le posizioni."

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Market Intelligence Layer: Come Funziona"
    override val marketIntelligenceInfoButton: String = "Cos'è questo?"
    override val marketIntelligenceConfidenceTitle: String = "Punteggio di Confidenza (es. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Misura la forza quantitativa del posizionamento attuale sui futures in base a volume, open interest e momentum."
    override val marketIntelligenceRegimesHeader: String = "Regimi di Mercato (Cosa significano i segnali)"
    override val regimeShortSqueezeTitle: String = "Pressione di Short Squeeze"
    override val regimeShortSqueezeDesc: String = "Forti posizioni short sono intrappolate. Un lieve rialzo potrebbe innescare liquidazioni a cascata e rapidi picchi."
    override val regimeSpotAccumulationTitle: String = "Accumulazione Spot"
    override val regimeSpotAccumulationDesc: String = "Assorbimento reale di acquisti spot anziché leva rischiosa. Segnala una struttura di mercato sana e sostenibile."
    override val regimeBalancedConsolidationTitle: String = "Consolidamento Equilibrato"
    override val regimeBalancedConsolidationDesc: String = "La leva sui derivati e la domanda spot sono in equilibrio, indicando trading in congestione."
    override val marketIntelligenceTelemetryHeader: String = "Telemetria Chiave"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Capitale totale bloccato in contratti derivati attivi."
    override val telemetryFundingRateTitle: String = "Funding Rate"
    override val telemetryFundingRateDesc: String = "Commissione periodica tra long e short. Tassi fortemente positivi avvisano di posizioni long troppo esposte e vulnerabili."
    override val marketIntelligenceUnderstood: String = "Ho capito"
}
