package com.example.util

import com.example.data.model.AppLanguage

class ItalianAppStrings : AppStrings(AppLanguage.ITALIAN) {
    // Navigation & Core
    override val navMarkets: String = "Ciclo"
    override val navCoins: String = "Monete"
    override val navFutures: String = "Futures"
    override val navSignals: String = "Nastro"
    override val navSettings: String = "Impostazioni"
    override val navMacro: String = "Macro"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO ATTIVO"
    override val backToFree: String = "Torna a Free"
    override val upgradeToPro: String = "Passa a Pro"
    override val proRequired: String = "Richiesto Pro"
    override val searchPlaceholder: String = "Cerca oltre 100+ crypto..."
    override val cryptocurrenciesCount: String = "CRIPTOVALUTE"
    override val cryptocurrencySingular: String = "CRIPTOVALUTA"
    override val turboEngineActive: String = "Motore Turbo Attivo"
    override val rankPrefix: String = "Posizione"
    override val closeButton: String = "Chiudi"
    override val institutionalTerminal: String = "Terminal Cicli e Derivati"
    override val trustBarFeed: String = "Feed Istituzionale: Book Ordini Diretto"
    override val latencyMs: String = "%dms latenza"
    override val realtimeFeed: String = "FEED IN TEMPO REALE"
    override val neutralPhase: String = "Fase Neutra"
    override val avg7d: String = "Media 7G"
    override val avg30d: String = "Media 30G"
    override val daysHigh: String = "g max"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Layer 1"
    override val catLayer2: String = "Layer 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "IA & Infra"
    override val catMeme: String = "Meme"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Utility"
    override val catFavorites: String = "Preferiti"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Panoramica di Mercato"
    override val marketsHeadline: String = "100+ Asset del Mondo Reale & Blueprint di Ciclo"
    override val marketsSubtitle: String = "Dove si muove ogni crypto, pattern storici, proiezioni future & whitepaper."
    override val fromAth: String = "dall'ATH"
    override val tapForCycleAnalog: String = "Tocca per analogo di ciclo, proiezioni & whitepaper"
    override val heroSubtitle: String = "ANALOGO STORICO DEL CICLO"
    override val currentPrice: String = "Prezzo Attuale"
    override val analogMatch: String = "Corrispondenza Storica"
    override val cyclePhase: String = "Fase del Ciclo"
    override val daysSinceAth: String = "Giorni dall'ATH"
    override val tapToViewCycles: String = "Tocca per esplorare cicli & whitepaper"

    // Markets Screen Teaser Cards
    override val marketsOrderFlowTeaserTitle: String = "Flusso Ordini & Profondità Futures"
    override val marketsOrderFlowTeaserSummary: String = "Funding · OI · Liquidazioni 24h"
    override val marketsOrderFlowTeaserLocked: String = "Bloccato"
    override val marketsOrderFlowTeaserLockedDesc: String = "Sblocca flusso di leva & liquidazioni in tempo reale"
    override val marketsOrderFlowTeaserUnlockedDesc: String = "Scala DOM in tempo reale & Book ordini"
    override val marketsOrderFlowTeaserUpgrade: String = "Aggiorna →"
    override val marketsOrderFlowTeaserOpenFutures: String = "Apri Futures →"
    override val marketsSignalsTeaserTitle: String = "Radar Balene & Segnali Frattali"
    override val marketsSignalsTeaserLiveTag: String = "FEED LIVE"
    override val marketsSignalsTeaserSample: String = "BTC: $148M accumulo netto su Coinbase Prime"
    override val marketsSignalsTeaserAccumulationTag: String = "ACCUMULO"
    override val marketsSignalsTeaserSub: String = "Mappe liquidazioni & frattali cicli 2016/2020"
    override val marketsSignalsTeaserOpen: String = "Apri scheda Segnali →"
    override val marketsMacroTeaserNextEvent: String = "Prossimo Evento: US Jobs (NFP) Venerdì 15:30 UTC"
    override val marketsMacroTeaserOpen: String = "Apri Macro →"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "ANALOGO STORICO DEL CICLO"
    override val historicalAnalogProUnlockedTitle: String = "Analisi del Ciclo Pro Sbloccata"
    override val historicalAnalogProTitle: String = "Analogo Storico del Ciclo"
    override val historicalAnalogProUnlockedDesc: String = "Lo storico live e i movimenti realizzati sono attivi."
    override val historicalAnalogProDesc: String = "Sblocca i grafici di storico live e le schede dei movimenti realizzati."
    override val historicalAnalogManagePro: String = "Gestisci Pro"
    override val historicalAnalogProPrice: String = "Sblocca Pro (3,99 €/mese)"
    override val movementAnalysisHeader: String = "ANALISI DEL MOVIMENTO & STORIA DEL CICLO"
    override val whereItMovesNowLabel: String = "Dove si muove adesso:"
    override val whereItMovedPastLabel: String = "Dove si è mosso nei cicli passati:"
    override val nextMoveHeader: String = "MOVIMENTI LIVE REALIZZATI"
    override val cycleFractalLabel: String = "Giorno Frattale del Ciclo"
    override val historicalMatchLabel: String = "Come il prezzo si è mosso da un halving al successivo"
    override val target1w: String = "1 Settimana"
    override val target2w: String = "2 Settimane"
    override val target4w: String = "4 Settimane"
    override val strategyGuideTitle: String = "📖 Guida Strategica: Quando Comprare & Vendere"
    override val buyMomentTitle: String = "🟢 Minimo storico Pi Cycle"
    override val buyMomentRules: String = "1. Quando il prezzo di Bitcoin tocca o si avvicina al Fondo 200W MA (<15% di divario). Questo segna i minimi storici del ciclo.\n2. Quando 111 DMA è molto al di sotto (>40%) di 350 DMA x 2. Minimo rischio al ribasso con massimo rendimento (DCA In)."
    override val sellMomentTitle: String = "🔴 Quando è il momento migliore per VENDERE (Massimo del Ciclo)"
    override val sellMomentRules: String = "1. Quando 111 DMA incrocia sopra 350 DMA x 2. Segnala alta probabilità di massimo di ciclo.\n2. Quando il Rainbow Chart entra nelle zone rosse 'Massima Bolla'. I dati storici mostrano correzioni massicce successive (90%+ per le altcoin)."
    override val rainbowFeatureLabel: String = "🌈 Bitcoin Rainbow Chart (Modello Power Law Dinamico)"
    override val altSeasonFeatureLabel: String = "⚡ Indice Altcoin Season (0-100) & Top 50 Outperformer"
    override val piCycleFeatureLabel: String = "🎯 Pi Cycle Top & Fondo 200W MA (incroci storici)"
    override val fearGreedFeatureLabel: String = "😱 Fear & Greed Analisi Multi-Periodo del Sentiment"
    override val proAnalyticsTitle: String = "Analisi del Ciclo Pro"
    override val proAnalyticsDesc: String = "Sblocca le linee 2016 e 2020 nello stesso giorno di ciclo per"
    override val proAnalyticsButton: String = "Sblocca Pro (3,99 €/mese)"
    override val projectedPeakLabel: String = "ATH"
    override val projectedBottomLabel: String = "ATL"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "STATISTICHE DI MERCATO & FORNITURA TOKEN"
    override val circulatingSupplyLabel: String = "Fornitura Circolante:"
    override val circulatingShort: String = "Circolante"
    override val infiniteDeflationary: String = "Infinita (Deflazionistica)"
    override val marketCapMetric: String = "CAPITALIZZAZIONE"
    override val volume24hMetric: String = "VOLUME 24H"
    override val tradingVolumeSub: String = "Volume di scambio"
    override val fdvMetric: String = "FDV (VALUTAZIONE)"
    override val fdvSub: String = "Valutazione completamente diluita"
    override val athMetric: String = "MASSIMO STORICO (ATH)"
    override val atlMetric: String = "MINIMO STORICO (ATL)"
    override val drawdownAthMetric: String = "CALO DALL'ATH"
    override val fromPeakSub: String = "Dal picco"
    override val allTimeLowMetric: String = "Minimo storico"
    override val allTimeHighMetric: String = "Massimo storico"
    override val startMetric: String = "Inizio"
    override val liveYearsMetric: String = "6443g · 17.64 anni attivo"
    override val daysSinceHighMetric: String = "Giorni dal massimo"
    override val dropFromHighMetric: String = "-36.0% calo dal massimo"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & PIANO TECNOLOGICO"
    override val founderLabel: String = "CREATORE / FONDATORE"
    override val genesisDateLabel: String = "DATA DI GENESI"
    override val whatCoinDoesLabel: String = "Cosa fa la crypto (Core Whitepaper Blueprint)"
    override val consensusLabel: String = "Meccanismo di Consenso & Architettura"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Emissione"
    override val useCasesLabel: String = "Casi d'Uso Principali dell'Ecosistema"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Settimana storicamente ribassista corrispondente (Campione: n=2 cicli)"
    override val weekOfFallSub: String = "settimana 46 · tipicamente 16 sett."
    override val cycleAnalysisHeader: String = "Analisi del ciclo"
    override val fromHighToLowTitle: String = "DAL MASSIMO A UN POSSIBILE MINIMO"
    override val daysAfterAthLabel: String = "giorni dopo il massimo storico"
    override val daysToBottomLabel: String = "giorni a un possibile minimo"
    override val highMarker: String = "Alto"
    override val typical383dMarker: String = "tipico 383g"
    override val lowMarker: String = "Basso"
    override val fromHighToLowNarrative: String = "Siamo a 319 giorni dal massimo storico. Storicamente, dal massimo al fondo sono trascorsi circa 383 giorni. Mancano circa 64 giorni a un possibile minimo."
    override val fromHighToLowDetails: String = "06 ott 2025 · \$124,752.53 · -36.0% dal massimo"
    override val fromHighToLowDisclaimer: String = "Questo è ciò che hanno fatto i cicli passati. Non è una promessa: solo un orologio."
    override val thisCycleVsLastTitle: String = "QUESTO CICLO VS I PRECEDENTI"
    override val daysAfterHighTitle: String = "Giorni dopo il massimo"
    override val daysAfterHighSub: String = "Siamo a 319 giorni dal massimo. I cali passati verso il fondo sono durati circa 383 giorni."
    override val nowLabel: String = "Adesso"
    override val daysOfRiseTitle: String = "Giorni di rialzo, storicamente"
    override val daysOfRiseSub: String = "I rialzi passati dal fondo al massimo successivo sono durati circa 1059 giorni."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "giorni al prossimo halving"
    override val halvingHoursLabel: String = "ore rimanenti"
    override val whatCameNextTitle: String = "Cosa è successo nei giorni corrispondenti dei cicli precedenti"
    override val timeframe1wk: String = "in 1 sett."
    override val timeframe2wk: String = "in 2 sett."
    override val timeframe4wk: String = "in 4 sett."
    override val winRate86: String = "Dall'ATH"
    override val whyWeSayThisTitle: String = "Contesto Storico e Avvertenze del Ciclo"
    override val whyPoint1: String = "Questa settimana del ciclo assomiglia al 28 giu 2018 — stessa fase, movimento simile."
    override val whyPoint2: String = "Abbiamo esaminato 14 settimane simili nel passato. Nelle 4 settimane successive il prezzo è salito 12 volte su 14 (tipicamente +29.5%)."
    override val whyPoint3: String = "Siamo alla settimana 46 di calo. In passato una fase simile è durata circa 16 settimane."
    override val whyPoint4: String = "Sia la posizione del ciclo che le settimane storiche puntano alla zona verde."

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Seleziona Asset"
    override val signalsAllCoins: String = "Tutte le 100+ Crypto"
    override val timeframe1D: String = "1G"
    override val timeframe1W: String = "1S"
    override val timeframe1M: String = "1M"
    override val timeframe1Y: String = "1A"
    override val timeframeCycle: String = "Ciclo Macro"
    override val signalBullish: String = "24h SU"
    override val signalBearish: String = "24h GIÙ"
    override val signalAccumulation: String = "BREAKOUT DI ACCUMULO"
    override val signalConfidence: String = "Frequenza di riferimento storico"
    override val signalLiveFeed: String = "Feed Live CoinGecko • Ticks 1s"
    override val analogComparisonHeader: String = "SOVRAPPOSIZIONE AZIONE DEI PREZZI STORICA"
    override val analogExplanation: String = "Allineamento della price action con date di cicli precedenti. Non è una previsione."
    override val highAccuracyNotice: String = "Registro di riferimento storico di backtest"

    // Settings Screen
    override val settingsHeader: String = "Impostazioni"
    override val languageTitle: String = "Lingua"
    override val languageDesc: String = "Seleziona la tua lingua preferita"
    override val appearanceTitle: String = "Aspetto"
    override val themeGalaxyDark: String = "Galaxy Dark (Predefinito)"
    override val themeGalaxyDarkSub: String = "Sfondo blu profondo OLED con dettagli ciano"
    override val themePureBlack: String = "Nero Puro"
    override val themePureBlackSub: String = "Modalità OLED nero assoluto per il massimo risparmio energetico"
    override val themeCleanWhite: String = "Bianco Pulito"
    override val themeCleanWhiteSub: String = "Tema chiaro per ambienti molto illuminati"
    override val optionsTitle: String = "Opzioni"
    override val soundEffectsTitle: String = "Effetti Sonori Crypto (SFX)"
    override val soundEffectsSub: String = "Feedback aptico su navigazione e avvisi"
    override val soundTestTitle: String = "Test Effetti Audio"
    override val soundTestLaunch: String = "Scala Maggiore Ascendente 🎵"
    override val soundTestClick: String = "Tocco Tecnologico"
    override val soundTestToggle: String = "Suono Interruttore"
    override val soundTestChime: String = "Rintocco Premio Crypto"
    override val hideMemecoinsTitle: String = "Nascondi Memecoin"
    override val hideMemecoinsSub: String = "Mostra solo progetti fondamentali ad alta capitalizzazione"
    override val logChartsTitle: String = "Grafici Logaritmici"
    override val logChartsSub: String = "Visualizza i prezzi su scala logaritmica"
    override val proMembershipTitle: String = "Abbonamento Pro"
    override val proMembershipPrice: String = "3,99 € / mese · 34,99 € / anno"
    override val manageProSubscription: String = "Gestisci abbonamento Pro"
    override val proPriceTrialLine: String = "3,99 € / mese · prova gratuita di 7 giorni"
    override val proTapeTitle: String = "LETTURA NASTRO PRO"
    override val proTapeDesc: String = "Sblocca la lettura live di RSI, EMA, ATR, funding ed ETF dalle chiusure giornaliere. Non è una previsione."
    override val proBenefit1: String = "Linee 2016 e 2020 nello stesso giorno di ciclo"
    override val proBenefit2: String = "Diario quotidiano di ciò che l'app ha mostrato"
    override val proBenefit3: String = "Avviso opzionale del giorno di ciclo che apre il grafico"
    override val proBenefit4: String = "Lettura live delle chiusure giornaliere — non è una previsione"
    override val proBenefit5: String = "IA che legge solo lo snapshot a schermo"
    override val proBenefit6: String = "La storia propria di una moneta, o nessuna linea. Educativo, non un consiglio."
    override val currencyDisplayTitle: String = "Valuta di Visualizzazione"
    override val howWeReadItTitle: String = "Come lo leggiamo — in parole semplici"
    override val plainItem1Title: String = "1. La storia si ripete in cicli"
    override val plainItem1Desc: String = "Le crypto seguono cicli di halving quadriennali. Allineiamo l'andamento odierno con il 2020 e il 2016."
    override val plainItem2Title: String = "2. Analoghi Storici"
    override val plainItem2Desc: String = "La curva arancione mostra il 2020; quella ciano il 2016. La linea bianca è la traiettoria attuale."
    override val plainItem3Title: String = "3. Fasce Storiche del Ciclo"
    override val plainItem3Desc: String = "Tramite regressione logaritmica calcoliamo zone storiche per finalità di studio. Tutti gli strumenti sono educativi e non costituiscono consulenza finanziaria."
    override val plainItem4Title: String = "4. Whitepaper Fondamentali"
    override val plainItem4Desc: String = "Ogni profilo include modello di consenso, tokenomics, fondatori e casi d'uso reali."
    override val plainItem5Title: String = "5. Avviso sul Rischio"
    override val plainItem5Desc: String = "I rendimenti passati non garantiscono risultati futuri. Investi con prudenza."
    override val privacyPolicyTitle: String = "Termini d'uso e Informativa sulla privacy"
    override val privacyPolicyView: String = "Consulta la nostra informativa sui dati e privacy"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Sblocca le linee 2016/2020, il diario e la lettura live. Non è una previsione. Disdici quando vuoi."
    override val proModalFeature1: String = "Linee 2016 e 2020 nello stesso giorno di ciclo"
    override val proModalFeature2: String = "Diario quotidiano di ciò che l'app ha mostrato"
    override val proModalFeature3: String = "Avviso opzionale del giorno di ciclo che apre il grafico"
    override val proModalFeature4: String = "Lettura live delle chiusure giornaliere — non è una previsione"
    override val proModalFeature5: String = "IA che legge solo lo snapshot a schermo"
    override val proModalFeature6: String = "La storia propria di una moneta, o nessuna linea. Educativo, non un consiglio."
    override val planMonthlyTitle: String = "Mensile"
    override val planMonthlyPrice: String = "3,99 €"
    override val planMonthlyPeriod: String = "/ mese"
    override val planMonthlyBadge: String = "Prova gratuita di 7 giorni"
    override val planAnnualTitle: String = "Annuale"
    override val planAnnualPrice: String = "34,99 €"
    override val planAnnualPeriod: String = "/ anno"
    override val planAnnualBadge: String = "Offerta Launch 40% • ~2,91 €/mese"
    override val subscribeProBtn: String = "Inizia prova gratuita di 7 giorni"
    override val startFreeTrialBtn: String = "Inizia prova gratuita di 7 giorni"
    override val startFreeTrialSub: String = "7 giorni gratis, poi 3,99 € / mese. Annulla in qualsiasi momento."
    override val continueYearlyBtn: String = "Continua con Annuale (34,99 €/anno)"
    override val continueYearlySub: String = "Accesso Pro Immediato • 34,99 € fatturati annualmente (~2,91 €/mese)"
    override val restorePurchases: String = "Ripristina Acquisti"
    override val restoringPurchases: String = "Verifica acquisti Google Play in corso..."
    override val cancelAnytime: String = "Annulla in qualsiasi momento su Google Play"
    override val playTermsDisclosure: String = "Il pagamento verrà addebitato sul tuo account Google Play alla conferma dell'acquisto. L'abbonamento si rinnova automaticamente a meno che non venga annullato almeno 24 ore prima della scadenza."
    override val financialDisclaimerTitle: String = "Disclaimer Finanziario e Normativo"
    override val financialDisclaimerText: String = "Storia educativa dei cicli passati. Non è una previsione e non è un consiglio. CryptoCycles non è un exchange, non detiene fondi e non dice di comprare o vendere."
    override val privacySheetTitle: String = "Privacy CryptoCycles"
    override val privacyLastUpdated: String = "Ultimo aggiornamento: 2026"
    override val privSection1Title: String = "1. Raccolta Dati"
    override val privSection1Body: String = "I segnali e le finestre di acquisto/vendita sono pattern storici e non costituiscono consulenza finanziaria."
    override val privSection2Title: String = "2. Minori"
    override val privSection2Body: String = "CryptoCycles non è rivolto a minori di 13 anni."
    override val privSection3Title: String = "3. Contatti"
    override val privSection3Body: String = "Per domande sulla privacy, utilizza l'email fornita su Google Play."
    override val privSection4Title: String = "4. Archiviazione Locale"
    override val privSection4Body: String = "CryptoCycles non crea account utente né vende dati personali. Tutte le preferenze rimangono sul tuo dispositivo."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO linee di ciclo e lettura nastro"
    override val signalsProLockedSubtitle: String = "Sblocca le sovrapposizioni 2016 e 2020 e la lettura delle chiusure giornaliere. Non è una previsione."
    override val signalsProLockedFeature1: String = "Linee 2016 e 2020 nello stesso giorno di ciclo"
    override val signalsProLockedFeature2: String = "Lettura live (RSI, EMA, ATR dalle chiusure giornaliere)"
    override val signalsProLockedFeature3: String = "Diario quotidiano di ciò che l'app ha mostrato"
    override val signalsProLockedFeature4: String = "Storia educativa. Non è una previsione e non è un consiglio."
    override val signalsGateTitle: String = "Sovrapposizioni di ciclo e lettura nastro"
    override val signalsGateDesc: String = "Sblocca le linee 2016 e 2020 e la lettura live delle chiusure. Non è un segnale e non è una previsione."
    override val signalsGateBadge: String = "Chiusure live · funding live · ETF live"

    // Zone Playbook Strings
    override val zonePlaybookTitle: String = "PLAYBOOK DELLE ZONE DI CICLO"
    override val zonePlaybookSub: String = "Guida didattica alla gestione del rischio basata sulle zone macro"
    override val zoneGreenAction: String = "Zona Verde • Ingresso Progressivo (Accumulo)"
    override val zoneGreenDesc: String = "Rapporto rischio/rendimento storicamente favorevole. Dollar-cost averaging sistematico sugli asset principali."
    override val zoneYellowAction: String = "Zona Gialla • Mantenimento & Ribilanciamento"
    override val zoneYellowDesc: String = "Fascia di valutazione intermedia. Mantenere le posizioni attuali, evitare decisioni emotive."
    override val zoneRedAction: String = "Zona Rossa • Uscita Progressiva (Riduzione Rischio)"
    override val zoneRedDesc: String = "Fascia di valutazione in ipercomprato. Storicamente prudente prendere profitti parziali e proteggere il capitale."
    override val zonePlaybookDisclaimer: String = "Solo per finalità didattiche e di studio. Nessuna consulenza finanziaria."

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "BRIEFING MACRO SETTIMANALE"
    override val weeklyBriefingSub: String = "Sintesi istituzionale settimanale del ciclo & orientamento al rischio"
    override val weeklyBriefingCurrentZone: String = "Zona Macro Attuale"
    override val weeklyBriefingActionTitle: String = "Orientamento Raccomandato"
    override val weeklyBriefingActionAccumulate: String = "ACCUMULO"
    override val weeklyBriefingActionHold: String = "MANTENIMENTO"
    override val weeklyBriefingActionReduce: String = "RIDUZIONE"
    override val weeklyBriefingReasonTitle: String = "Sintesi in 3 Punti"
    override val weeklyBriefingLine1: String = "1. Le metriche di valutazione macro rimangono nel corridoio inferiore di accumulo."
    override val weeklyBriefingLine2: String = "2. Il fondo 200W SMA e la dinamica di offerta dell'halving continuano a fornire solido supporto strutturale a lungo termine."
    override val weeklyBriefingLine3: String = "3. L'accumulo sui wallet on-chain mostra un assorbimento costante durante le fasi di consolidamento."
    override val weeklyBriefingProUnlockText: String = "Sblocca il Briefing Settimanale istituzionale, il playbook delle zone e gli analoghi macro con Pro."

    // Historical Analog Card Strings
    override val historicalAnalogCardTitle: String = "ANALOGO STORICO DEL CICLO"
    override val historicalAnalogPhaseText: String = "Siamo nella stessa fase di ciclo del %s."
    override val historicalAnalogFollowThrough: String = "Dopo quel punto, l'evoluzione tipica è stata: 30g: %s • 90g: %s • 180g: %s"
    override val historicalAnalogNotFinancialAdvice: String = "Modello didattico basato sulla storia frattale del 2016 & 2020. Nessuna consulenza finanziaria."
    override val historicalAnalogProUnlockText: String = "Sblocca le linee 2016 e 2020 nello stesso giorno di ciclo. Solo storia."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Avvisi Push Cicli & Indicatori"
    override val alertSettingsSub: String = "Notifiche istantanee sul dispositivo per soglie critiche del ciclo di mercato"
    override val alertZoneChangeTitle: String = "Avviso Cambio Zona"
    override val alertZoneChangeDesc: String = "Notifica quando Bitcoin passa tra le zone Verde, Gialla e Rossa"
    override val alertPiCycleTitle: String = "Distanza & Incrocio Pi Cycle Top"
    override val alertPiCycleDesc: String = "Notifica quando la distanza tra 111DMA e 350DMA x 2 si restringe o incrocia"
    override val alertRainbowTitle: String = "Transizione Fascia Rainbow"
    override val alertRainbowDesc: String = "Notifica quando Bitcoin passa da una fascia di valutazione Rainbow all'altra"
    override val alert200WTitle: String = "Distanza dalla 200-Week SMA"
    override val alert200WDesc: String = "Notifica quando il prezzo si avvicina o devia significativamente dalla 200W SMA"
    override val alertFreeLimitNotice: String = "La versione gratuita include fino a 2 avvisi attivi. Passa a Pro per avvisi illimitati."
    override val alertProUnlockNotice: String = "Funzionalità PRO: Avvisi push illimitati per cicli, Pi Cycle e Rainbow."

    // Widget Strings
    override val widgetSettingsTitle: String = "Widget Schermata Home"
    override val widgetSettingsDesc: String = "Mostra la zona attuale del ciclo, il prezzo di BTC e i giorni dall'ATH nella schermata home"
    override val widgetZoneLabel: String = "Zona"
    override val widgetBtcPriceLabel: String = "Prezzo BTC"
    override val widgetDaysSinceAthLabel: String = "Giorni da ATH"

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "GRANDI PRINT BINANCE USDT-M (PRO)"
    override val whaleRadarSub: String = "Print futures Binance USDT-M da $100k. Non trasferimenti on-chain."
    override val whaleNotificationsTitle: String = "Notifiche Push Avviso Balene"
    override val whaleNotificationsDesc: String = "Ricevi avvisi istantanei per acquisti massicci di balene o depositi sugli exchange."
    override val whaleNotificationsProLockedDesc: String = "Pro: avviso quando un print Binance USDT-M supera il filtro. Non trasferimenti on-chain."
    override val whaleThresholdTitle: String = "Soglia Minima Avviso Balene"
    override val whaleFilterAll: String = "Tutte le Balene"
    override val whaleFilterInflow: String = "🚨 Entrate / Vendite"
    override val whaleFilterOutflow: String = "🟢 Accumulo"
    override val whaleFilterBuy: String = "🚀 Mega Acquisti"
    override val whaleCollapse: String = "Comprimi"
    override val whaleViewAll: String = "Vedi tutti (%d)"
    override val timeJustNow: String = "Proprio ora"
    override val timeMinsAgo: String = "%d min fa"
    override val timeHoursAgo: String = "%d ore fa"
    override val liveOrderFlowTitle: String = "24/7 LIVE FLUSSO ORDINI (BINANCE)"
    override val liveOrderFlowSub: String = "Flusso tick in tempo reale: Oscillatore pressione acquisto vs vendita"
    override val buyDominanceLabel: String = "PRESSIONE ACQUISTI"
    override val sellDominanceLabel: String = "PRESSION VENDITE"
    override val netVolumeDelta: String = "FLUSSO NETTO 24H"
    override val liveExecutionFeed: String = "ESECUZIONI LIVE"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Indici Macro & Cicli"
    override val macroScreenSubtitle: String = "Modelli istituzionali di valutazione, Rainbow power law & sentiment di mercato"
    override val macroUpdated4m: String = "Aggiornato 4 min fa"
    override val macroProLockedTitle: String = "Strumenti PRO di storia del ciclo"
    override val macroProLockedSubtitle: String = "Sblocca le bande Rainbow, gli incroci Pi Cycle e il briefing settimanale. Non è un segnale di acquisto o vendita."
    override val macroGateTitle: String = "Strumenti di storia del ciclo"
    override val macroGateDesc: String = "Bande Rainbow, incroci Pi Cycle e fatti settimanali. Solo storia — non è un trade."

    // Macro Filters
    override val macroFilterAll: String = "Tutti gli Indici"
    override val macroFilterEconomicCalendar: String = "📅 Calendario NFP & CPI"
    override val macroFilterRiskBackdrop: String = "🌐 DXY, 10Y & FedWatch"
    override val macroFilterRainbow: String = "🌈 Rainbow Chart"
    override val macroFilterAltSeason: String = "⚡ Alt Season"
    override val macroFilterFearGreed: String = "😱 Fear & Greed"
    override val macroFilterPiCycle: String = "🎯 Pi Cycle & 200W"

    // Macro Economic Calendar & Risk Cards
    override val macroEconomicCalendarCardTitle: String = "📅 Dati Economici & NFP / CPI"
    override val macroEconomicCalendarCardSub: String = "Prossimo: US Jobs (NFP) Venerdì 15:30 UTC"
    override val macroNfpFridayBadge: String = "NFP VENERDÌ"
    override val macroRiskBackdropCardTitle: String = "🌐 DXY, Rendimenti 10Y & FedWatch"
    override val macroRiskBackdropCardSub: String = "Liquidità Globale USD & Rendimenti Sovrani"
    override val macroRiskBackdropBadge: String = "CONTESTO MACRO"
    override val macroRainbowCardTitle: String = "🌈 Modello Prezzo Bitcoin Rainbow"
    override val macroRainbowCardSub: String = "Fasce di Valutazione Logaritmiche"
    override val macroRainbowBadge: String = "STORIA"
    override val macroAltSeasonCardTitle: String = "⚡ Indice Altcoin Season"
    override val macroAltSeasonCardSub: String = "42/100 · Zona Neutra (Bitcoin Season)"
    override val macroFearGreedCardTitle: String = "😱 Indice Fear & Greed"
    override val macroFearGreedCardSub: String = "68/100 · Sentiment di Avidità"

    override val macroUsJobsTitle: String = "US Jobs: Non-Farm Payrolls (NFP)"
    override val macroUsJobsTime: String = "Venerdì 15:30 UTC"
    override val macroCpiTitle: String = "Indice dei Prezzi al Consumo USA (CPI)"
    override val macroCpiTime: String = "Prossimo Mercoledì 13:30 UTC"
    override val macroForecastLabel: String = "Previsione"
    override val macroPreviousLabel: String = "Precedente"
    override val macroVolatilityLabel: String = "Volatilità"
    override val macroConsensusYoyLabel: String = "Consenso YoY"
    override val macroPriorYoyLabel: String = "Precedente YoY"
    override val macroProOnly: String = "🔒 Solo Pro"
    override val macroProHigh: String = "🔒 Alta"
    override val macroProLockedBadge: String = "🔒 Pro Bloccato"

    override val macroFedWatchTitle: String = "CME FedWatch: Probabilità Taglio Tassi"
    override val macroDxyTitle: String = "DXY: Indice del Dollaro USA"
    override val macroUs10yTitle: String = "US 10Y: Rendimento dei Titoli del Tesoro USA a 10 Anni"
    override val macroBrentTitle: String = "Petrolio Greggio Brent"

    // Rainbow Chart Strings
    override val rainbowHeaderTitle: String = "Bitcoin Rainbow Chart"
    override val rainbowHeaderSubtitle: String = "Grafico Dinamico Rainbow"
    override val rainbowFormulaTag: String = "Power Law Dinamico (Fit R² 94.3%)"
    override val rainbowDescription: String = "Modello dinamico di regressione logaritmica Power Law adattato all'intera storia dei prezzi di Bitcoin dal 2012."
    override val rainbowCurrentBandLabel: String = "Fascia di Valutazione Attuale"
    override val rainbowCyclePeakTarget: String = "Target Massimo di Ciclo"
    override val rainbowFireSaleTarget: String = "Fondo di Liquidazione (Fire Sale)"
    override val rainbowFilterAll: String = "Tutte le Fasce"
    override val rainbowInspectHelp: String = "Tocca e trascina sul grafico per ispezionare prezzi storici & fasce"
    override val halvingVerticalLabel: String = "Halving"
    override val halving2032Est: String = "Halving 2032 (Stimato)"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Indice Altcoin Season"
    override val altSeasonSubtitle: String = "75% delle Top 50 monete che sovraperformano Bitcoin su 90 giorni"
    override val altSeasonScoreLabel: String = "Punteggio Altcoin Season"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Zona Neutra"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val altSeasonOutperformedCount: String = "%d su %d monete hanno superato BTC"
    override val topPerformers90d: String = "Top 90G Performer vs BTC"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Indice Fear & Greed"
    override val fearGreedSubtitle: String = "Sentiment di mercato, euforia & orologio di accumulo"
    override val fearGreedNow: String = "Oggi"
    override val fearGreedYesterday: String = "Ieri"
    override val fearGreedLastWeek: String = "Settimana Scorsa"
    override val fearGreedLastMonth: String = "Mese Scorso"
    override val extremeFearLabel: String = "Paura Estrema"
    override val fearLabel: String = "Paura"
    override val neutralLabel: String = "Neutro"
    override val greedLabel: String = "Avidità"
    override val extremeGreedLabel: String = "Avidità Estrema"
    override val fearGreedAccumulationTip: String = "Lettura del sentiment in diretta. Se manca il numero, appare un trattino. Non è un ordine di acquisto o vendita."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Indicatori Pi Cycle (Massimo & Fondo)"
    override val piCycleSubtitle: String = "Massimo (111SMA vs 350SMA×2) & Fondo (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (INCROCIO STORICO)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BOTTOM (INCROCIO STORICO)"
    override val piCycleDma111: String = "SMA 111 Giorni"
    override val piCycleDma350x2: String = "SMA 350 Giorni × 2 (Soglia Massimo)"
    override val piCycleEma150: String = "EMA 150 Giorni"
    override val piCycleSma471x0745: String = "SMA 471 Giorni × 0.745 (Soglia Fondo)"
    override val piCycleMa200w: String = "Fondo SMA 200 Settimane"
    override val piCycleDistanceToCross: String = "Distanza dall'Incrocio Pi Top"
    override val piCycleDistanceToBottomCross: String = "Distanza dall'Incrocio di Fondo"
    override val piCycleStatusSafeText: String = "Fase di Accumulo & Espansione (Zona Sicura)"
    override val piCycleStatusAlertText: String = "🚨 INCROCIO PI CYCLE TOP RILEVATO (Rischio Massimo di Ciclo)"
    override val piCycleBottomStatusSafeText: String = "Sopra il Fondo Storico (Fase di Espansione)"
    override val piCycleBottomStatusAlertText: String = "🚨 INCROCIO PI CYCLE BOTTOM RILEVATO (fondo storico)"
    override val piCycleGenerationalSupport: String = "Supporto Storico Generazionale"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "TERMINAL FUTURES"
    override val futuresOfficialFeedsSub: String = "Feed ufficiali Binance USDT-M · Zero dati simulati"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "OBSOLETO"
    override val futuresStateOffline: String = "OFFLINE"
    override val futuresStateUnavailable: String = "NON DISPONIBILE"
    override val futuresLastMarkIndexTitle: String = "PREZZI ULTIMO / MARK / INDEX"
    override val futuresLastTradedPrice: String = "Ultimo Prezzo Scambiato"
    override val futuresMarkPrice: String = "Prezzo Mark"
    override val futuresIndexPrice: String = "Prezzo Index"
    override val futuresBasis: String = "Base (Mark - Index)"
    override val futuresHigh24h: String = "Massimo 24h"
    override val futuresLow24h: String = "Minimo 24h"
    override val futuresVolume24h: String = "Volume 24h (USDT)"
    override val futuresBboSpreadTitle: String = "MIGLIORE OFFERTA / DOMANDA (BBO) & SPREAD"
    override val futuresBestBid: String = "MIGLIORE OFFERTA (BID)"
    override val futuresBestAsk: String = "MIGLIORE DOMANDA (ASK)"
    override val futuresOrderbookSpread: String = "Spread del book ordini:"
    override val futuresPerpFundingTitle: String = "TASSO DI FINANZIAMENTO & CONTO ALLA ROVESCIA"
    override val futuresCurrentFundingRate: String = "Tasso di Finanziamento Attuale"
    override val futuresNextFundingIn: String = "Prossimo Regolamento tra"
    override val futuresApproxAprLabel: String = "APR Stimato (tasso × 3 × 365):"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (AGGIORNATO OGNI 15S)"
    override val futuresContracts: String = "contratti"
    override val futuresNoOpenInterest: String = "Nessun dato di open interest"
    override val futuresFearGreed5m: String = "Paura & Avidità (5m)"
    override val futuresBtcDominance60s: String = "Dominance BTC (60s)"
    override val futuresLiquidationsTapeTitle: String = "🚨 Ordini Forzati Binance (Liquidazioni)"
    override val futuresLiquidationsListening: String = "In ascolto del flusso di liquidazioni Binance in tempo reale..."
    override val futuresCaptured: String = "catturate"
    override val futuresLongLiq: String = "LIQUIDAZIONE LONG (VENDITA)"
    override val futuresShortLiq: String = "LIQUIDAZIONE SHORT (ACQUISTO)"
    override val futuresTradesTapeTitle: String = "⚡ NASTRO DEGLI SCAMBI IN TEMPO REALE"
    override val futuresTradesAwaiting: String = "In attesa del flusso di scambi..."
    override val futuresPriceHeader: String = "Prezzo (USDT)"
    override val futuresQtyHeader: String = "Q.tà"
    override val futuresTimeHeader: String = "Ora"
    override val futuresLockedTitle: String = "Coppia Futures Pro Bloccata"
    override val futuresLockedDesc: String = "%s (%s) fa parte del livello Pro. Sblocca il book ordini completo, l'arbitraggio di base e i dati dei perpetual."
    override val futuresLockedButton: String = "Sblocca Accesso Pro"
    override val futuresProPair: String = "Coppia Pro"
    override val futuresSizePrefix: String = "Dimensione:"

    // Structured 3-Line Metric Explainers (Headers & Micro-copy)
    override val explainerWhatItIsLabel: String = "Cos'è: "
    override val explainerWhatItShowsLabel: String = "Cosa mostra: "
    override val explainerNotASignalLabel: String = "Cosa non significa: "

    // Macro Metric Explainers
    override val explainerNfpWhat: String = "Variazione mensile dell'occupazione USA non agricola, pubblicata dal Bureau of Labor Statistics."
    override val explainerNfpShows: String = "Rigidità del mercato del lavoro e attività economica che orientano direttamente le decisioni sui tassi della Fed."
    override val explainerNfpNotMean: String = "Contesto di liquidità macro per i tassi, non un segnale direzionale diretto per il mercato crypto."

    override val explainerCpiWhat: String = "Misura chiave dell'inflazione che traccia le variazioni medie dei prezzi di un paniere di beni e servizi."
    override val explainerCpiShows: String = "Erosione del potere d'acquisto dei consumatori e percorso verso l'obiettivo del 2% della Fed."
    override val explainerCpiNotMean: String = "Contesto di traiettoria dell'inflazione, non un trigger algoritmico di esecuzione."

    override val explainerFedWatchWhat: String = "Probabilità implicita di taglio dei tassi calcolata dai futures sui Fed Funds a 30 giorni."
    override val explainerFedWatchShows: String = "Aspettative di consenso del mercato sull'allentamento monetario della Federal Reserve."
    override val explainerFedWatchNotMean: String = "Distribuzione delle probabilità di mercato, non un impegno garantito della banca centrale."

    override val explainerDxyWhat: String = "Indice ponderato geometricamente che misura la forza dell'USD rispetto a 6 principali valute fiat."
    override val explainerDxyShows: String = "Condizioni globali di liquidità in dollari, fuga di capitali e relativo potere d'acquisto del dollaro."
    override val explainerDxyNotMean: String = "Marea di liquidità macro, non un fattore determinante isolato per massimi o minimi crypto."

    override val explainerUs10yWhat: String = "Rendimento annuo dei titoli di debito sovrano a 10 anni del governo statunitense."
    override val explainerUs10yShows: String = "Costo globale del capitale privo di rischio e aspettative di crescita/inflazione a lungo termine."
    override val explainerUs10yNotMean: String = "Tasso di sconto macro per asset a rischio, non un trigger di esecuzione a breve termine."

    override val explainerBrentWhat: String = "Benchmark internazionale di prezzo per i contratti fisici di petrolio greggio."
    override val explainerBrentShows: String = "Pressioni inflazionistiche sulle materie prime energetiche e attività industriale globale."
    override val explainerBrentNotMean: String = "Componente degli indici di inflazione, non un driver diretto dei prezzi crypto."

    // Futures Metric Explainers
    override val explainerFundingWhat: String = "Commissione periodica scambiata tra posizioni long e short sui contratti perpetual."
    override val explainerFundingShows: String = "Concentrazione del posizionamento dei trader e inclinazione direzionale della leva sui derivati."
    override val explainerFundingNotMean: String = "Una forte inclinazione riflette la leva, non un'inversione immediata o garantita dei prezzi."

    override val explainerOiWhat: String = "Totale delle posizioni aperte e valore in dollari su tutti i contratti perpetual attivi."
    override val explainerOiShows: String = "Flusso netto di entrata o uscita di capitale dai derivati e continua espansione della leva."
    override val explainerOiNotMean: String = "Misura dell'impegno complessivo sui derivati, non un esito direzionale senza contesto di prezzo."

    override val explainerSentimentWhat: String = "Indice di sentiment (0-100) e quota di mercato della capitalizzazione di Bitcoin."
    override val explainerSentimentShows: String = "Propensione al rischio del mercato e rotazione di capitale tra Bitcoin e Altcoin."
    override val explainerSentimentNotMean: String = "Quadro macro complessivo del mercato, non un segnale di esecuzione a breve termine."

    override val explainerLiqWhat: String = "Chiusure forzate di posizioni eseguite alla violazione del margine di mantenimento."
    override val explainerLiqShows: String = "Aree di prezzo concentrate in cui i conti sovra-indebitati vengono liquidati dall'exchange."
    override val explainerLiqNotMean: String = "Cascate di chiusure forzate, non un accumulo istituzionale direzionale organico."

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "Analista di Mercato IA"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Intelligence in Tempo Reale su Cicli, Futures e Balene"
    override val aiPromptPlaceholder: String = "Chiedi sul ciclo BTC, funding, supporto, altseason..."
    override val aiAskButton: String = "Analizza"
    override val aiQuickActionCycle: String = "Ciclo e Rischio Halving"
    override val aiQuickActionFutures: String = "Funding e Flusso di Leva"
    override val aiQuickActionWhales: String = "Accumulo delle Balene"
    override val aiQuickActionAltseason: String = "Prontezza Altseason"
    override val aiDisclaimer: String = "Basato su modelli Gemini AI e telemetria in tempo reale. Non costituisce consulenza finanziaria."
    override val aiThinking: String = "Analisi della telemetria e dell'order book in tempo reale..."
    override val aiGreeting: String = "Sono qui. Cosa vorresti vedere?"
    override val aiClearHistory: String = "Cancella"
    override val aiLiveContextTag: String = "Dati in Tempo Reale Collegati"
    override val aiPromptPrefixCycle: String = "Analizza l'attuale fase del ciclo di halving, il rischio e gli analoghi storici."
    override val aiPromptPrefixFutures: String = "Interpreta gli attuali tassi di funding, open interest e rischi di liquidazione sui futures."
    override val aiPromptPrefixWhales: String = "Cosa indicano i recenti avvisi delle balene riguardo all'accumulo o alla distribuzione istituzionale?"
    override val aiPromptPrefixAltseason: String = "Valuta se le condizioni di mercato, la dominance di BTC e il sentiment favoriscono una Altseason adesso."
    override val backtestBadgeText: String = "Live whale radar · live order flow · live liquidations"
    override val derivativesRiskGuardrail: String = "Questa schermata legge il nastro dei perpetual. Non è un desk e non dimensiona le posizioni."

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Market Intelligence Layer: Come Funziona"
    override val marketIntelligenceInfoButton: String = "Cos'è questo?"
    override val marketIntelligenceConfidenceTitle: String = "Punteggio di Confidenza (es. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Misura la forza quantitativa del posizionamento attuale sui futures in base a volume, open interest e momentum."
    override val marketIntelligenceRegimesHeader: String = "Regimi di Mercato (Cosa significano i segnali)"
    override val regimeShortSqueezeTitle: String = "Pressione di Short Squeeze"
    override val regimeShortSqueezeDesc: String = "Forti posizioni short sono intrappolate. Un lieve rialzo potrebbe innescare liquidazioni a cascata e rapidi picchi."
    override val regimeSpotAccumulationTitle: String = "Accumulazione Spot"
    override val regimeSpotAccumulationDesc: String = "Assorbimento reale di acquisti spot anziché leva rischiosa. Segnala una struttura di mercato sana e sostenibile."
    override val regimeBalancedConsolidationTitle: String = "Consolidamento Equilibrato"
    override val regimeBalancedConsolidationDesc: String = "La leva sui derivati e la domanda spot sono in equilibrio, indicando trading in congestione."
    override val marketIntelligenceTelemetryHeader: String = "Telemetria Chiave"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Capitale totale bloccato in contratti derivati attivi."
    override val telemetryFundingRateTitle: String = "Funding Rate"
    override val telemetryFundingRateDesc: String = "Commissione periodica tra long e short. Tassi fortemente positivi avvisano di posizioni long troppo esposte e vulnerabili."
    override val marketIntelligenceUnderstood: String = "Ho capito"
}
