package com.example.util

import com.example.data.model.AppLanguage

class SpanishAppStrings : AppStrings(AppLanguage.SPANISH) {
    // Navigation & Core
    override val navMarkets: String = "Ciclo"
    override val navCoins: String = "Monedas"
    override val navFutures: String = "Futuros"
    override val navSignals: String = "Cinta"
    override val navSettings: String = "Ajustes"
    override val navMacro: String = "Macro"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO ACTIVO"
    override val backToFree: String = "Volver a Free"
    override val upgradeToPro: String = "Mejorar a Pro"
    override val proRequired: String = "Requiere Pro"
    override val searchPlaceholder: String = "Buscar 100+ criptomonedas..."
    override val cryptocurrenciesCount: String = "CRIPTOMONEDAS"
    override val cryptocurrencySingular: String = "CRIPTOMONEDA"
    override val turboEngineActive: String = "Motor Turbo Activo"
    override val rankPrefix: String = "Rango"
    override val closeButton: String = "Cerrar"
    override val institutionalTerminal: String = "Terminal de Ciclos y Derivados"
    override val trustBarFeed: String = "Feed Institucional: Libro de Órdenes Directo"
    override val latencyMs: String = "%dms latencia"
    override val realtimeFeed: String = "FEED EN VIVO"
    override val neutralPhase: String = "Fase Neutral"
    override val avg7d: String = "Prom. 7D"
    override val avg30d: String = "Prom. 30D"
    override val daysHigh: String = "d máx"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Capa 1"
    override val catLayer2: String = "Capa 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "IA & Infra"
    override val catMeme: String = "Memes"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Utilidad"
    override val catFavorites: String = "Favoritos"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Resumen del Mercado"
    override val marketsHeadline: String = "100+ Activos del Mundo Real & Planos de Ciclos"
    override val marketsSubtitle: String = "Hacia dónde se mueve cada cripto, patrones históricos, proyecciones futuras & whitepapers."
    override val fromAth: String = "desde el ATH"
    override val tapForCycleAnalog: String = "Toca para ver análogo de ciclo, proyecciones & whitepaper"
    override val heroSubtitle: String = "ANÁLOGO HISTÓRICO DEL CICLO"
    override val currentPrice: String = "Precio Actual"
    override val analogMatch: String = "Coincidencia Histórica"
    override val cyclePhase: String = "Fase del Ciclo"
    override val daysSinceAth: String = "Días desde el ATH"
    override val tapToViewCycles: String = "Toca para explorar ciclos & whitepaper"

    // Markets Screen Teaser Cards
    override val marketsOrderFlowTeaserTitle: String = "Flujo de Órdenes & Profundidad Futures"
    override val marketsOrderFlowTeaserSummary: String = "Funding · OI · Liquidaciones 24h"
    override val marketsOrderFlowTeaserLocked: String = "Bloqueado"
    override val marketsOrderFlowTeaserLockedDesc: String = "Desbloquea el flujo de apalancamiento y liquidaciones en vivo"
    override val marketsOrderFlowTeaserUnlockedDesc: String = "Escalera DOM en vivo & Libro de órdenes"
    override val marketsOrderFlowTeaserUpgrade: String = "Mejorar →"
    override val marketsOrderFlowTeaserOpenFutures: String = "Abrir Futuros →"
    override val marketsSignalsTeaserTitle: String = "Radar de Ballenas & Señales Fractales"
    override val marketsSignalsTeaserLiveTag: String = "FEED EN VIVO"
    override val marketsSignalsTeaserSample: String = "BTC: $148M acumulación neta en Coinbase Prime"
    override val marketsSignalsTeaserAccumulationTag: String = "ACUMULACIÓN"
    override val marketsSignalsTeaserSub: String = "Mapas de liquidación & fractales de ciclos 2016/2020"
    override val marketsSignalsTeaserOpen: String = "Abrir pestaña Señales →"
    override val marketsMacroTeaserNextEvent: String = "Próximo Evento: Empleo EE.UU. (NFP) Viernes 15:30 UTC"
    override val marketsMacroTeaserOpen: String = "Abrir Macro →"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "ANÁLOGO HISTÓRICO DEL CICLO"
    override val historicalAnalogProUnlockedTitle: String = "Análisis de Ciclo Pro Desbloqueado"
    override val historicalAnalogProTitle: String = "Análogo Histórico del Ciclo"
    override val historicalAnalogProUnlockedDesc: String = "El historial en vivo y los movimientos realizados están activos."
    override val historicalAnalogProDesc: String = "Desbloquea gráficos de historial en vivo y tarjetas de movimientos realizados."
    override val historicalAnalogManagePro: String = "Gestionar Pro"
    override val historicalAnalogProPrice: String = "Desbloquear Pro (2,99 €/mes)"
    override val movementAnalysisHeader: String = "ANÁLISIS DE MOVIMIENTO & HISTORIA DEL CICLO"
    override val whereItMovesNowLabel: String = "Hacia dónde se mueve ahora:"
    override val whereItMovedPastLabel: String = "Hacia dónde se movió en ciclos anteriores:"
    override val nextMoveHeader: String = "MOVIMIENTOS LIVE REALIZADOS"
    override val cycleFractalLabel: String = "Día Fractal del Ciclo"
    override val historicalMatchLabel: String = "Cómo se movió el precio de un halving al siguiente"
    override val target1w: String = "1 Semana"
    override val target2w: String = "2 Semanas"
    override val target4w: String = "4 Semanas"
    override val strategyGuideTitle: String = "📖 Guía de Estrategia: Cuándo Comprar & Vender"
    override val buyMomentTitle: String = "🟢 Suelo histórico Pi Cycle"
    override val buyMomentRules: String = "1. Cuando el precio de Bitcoin toca o se acerca al Suelo 200W MA (<15% de brecha). Esto marca suelos históricos de ciclo.\n2. Cuando 111 DMA está muy por debajo (>40%) de 350 DMA x 2. Mínimo riesgo bajista con máxima recompensa (DCA In)."
    override val sellMomentTitle: String = "🔴 Cuándo es el mejor momento para VENDER (Techo de Ciclo)"
    override val sellMomentRules: String = "1. Cuando 111 DMA cruza por encima de 350 DMA x 2. Señala alta probabilidad de techo de ciclo.\n2. Cuando Rainbow Chart entra en las zonas rojas de 'Burbuja Máxima'. Los datos históricos muestran caídas masivas posteriores (90%+ en alts)."
    override val rainbowFeatureLabel: String = "🌈 Bitcoin Rainbow Chart (Modelo Dinámico Power Law)"
    override val altSeasonFeatureLabel: String = "⚡ Índice Altcoin Season (0-100) & Top 50 Superiores"
    override val piCycleFeatureLabel: String = "🎯 Indicador Pi Cycle Top & Suelo 200W MA (cruces históricos)"
    override val fearGreedFeatureLabel: String = "😱 Análisis Multi-Temporal de Sentimiento Fear & Greed"
    override val proAnalyticsTitle: String = "Análisis de Ciclo Pro"
    override val proAnalyticsDesc: String = "Desbloquea las líneas 2016 y 2020 en el mismo día de ciclo para"
    override val proAnalyticsButton: String = "Desbloquear Pro (2,99 €/mes)"
    override val projectedPeakLabel: String = "ATH"
    override val projectedBottomLabel: String = "ATL"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "ESTADÍSTICAS DE MERCADO & SUMINISTRO DE TOKENS"
    override val circulatingSupplyLabel: String = "Suministro Circulante:"
    override val circulatingShort: String = "Circulante"
    override val infiniteDeflationary: String = "Infinito (Deflacionario)"
    override val marketCapMetric: String = "CAPITALIZACIÓN"
    override val volume24hMetric: String = "VOLUMEN 24H"
    override val tradingVolumeSub: String = "Volumen de negociación"
    override val fdvMetric: String = "FDV (VALORACIÓN)"
    override val fdvSub: String = "Valoración totalmente diluida"
    override val athMetric: String = "MÁXIMO HISTÓRICO (ATH)"
    override val atlMetric: String = "MÍNIMO HISTÓRICO (ATL)"
    override val drawdownAthMetric: String = "CAÍDA DESDE ATH"
    override val fromPeakSub: String = "Desde el pico"
    override val allTimeLowMetric: String = "Mínimo histórico"
    override val allTimeHighMetric: String = "Máximo histórico"
    override val startMetric: String = "Inicio"
    override val liveYearsMetric: String = "6443d · 17.64 años activo"
    override val daysSinceHighMetric: String = "Días desde el máximo"
    override val dropFromHighMetric: String = "-36.0% caída desde el máximo"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & PLAN TECNOLÓGICO"
    override val founderLabel: String = "CREADOR / FUNDADOR"
    override val genesisDateLabel: String = "FECHA DE GÉNESIS"
    override val whatCoinDoesLabel: String = "Qué hace la cripto (Core Whitepaper Blueprint)"
    override val consensusLabel: String = "Mecanismo de Consenso & Arquitectura"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Emisión"
    override val useCasesLabel: String = "Casos de Uso Principales del Ecosistema"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Semanas desde el máximo"
    override val weekOfFallSub: String = "semana 46 · típicamente 16 sem."
    override val cycleAnalysisHeader: String = "Análisis del ciclo"
    override val fromHighToLowTitle: String = "DEL MÁXIMO A UN POSIBLE MÍNIMO"
    override val daysAfterAthLabel: String = "días después del máximo histórico"
    override val daysToBottomLabel: String = "días, correcciones pasadas (media)"
    override val highMarker: String = "Alto"
    override val typical383dMarker: String = "típico 383d"
    override val lowMarker: String = "Bajo"
    override val fromHighToLowNarrative: String = "Estamos a 319 días del máximo histórico. Históricamente, del máximo al mínimo pasaron unos 383 días. Faltan unos 64 días para un posible mínimo."
    override val fromHighToLowDetails: String = "06 oct 2025 · \$124,752.53 · -36.0% desde el máximo"
    override val fromHighToLowDisclaimer: String = "Esto es lo que hicieron los ciclos pasados. No es una promesa: solo un reloj."
    override val thisCycleVsLastTitle: String = "ESTE CICLO VS LOS ANTERIORES"
    override val daysAfterHighTitle: String = "Días después del máximo"
    override val daysAfterHighSub: String = "Estamos a 319 días del máximo. Las caídas pasadas al suelo duraron unos 383 días."
    override val nowLabel: String = "Ahora"
    override val daysOfRiseTitle: String = "Días de subida, históricamente"
    override val daysOfRiseSub: String = "Las subidas pasadas desde el suelo al siguiente máximo duraron unos 1059 días."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "días hasta el próximo halving"
    override val halvingHoursLabel: String = "horas restantes"
    override val whatCameNextTitle: String = "Qué ocurrió en días similares de ciclos anteriores"
    override val timeframe1wk: String = "en 1 sem."
    override val timeframe2wk: String = "en 2 sem."
    override val timeframe4wk: String = "en 4 sem."
    override val winRate71: String = "Live 24h"
    override val winRate79: String = "Live sparkline"
    override val winRate86: String = "Desde ATH"
    override val whyWeSayThisTitle: String = "Contexto Histórico y Advertencias del Ciclo"
    override val whyPoint1: String = "Esta semana del ciclo se parece al 28 jun 2018: misma fase, movimiento similar."
    override val whyPoint2: String = "Examinamos 14 semanas similares del pasado. En las 4 semanas siguientes el precio subió 12 de 14 veces (típicamente +29.5%)."
    override val whyPoint3: String = "Estamos en la semana 46 de caída. En el pasado una fase así duró unas 16 semanas."
    override val whyPoint4: String = "Tanto la posición del ciclo como las semanas históricas apuntan a la zona verde."

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Seleccionar Activo"
    override val signalsAllCoins: String = "Todas las 100+ Criptos"
    override val timeframe1D: String = "1D"
    override val timeframe1W: String = "1S"
    override val timeframe1M: String = "1M"
    override val timeframe1Y: String = "1A"
    override val timeframeCycle: String = "Ciclo Macro"
    override val signalBullish: String = "24h ALZA"
    override val signalBearish: String = "24h BAJA"
    override val signalAccumulation: String = "RUPTURA DE ACUMULACIÓN"
    override val signalConfidence: String = "Frecuencia de referencia histórica"
    override val signalLiveFeed: String = "Feed en Vivo CoinGecko • Ticks 1s"
    override val analogComparisonHeader: String = "SUPERPOSICIÓN DE ACCIÓN DE PRECIOS HISTÓRICA"
    override val analogExplanation: String = "Alineación de la acción de precios con fechas de ciclos anteriores. No es una predicción."
    override val highAccuracyNotice: String = "Registro de referencia histórica de backtest"

    // Settings Screen
    override val settingsHeader: String = "Ajustes"
    override val languageTitle: String = "Idioma"
    override val languageDesc: String = "Selecciona tu idioma preferido"
    override val appearanceTitle: String = "Apariencia"
    override val themeGalaxyDark: String = "Galaxy Dark (Predeterminado)"
    override val themeGalaxyDarkSub: String = "Fondo azul profundo OLED con detalles cian"
    override val themePureBlack: String = "Negro Puro"
    override val themePureBlackSub: String = "Modo OLED negro puro para ahorrar batería"
    override val themeCleanWhite: String = "Blanco Limpio"
    override val themeCleanWhiteSub: String = "Tema claro para entornos muy iluminados"
    override val optionsTitle: String = "Opciones"
    override val soundEffectsTitle: String = "Efectos de Sonido Crypto (SFX)"
    override val soundEffectsSub: String = "Retroalimentación háptica en navegación y alertas"
    override val soundTestTitle: String = "Probar Efectos de Sonido"
    override val soundTestLaunch: String = "Escala Mayor Ascendente 🎵"
    override val soundTestClick: String = "Toque Tecnológico"
    override val soundTestToggle: String = "Tono de Interruptor"
    override val soundTestChime: String = "Campanilla de Recompensa"
    override val hideMemecoinsTitle: String = "Ocultar Memecoins"
    override val hideMemecoinsSub: String = "Mostrar solo proyectos fundamentales de alta capitalización"
    override val logChartsTitle: String = "Gráficos Logarítmicos"
    override val logChartsSub: String = "Mostrar precios en escala logarítmica"
    override val proMembershipTitle: String = "Suscripción Pro"
    override val proMembershipPrice: String = "2,99 € / mes · 24,99 € / año"
    override val manageProSubscription: String = "Gestionar suscripción Pro"
    override val proPriceTrialLine: String = "2,99 € / mes · prueba gratis de 7 días"
    override val proTapeTitle: String = "LECTURA DE CINTA PRO"
    override val proTapeDesc: String = "Desbloquea la lectura en vivo de RSI, EMA, ATR, funding y ETF desde cierres diarios. No es una previsión."
    override val proBenefit1: String = "Líneas 2016 y 2020 en el mismo día de ciclo"
    override val proBenefit2: String = "Registro diario de los números en vivo que mostró la app"
    override val proBenefit3: String = "Alerta opcional del día de ciclo que abre el gráfico"
    override val proBenefit4: String = "Cinta en vivo de cierres, funding y ETF — no es una previsión"
    override val proBenefit5: String = "IA que solo lee la instantánea en pantalla"
    override val proBenefit6: String = "Lecciones extra sobre apalancamiento, funding y el libro — sin orden de trade"
    override val currencyDisplayTitle: String = "Moneda de Visualización"
    override val howWeReadItTitle: String = "Cómo lo leemos — en palabras sencillas"
    override val plainItem1Title: String = "1. La historia se repite en ciclos"
    override val plainItem1Desc: String = "Las criptos siguen ciclos de halving de 4 años. Alineamos la marcha actual con 2020 y 2016."
    override val plainItem2Title: String = "2. Análogos Históricos"
    override val plainItem2Desc: String = "La curva naranja muestra 2020; la cian 2016. La línea blanca es tu trayectoria actual."
    override val plainItem3Title: String = "3. Zonas Históricas del Ciclo"
    override val plainItem3Desc: String = "Mediante regresión logarítmica calculamos zonas históricas con fines de estudio. Todas las herramientas son educativas y no constituyen asesoramiento financiero."
    override val plainItem4Title: String = "4. Whitepapers Fundamentales"
    override val plainItem4Desc: String = "Cada ficha incluye modelo de consenso, tokenomics, fundadores y casos de uso reales."
    override val plainItem5Title: String = "5. Advertencia sobre Riesgos"
    override val plainItem5Desc: String = "Las rentabilidades pasadas no garantizan resultados futuros. Invierte con prudencia."
    override val privacyPolicyTitle: String = "Términos de Uso y Política de Privacidad"
    override val privacyPolicyView: String = "Consulta nuestra política de privacidad y almacenamiento de datos"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Pagas las líneas 2016/2020, el registro, la alerta del día, la cinta en vivo y las lecciones extra. Precio, cap, Fear & Greed y ETF 1 día siguen gratis. No es una previsión."
    override val proModalFeature1: String = "Líneas 2016 y 2020 en el mismo día de ciclo"
    override val proModalFeature2: String = "Registro diario de los números en vivo que mostró la app"
    override val proModalFeature3: String = "Alerta opcional del día de ciclo que abre el gráfico"
    override val proModalFeature4: String = "Cinta en vivo de cierres, funding y ETF — no es una previsión"
    override val proModalFeature5: String = "IA que solo lee la instantánea en pantalla"
    override val proModalFeature6: String = "Lecciones extra sobre apalancamiento, funding y el libro — sin orden de trade"
    override val planMonthlyTitle: String = "Mensual"
    override val planMonthlyPrice: String = "2,99 €"
    override val planMonthlyPeriod: String = "/ mes"
    override val planMonthlyBadge: String = "Prueba gratuita 7 días"
    override val planAnnualTitle: String = "Anual"
    override val planAnnualPrice: String = "24,99 €"
    override val planAnnualPeriod: String = "/ año"
    override val planAnnualBadge: String = "~2,08 €/mes · unos 3 meses de regalo"
    override val subscribeProBtn: String = "Comenzar prueba gratuita de 7 días"
    override val startFreeTrialBtn: String = "Comenzar prueba gratuita de 7 días"
    override val startFreeTrialSub: String = "7 días gratis, luego 2,99 € / mes. Cancela en cualquier momento."
    override val continueYearlyBtn: String = "Continuar con Anual (24,99 €/año)"
    override val continueYearlySub: String = "Acceso Pro Inmediato • 24,99 € facturado anualmente (~2,08 €/mes)"
    override val restorePurchases: String = "Restaurar Compras"
    override val restoringPurchases: String = "Verificando compras en Google Play..."
    override val cancelAnytime: String = "Cancela cuando quieras en Google Play"
    override val playTermsDisclosure: String = "El pago se cargará a tu cuenta de Google Play tras confirmar la compra. La suscripción se renueva automáticamente a menos que se cancele al menos 24 horas antes del vencimiento."
    override val financialDisclaimerTitle: String = "Descargo Financiero y Regulatorio"
    override val financialDisclaimerText: String = "Historia educativa de ciclos pasados. No es un pronóstico ni un consejo. CryptoCycles no es un exchange, no custodia fondos y no dice que compres o vendas."
    override val privacySheetTitle: String = "Privacidad CryptoCycles"
    override val privacyLastUpdated: String = "Última actualización: 2026"
    override val privSection1Title: String = "1. Recopilación de Datos"
    override val privSection1Body: String = "Las señales y ventanas de compra/venta son patrones históricos y no constituyen asesoramiento financiero."
    override val privSection2Title: String = "2. Menores"
    override val privSection2Body: String = "CryptoCycles no está dirigida a menores de 13 años."
    override val privSection3Title: String = "3. Contacto"
    override val privSection3Body: String = "Para dudas de privacidad, usa el correo de contacto en Google Play."
    override val privSection4Title: String = "4. Almacenamiento Local"
    override val privSection4Body: String = "CryptoCycles no crea cuentas de usuario ni vende datos personales. Todas tus preferencias quedan guardadas en tu dispositivo."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO líneas de ciclo y lectura de cinta"
    override val signalsProLockedSubtitle: String = "Desbloquea las superposiciones 2016 y 2020 y la lectura de cierres diarios. No es una previsión."
    override val signalsProLockedFeature1: String = "Líneas 2016 y 2020 en el mismo día de ciclo"
    override val signalsProLockedFeature2: String = "Lectura en vivo (RSI, EMA, ATR de cierres diarios)"
    override val signalsProLockedFeature3: String = "Registro diario de lo que mostró la app"
    override val signalsProLockedFeature4: String = "Historia educativa. No es una previsión ni un consejo."
    override val signalsGateTitle: String = "Superposiciones de ciclo y lectura de cinta"
    override val signalsGateDesc: String = "Desbloquea las líneas 2016 y 2020 y la lectura en vivo de cierres diarios. No es una señal ni una previsión."
    override val signalsGateBadge: String = "Cierres en vivo · funding en vivo · ETF en vivo"

    // Zone Playbook Strings
    override val zonePlaybookTitle: String = "PLAYBOOK DE ZONAS DEL CICLO"
    override val zonePlaybookSub: String = "Guía educativa de gestión de riesgo según zonas macro"
    override val zoneGreenAction: String = "Zona Verde • Entrada Progresiva (Acumular)"
    override val zoneGreenDesc: String = "Relación riesgo/recompensa históricamente favorable. Dollar-cost averaging sistemático en activos clave."
    override val zoneYellowAction: String = "Zona Amarilla • Mantener & Reequilibrar"
    override val zoneYellowDesc: String = "Zona de valoración de medio ciclo. Mantener posiciones existentes, evitar compras por impulso."
    override val zoneRedAction: String = "Zona Roja • Salida Progresiva (Reducir Riesgo)"
    override val zoneRedDesc: String = "Zona de valoración sobrecomprada. Históricamente prudente tomar beneficios parciales y asegurar capital."
    override val zonePlaybookDisclaimer: String = "Con fines de estudio y educativos únicamente. No constituye asesoramiento financiero."

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "INFORME MACRO SEMANAL"
    override val weeklyBriefingSub: String = "Síntesis institucional semanal del ciclo & postura de riesgo"
    override val weeklyBriefingCurrentZone: String = "Zona Macro Actual"
    override val weeklyBriefingActionTitle: String = "Postura Recomendada"
    override val weeklyBriefingActionAccumulate: String = "ACUMULAR"
    override val weeklyBriefingActionHold: String = "MANTENER"
    override val weeklyBriefingActionReduce: String = "REDUCIR"
    override val weeklyBriefingReasonTitle: String = "Síntesis en 3 Puntos"
    override val weeklyBriefingLine1: String = "1. Las métricas de valoración macro permanecen en el corredor inferior de acumulación."
    override val weeklyBriefingLine2: String = "2. El suelo 200W SMA y la dinámica de oferta del halving siguen ofreciendo respaldo estructural a largo plazo."
    override val weeklyBriefingLine3: String = "3. La acumulación en carteras on-chain indica una absorción constante durante fases de consolidación."
    override val weeklyBriefingProUnlockText: String = "Desbloquea el Informe Semanal institucional, el playbook de zonas y análogos macro con Pro."

    // Historical Analog Card Strings
    override val historicalAnalogCardTitle: String = "ANÁLOGO HISTÓRICO DEL CICLO"
    override val historicalAnalogPhaseText: String = "Estamos en la misma fase de ciclo que el %s."
    override val historicalAnalogFollowThrough: String = "Tras ese punto, el movimiento típico fue: 30d: %s • 90d: %s • 180d: %s"
    override val historicalAnalogNotFinancialAdvice: String = "Modelo educativo basado en la historia fractal de 2016 & 2020. No es asesoramiento financiero."
    override val historicalAnalogProUnlockText: String = "Desbloquea las líneas 2016 y 2020 en el mismo día de ciclo. Solo historia."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Alertas Push de Ciclos & Indicadores"
    override val alertSettingsSub: String = "Notificaciones instantáneas en el dispositivo para umbrales críticos del ciclo de mercado"
    override val alertZoneChangeTitle: String = "Alerta de Cambio de Zona"
    override val alertZoneChangeDesc: String = "Aviso cuando Bitcoin pasa entre las zonas Verde, Amarilla y Roja"
    override val alertPiCycleTitle: String = "Brecha & Cruce de Pi Cycle Top"
    override val alertPiCycleDesc: String = "Aviso cuando la brecha entre 111DMA y 350DMA x 2 se estrecha o cruza"
    override val alertRainbowTitle: String = "Transición de Banda Rainbow"
    override val alertRainbowDesc: String = "Aviso cuando Bitcoin cambia entre bandas de valoración de Rainbow"
    override val alert200WTitle: String = "Distancia a 200-Week SMA"
    override val alert200WDesc: String = "Aviso cuando el precio se acerca o desvía significativamente de 200W SMA"
    override val alertFreeLimitNotice: String = "La versión gratuita incluye hasta 2 alertas activas. Mejora a Pro para alertas ilimitadas."
    override val alertProUnlockNotice: String = "Función PRO: Alertas push ilimitadas para ciclos, Pi Cycle y Rainbow."

    // Widget Strings
    override val widgetSettingsTitle: String = "Widget de Pantalla de Inicio"
    override val widgetSettingsDesc: String = "Muestra la zona actual del ciclo, el precio de BTC y días desde el ATH en tu pantalla de inicio"
    override val widgetZoneLabel: String = "Zona"
    override val widgetBtcPriceLabel: String = "Precio BTC"
    override val widgetDaysSinceAthLabel: String = "Días Desde ATH"

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "GRANDES PRINTS BINANCE USDT-M (PRO)"
    override val whaleRadarSub: String = "Prints de futuros Binance USDT-M desde $100k. No son transferencias on-chain."
    override val whaleNotificationsTitle: String = "Notificaciones Push Alerta de Ballenas"
    override val whaleNotificationsDesc: String = "Recibe alertas instantáneas ante compras masivas de ballenas o ventas en exchanges."
    override val whaleNotificationsProLockedDesc: String = "Pro: aviso cuando un print Binance USDT-M supera el filtro. No son transferencias on-chain."
    override val whaleThresholdTitle: String = "Tamaño Mínimo de Alerta Ballena"
    override val whaleFilterAll: String = "Todas las Ballenas"
    override val whaleFilterInflow: String = "🔻 Grandes ventas"
    override val whaleFilterOutflow: String = "🟢 Acumulación"
    override val whaleFilterBuy: String = "🔺 Grandes compras"
    override val whaleCollapse: String = "Colapsar"
    override val whaleViewAll: String = "Ver todas (%d)"
    override val timeJustNow: String = "Justo ahora"
    override val timeMinsAgo: String = "hace %d min"
    override val timeHoursAgo: String = "hace %d h"
    override val liveOrderFlowTitle: String = "24/7 LIVE FLUJO DE ÓRDENES (BINANCE)"
    override val liveOrderFlowSub: String = "Grandes prints Binance USDT-M de los majors: presión compra vs venta"
    override val buyDominanceLabel: String = "PRESIÓN DE COMPRA"
    override val sellDominanceLabel: String = "PRESIÓN DE VENTA"
    override val netVolumeDelta: String = "FLUJO NETO 24H"
    override val liveExecutionFeed: String = "EJECUCIONES EN VIVO"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Índices Macro & Ciclos"
    override val macroScreenSubtitle: String = "Modelos institucionales de valoración, Rainbow power law & sentimiento de mercado"
    override val macroUpdated4m: String = "Actualizado hace 4 min"
    override val macroProLockedTitle: String = "Herramientas PRO de historia de ciclo"
    override val macroProLockedSubtitle: String = "Desbloquea bandas Rainbow, cruces Pi Cycle y el briefing semanal de hechos. No es una señal de compra o venta."
    override val macroGateTitle: String = "Herramientas de historia de ciclo"
    override val macroGateDesc: String = "Bandas Rainbow, cruces Pi Cycle y hechos semanales. Solo historia — no es un trade."

    // Macro Filters
    override val macroFilterAll: String = "Todos los Índices"
    override val macroFilterEconomicCalendar: String = "📅 Calendario NFP & CPI"
    override val macroFilterRiskBackdrop: String = "🌐 DXY, 10Y & FedWatch"
    override val macroFilterRainbow: String = "🌈 Rainbow Chart"
    override val macroFilterAltSeason: String = "⚡ Alt Season"
    override val macroFilterFearGreed: String = "😱 Fear & Greed"
    override val macroFilterPiCycle: String = "🎯 Pi Cycle & 200W"

    // Macro Economic Calendar & Risk Cards
    override val macroEconomicCalendarCardTitle: String = "📅 Datos Económicos & NFP / CPI"
    override val macroEconomicCalendarCardSub: String = "Próximo: Empleo EE.UU. (NFP) Viernes 15:30 UTC"
    override val macroNfpFridayBadge: String = "NFP VIERNES"
    override val macroRiskBackdropCardTitle: String = "🌐 DXY, Rendimientos 10Y & FedWatch"
    override val macroRiskBackdropCardSub: String = "Liquidez Mundial en USD & Rendimientos Soberanos"
    override val macroRiskBackdropBadge: String = "MARCO MACRO"
    override val macroRainbowCardTitle: String = "🌈 Modelo de Precio Bitcoin Rainbow"
    override val macroRainbowCardSub: String = "Bandas de Valoración Logarítmicas"
    override val macroRainbowBadge: String = "HISTORIA"
    override val macroAltSeasonCardTitle: String = "⚡ Índice Altcoin Season"
    override val macroAltSeasonCardSub: String = "42/100 · Zona Neutral (Bitcoin Season)"
    override val macroFearGreedCardTitle: String = "😱 Índice Fear & Greed"
    override val macroFearGreedCardSub: String = "68/100 · Sentimiento de Codicia"

    override val macroUsJobsTitle: String = "Empleo EE.UU.: Non-Farm Payrolls (NFP)"
    override val macroUsJobsTime: String = "Viernes 15:30 UTC"
    override val macroCpiTitle: String = "Índice de Precios al Consumidor EE.UU. (CPI)"
    override val macroCpiTime: String = "Próximo Mié 13:30 UTC"
    override val macroForecastLabel: String = "Previsión"
    override val macroPreviousLabel: String = "Previo"
    override val macroVolatilityLabel: String = "Volatilidad"
    override val macroConsensusYoyLabel: String = "Consenso YoY"
    override val macroPriorYoyLabel: String = "Previo YoY"
    override val macroProOnly: String = "🔒 Solo Pro"
    override val macroProHigh: String = "🔒 Alta"
    override val macroProLockedBadge: String = "🔒 Pro Bloqueado"

    override val macroFedWatchTitle: String = "CME FedWatch: Probabilidad de Bajada de Tipos"
    override val macroDxyTitle: String = "DXY: Índice del Dólar Estadounidense"
    override val macroUs10yTitle: String = "US 10Y: Rendimiento del Bono del Tesoro de EE.UU. a 10 años"
    override val macroBrentTitle: String = "Petróleo Crudo Brent"

    // Rainbow Chart Strings
    override val rainbowHeaderTitle: String = "Bitcoin Rainbow Chart"
    override val rainbowHeaderSubtitle: String = "Gráfico Dinámico Rainbow"
    override val rainbowFormulaTag: String = "Power Law Dinámico (Ajuste R² 94.3%)"
    override val rainbowDescription: String = "Modelo dinámico de regresión logarítmica Power Law que se ajusta a toda la historia de precios de Bitcoin desde 2012."
    override val rainbowCurrentBandLabel: String = "Banda de Valoración Actual"
    override val rainbowCyclePeakTarget: String = "Objetivo Techo de Ciclo"
    override val rainbowFireSaleTarget: String = "Suelo de Liquidación (Fire Sale)"
    override val rainbowFilterAll: String = "Todas las Bandas"
    override val rainbowInspectHelp: String = "Toca y arrastra en el gráfico para inspeccionar precios & bandas históricas"
    override val halvingVerticalLabel: String = "Halving"
    override val halving2032Est: String = "Halving 2032 (Estimado)"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Índice Altcoin Season"
    override val altSeasonSubtitle: String = "75% del Top 50 de criptos superando a Bitcoin en 90 días"
    override val altSeasonScoreLabel: String = "Puntuación Altcoin Season"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Zona Neutral"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val altSeasonOutperformedCount: String = "%d de %d criptos superaron a BTC"
    override val topPerformers90d: String = "Top 90D Superiores vs BTC"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Índice Fear & Greed"
    override val fearGreedSubtitle: String = "Sentimiento del mercado, euforia & reloj de acumulación"
    override val fearGreedNow: String = "Hoy"
    override val fearGreedYesterday: String = "Ayer"
    override val fearGreedLastWeek: String = "Semana Pasada"
    override val fearGreedLastMonth: String = "Mes Pasado"
    override val extremeFearLabel: String = "Miedo Extremo"
    override val fearLabel: String = "Miedo"
    override val neutralLabel: String = "Neutral"
    override val greedLabel: String = "Codicia"
    override val extremeGreedLabel: String = "Codicia Extrema"
    override val fearGreedAccumulationTip: String = "Lectura de sentimiento en vivo. Si falta el número, se muestra un guion. No es una orden de compra o venta."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Indicadores Pi Cycle (Techo & Suelo)"
    override val piCycleSubtitle: String = "Techo (111SMA vs 350SMA×2) & Suelo (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (CRUCE HISTÓRICO)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BOTTOM (CRUCE HISTÓRICO)"
    override val piCycleDma111: String = "SMA 111 Días"
    override val piCycleDma350x2: String = "SMA 350 Días × 2 (Umbral de Techo)"
    override val piCycleEma150: String = "EMA 150 Días"
    override val piCycleSma471x0745: String = "SMA 471 Días × 0.745 (Umbral de Suelo)"
    override val piCycleMa200w: String = "Suelo SMA 200 Semanas"
    override val piCycleDistanceToCross: String = "Distancia al Cruce Pi Top"
    override val piCycleDistanceToBottomCross: String = "Distancia al Cruce de Suelo"
    override val piCycleStatusSafeText: String = "Fase de Acumulación & Expansión (Zona Segura)"
    override val piCycleStatusAlertText: String = "🚨 CRUCE PI CYCLE TOP DETECTADO (Riesgo de Techo de Ciclo)"
    override val piCycleBottomStatusSafeText: String = "Por encima del Suelo Histórico (Fase de Expansión)"
    override val piCycleBottomStatusAlertText: String = "🚨 CRUCE PI CYCLE BOTTOM DETECTADO (suelo histórico)"
    override val piCycleGenerationalSupport: String = "Soporte Histórico Generacional"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "TERMINAL DE FUTUROS"
    override val futuresOfficialFeedsSub: String = "Feeds oficiales Binance USDT-M · Cero datos simulados"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "OBSOLETO"
    override val futuresStateOffline: String = "OFFLINE"
    override val futuresStateUnavailable: String = "NO DISPONIBLE"
    override val futuresLastMarkIndexTitle: String = "PRECIOS ÚLTIMO / MARK / INDEX"
    override val futuresLastTradedPrice: String = "Último Precio Negociado"
    override val futuresMarkPrice: String = "Precio Mark"
    override val futuresIndexPrice: String = "Precio Index"
    override val futuresBasis: String = "Base (Mark - Index)"
    override val futuresHigh24h: String = "Máximo 24h"
    override val futuresLow24h: String = "Mínimo 24h"
    override val futuresVolume24h: String = "Volumen 24h (USDT)"
    override val futuresBboSpreadTitle: String = "MEJOR OFERTA / DEMANDA (BBO) & SPREAD"
    override val futuresBestBid: String = "MEJOR OFERTA (BID)"
    override val futuresBestAsk: String = "MEJOR DEMANDA (ASK)"
    override val futuresOrderbookSpread: String = "Spread del libro de órdenes:"
    override val futuresPerpFundingTitle: String = "TASA DE FINANCIACIÓN & CUENTA REGRESIVA"
    override val futuresCurrentFundingRate: String = "Tasa de Financiación Actual"
    override val futuresNextFundingIn: String = "Próxima Liquidación en"
    override val futuresApproxAprLabel: String = "APR Estimado (tasa × 3 × 365):"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (ACTUALIZADO 15S)"
    override val futuresContracts: String = "contratos"
    override val futuresNoOpenInterest: String = "Sin datos de open interest"
    override val futuresFearGreed5m: String = "Miedo & Codicia (5m)"
    override val futuresBtcDominance60s: String = "Dominancia BTC (60s)"
    override val futuresLiquidationsTapeTitle: String = "🚨 Órdenes Forzadas Binance (Liquidaciones)"
    override val futuresLiquidationsListening: String = "Escuchando flujo de liquidaciones Binance en vivo..."
    override val futuresCaptured: String = "capturadas"
    override val futuresLongLiq: String = "LIQUIDACIÓN LONG (VENTA)"
    override val futuresShortLiq: String = "LIQUIDACIÓN SHORT (COMPRA)"
    override val futuresTradesTapeTitle: String = "⚡ CINTA DE OPERACIONES EN TIEMPO REAL"
    override val futuresTradesAwaiting: String = "Esperando flujo de operaciones..."
    override val futuresPriceHeader: String = "Precio (USDT)"
    override val futuresQtyHeader: String = "Cant"
    override val futuresTimeHeader: String = "Hora"
    override val futuresLockedTitle: String = "Par de Futuros Pro Bloqueado"
    override val futuresLockedDesc: String = "%s (%s) forma parte del nivel Pro. Desbloquea el libro de órdenes completo, arbitraje de base y datos de perpetuals."
    override val futuresLockedButton: String = "Desbloquear Acceso Pro"
    override val futuresProPair: String = "Par Pro"
    override val futuresSizePrefix: String = "Tamaño:"

    // Structured 3-Line Metric Explainers (Headers & Micro-copy)
    override val explainerWhatItIsLabel: String = "Qué es: "
    override val explainerWhatItShowsLabel: String = "Qué muestra: "
    override val explainerNotASignalLabel: String = "Qué no significa: "

    // Macro Metric Explainers
    override val explainerNfpWhat: String = "Variación mensual del empleo en EE.UU. excluyendo el sector agrícola, reportada por la Oficina de Estadísticas Laborales."
    override val explainerNfpShows: String = "Tensión en el mercado laboral y actividad económica que influyen directamente en las decisiones de tipos de la Fed."
    override val explainerNfpNotMean: String = "Contexto de liquidez macro para tasas de interés, no una señal direccional directa para cripto."

    override val explainerCpiWhat: String = "Métrica clave de inflación que rastrea los cambios promedio de precios en una cesta de bienes y servicios."
    override val explainerCpiShows: String = "Erosión del poder adquisitivo del consumidor y trayectoria hacia el objetivo del 2% de la Fed."
    override val explainerCpiNotMean: String = "Contexto de inflación general, no un activador algorítmico de operaciones."

    override val explainerFedWatchWhat: String = "Probabilidad implícita de bajada de tipos calculada a partir de los futuros de Fondos Federales a 30 días."
    override val explainerFedWatchShows: String = "Expectativas de consenso del mercado sobre la flexibilización de la política de la Reserva Federal."
    override val explainerFedWatchNotMean: String = "Distribución de probabilidad de mercado, no un compromiso de política garantizado del banco central."

    override val explainerDxyWhat: String = "Índice geométricamente ponderado que mide la fortaleza del USD frente a 6 monedas fiduciarias principales."
    override val explainerDxyShows: String = "Condiciones globales de liquidez en dólares, fuga de capitales y poder adquisitivo relativo del dólar."
    override val explainerDxyNotMean: String = "Marea de liquidez macroeconómica, no un factor determinante aislado de suelos o techos en cripto."

    override val explainerUs10yWhat: String = "Rendimiento de interés anual de los títulos de deuda del gobierno de Estados Unidos a 10 años."
    override val explainerUs10yShows: String = "Coste global del capital libre de riesgo y expectativas de crecimiento/inflación a largo plazo."
    override val explainerUs10yNotMean: String = "Tasa de descuento macro para activos de riesgo, no un detonante de ejecución a corto plazo."

    override val explainerBrentWhat: String = "Punto de referencia internacional de precios para contratos físicos de petróleo crudo."
    override val explainerBrentShows: String = "Presiones inflacionarias de materias primas energéticas y actividad industrial global."
    override val explainerBrentNotMean: String = "Componente de índices de inflación, no un impulsor directo del precio de las criptomonedas."

    // Futures Metric Explainers
    override val explainerFundingWhat: String = "Tarifa periódica intercambiada entre compradores (longs) y vendedores (shorts) en contratos perpetuos."
    override val explainerFundingShows: String = "Concentración de posiciones de los operadores y sesgo de apalancamiento en mercados de derivados."
    override val explainerFundingNotMean: String = "Un sesgo extremo refleja apalancamiento, no una reversión inmediata o garantizada del precio."

    override val explainerOiWhat: String = "Total de posiciones abiertas agregadas y valoración en dólares en contratos perpetuos activos."
    override val explainerOiShows: String = "Flujo neto de entrada o salida de capital de derivados y continua expansión del apalancamiento."
    override val explainerOiNotMean: String = "Medida del compromiso total en derivados, no un resultado direccional sin contexto de precio."

    override val explainerSentimentWhat: String = "Índice de sentimiento (0-100) y cuota de capitalización de mercado de Bitcoin."
    override val explainerSentimentShows: String = "Apetito por el riesgo en el mercado y rotación de capital entre Bitcoin y Altcoins."
    override val explainerSentimentNotMean: String = "Postura macro amplia del mercado, no una señal de ejecución inmediata."

    override val explainerLiqWhat: String = "Liquidaciones forzadas de posiciones ejecutadas al incumplirse el margen de mantenimiento."
    override val explainerLiqShows: String = "Zonas de precios concentradas donde las cuentas sobreapalancadas son cerradas por el exchange."
    override val explainerLiqNotMean: String = "Cascadas de desapalancamiento forzado, no acumulación institucional orgánica direccional."

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "Analista de Mercado IA"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Inteligencia en Tiempo Real de Ciclos, Futuros y Ballenas"
    override val aiPromptPlaceholder: String = "Pregunta sobre ciclo BTC, funding, soporte, altseason..."
    override val aiAskButton: String = "Analizar"
    override val aiQuickActionCycle: String = "Ciclo y Riesgo Halving"
    override val aiQuickActionFutures: String = "Funding y Flujo de Apalancamiento"
    override val aiQuickActionWhales: String = "Acumulación de Ballenas"
    override val aiQuickActionAltseason: String = "Preparación Altseason"
    override val aiDisclaimer: String = "Desarrollado con modelos Gemini AI y telemetría en tiempo real. No es asesoramiento financiero."
    override val aiThinking: String = "Analizando telemetría y libro de órdenes en vivo..."
    override val aiGreeting: String = "Estoy aquí. ¿Qué te gustaría ver?"
    override val aiClearHistory: String = "Limpiar"
    override val aiLiveContextTag: String = "Datos en Vivo Conectados"
    override val aiPromptPrefixCycle: String = "Analiza la fase actual del ciclo halving, el riesgo y los análogos históricos."
    override val aiPromptPrefixFutures: String = "Interpreta las tasas de financiación actuales, el interés abierto y los riesgos de liquidación."
    override val aiPromptPrefixWhales: String = "¿Qué indican las alertas recientes de ballenas sobre acumulación o distribución institucional?"
    override val aiPromptPrefixAltseason: String = "Evalúa si las condiciones del mercado, el dominio de BTC y el sentimiento favorecen una Altseason ahora."
    override val backtestBadgeText: String = "Live whale radar · live order flow · live liquidations"
    override val derivativesRiskGuardrail: String = "Esta pantalla lee la cinta de perpetuos. No es un escritorio de trading y no dimensiona posiciones."

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Capa de Market Intelligence: Cómo Funciona"
    override val marketIntelligenceInfoButton: String = "¿Qué es esto?"
    override val marketIntelligenceConfidenceTitle: String = "Puntuación de Confianza (ej. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Mide la fuerza cuantitativa del posicionamiento actual en futuros según volumen, interés abierto y momentum."
    override val marketIntelligenceRegimesHeader: String = "Regímenes de Mercado (Qué significan las señales)"
    override val regimeShortSqueezeTitle: String = "Presión de Short Squeeze"
    override val regimeShortSqueezeDesc: String = "Fuertes posiciones en corto están atrapadas. Un leve movimiento alcista puede desatar liquidaciones en cascada y subidas bruscas."
    override val regimeSpotAccumulationTitle: String = "Acumulación Spot"
    override val regimeSpotAccumulationDesc: String = "Absorción de compras reales al contado en lugar de apalancamiento riesgoso. Señala una estructura de mercado sana y sostenible."
    override val regimeBalancedConsolidationTitle: String = "Consolidación Equilibrada"
    override val regimeBalancedConsolidationDesc: String = "El apalancamiento en derivados y la demanda al contado están en equilibrio, indicando operativa en rango."
    override val marketIntelligenceTelemetryHeader: String = "Telemetría Clave"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Capital total bloqueado en contratos de derivados activos."
    override val telemetryFundingRateTitle: String = "Funding Rate"
    override val telemetryFundingRateDesc: String = "Comisión periódica entre longs y shorts. Tasas altamente positivas alertan de longs sobreapalancados propensos a caídas."
    override val marketIntelligenceUnderstood: String = "Entendido"
}
