package com.example.util

import com.example.data.model.AppLanguage

class SpanishAppStrings : AppStrings(AppLanguage.SPANISH) {
    // Navigation & Core
    override val navMarkets: String = "Ciclo"
    override val navCoins: String = "Monedas"
    override val navSignals: String = "Cinta"
    override val navSettings: String = "Ajustes"
    override val appTitle: String = "CryptoCycles"
    override val proBadge: String = "Pro"
    override val proActive: String = "PRO ACTIVO"
    override val upgradeToPro: String = "Mejorar a Pro"
    override val searchPlaceholder: String = "Buscar 100+ criptomonedas..."
    override val cryptocurrenciesCount: String = "CRIPTOMONEDAS"
    override val cryptocurrencySingular: String = "CRIPTOMONEDA"
    override val rankPrefix: String = "Rango"
    override val closeButton: String = "Cerrar"
    override val institutionalTerminal: String = "Terminal de Ciclos y Derivados"
    override val latencyMs: String = "%dms latencia"
    override val realtimeFeed: String = "FEED EN VIVO"

    // Coin Categories
    override val catAll: String = "100+"
    override val catLayer1: String = "Capa 1"
    override val catLayer2: String = "Capa 2"
    override val catDefi: String = "DeFi"
    override val catAiInfra: String = "IA & Infra"
    override val catMeme: String = "Memes"
    override val catRwaDepin: String = "RWA & DePIN"
    override val catUtility: String = "Utilidad"
    override val catFavorites: String = "Favoritos"

    // Markets Screen & Teasers
    override val marketsHeader: String = "Resumen del Mercado"
    override val marketsSubtitle: String = "Hacia dónde se mueve cada cripto, patrones históricos, proyecciones futuras & whitepapers."
    override val currentPrice: String = "Precio Actual"
    override val analogMatch: String = "Coincidencia Histórica"
    override val cyclePhase: String = "Fase del Ciclo"
    override val daysSinceAth: String = "Días desde el ATH"

    // Historical Cycle Analog
    override val historicalAnalogHeader: String = "ANÁLOGO HISTÓRICO DEL CICLO"
    override val historicalAnalogProTitle: String = "Análogo Histórico del Ciclo"
    override val historicalAnalogProUnlockedDesc: String = "El historial en vivo y los movimientos realizados están activos."
    override val historicalAnalogProDesc: String = "Desbloquea gráficos de historial en vivo y tarjetas de movimientos realizados."
    override val movementAnalysisHeader: String = "ANÁLISIS DE MOVIMIENTO & HISTORIA DEL CICLO"
    override val nextMoveHeader: String = "MOVIMIENTOS LIVE REALIZADOS"
    override val cycleFractalLabel: String = "Día Fractal del Ciclo"
    override val historicalMatchLabel: String = "Cómo se movió el precio de un halving al siguiente"
    override val proAnalyticsDesc: String = "Desbloquea las líneas 2016 y 2020 en el mismo día de ciclo para"

    // Market Stats & Token Supply
    override val marketStatsHeader: String = "ESTADÍSTICAS DE MERCADO & SUMINISTRO DE TOKENS"
    override val circulatingSupplyLabel: String = "Suministro Circulante:"
    override val circulatingShort: String = "Circulante"
    override val infiniteDeflationary: String = "Infinito (Deflacionario)"
    override val marketCapMetric: String = "CAPITALIZACIÓN"
    override val volume24hMetric: String = "VOLUMEN 24H"
    override val tradingVolumeSub: String = "Volumen de negociación"
    override val fdvMetric: String = "FDV (VALORACIÓN)"
    override val fdvSub: String = "Valoración totalmente diluida"
    override val athMetric: String = "MÁXIMO HISTÓRICO (ATH)"
    override val atlMetric: String = "MÍNIMO HISTÓRICO (ATL)"
    override val drawdownAthMetric: String = "CAÍDA DESDE ATH"
    override val fromPeakSub: String = "Desde el pico"
    override val allTimeLowMetric: String = "Mínimo histórico"
    override val allTimeHighMetric: String = "Máximo histórico"
    override val startMetric: String = "Inicio"
    override val daysSinceHighMetric: String = "Días desde el máximo"

    // Whitepaper & Technology Blueprint
    override val whitepaperSectionHeader: String = "WHITEPAPER & PLAN TECNOLÓGICO"
    override val founderLabel: String = "CREADOR / FUNDADOR"
    override val genesisDateLabel: String = "FECHA DE GÉNESIS"
    override val whatCoinDoesLabel: String = "Qué hace la cripto (Core Whitepaper Blueprint)"
    override val tokenomicsLabel: String = "Tokenomics, Halving & Emisión"
    override val useCasesLabel: String = "Casos de Uso Principales del Ecosistema"

    // Cycle Analysis Deep Dive
    override val weekOfFallTitle: String = "Semanas desde el máximo"
    override val cycleAnalysisHeader: String = "Análisis del ciclo"
    override val fromHighToLowTitle: String = "DEL MÁXIMO A UN POSIBLE MÍNIMO"
    override val daysAfterAthLabel: String = "días después del máximo histórico"
    override val daysToBottomLabel: String = "días, correcciones pasadas (media)"
    override val highMarker: String = "Alto"
    override val fromHighToLowDisclaimer: String = "Esto es lo que hicieron los ciclos pasados. No es una promesa: solo un reloj."
    override val thisCycleVsLastTitle: String = "ESTE CICLO VS LOS ANTERIORES"
    override val daysAfterHighTitle: String = "Días después del máximo"
    override val nowLabel: String = "Ahora"
    override val daysOfRiseTitle: String = "Días de subida, históricamente"
    override val daysOfRiseSub: String = "Las subidas pasadas desde el suelo al siguiente máximo duraron unos 1059 días."
    override val halvingTitle: String = "BITCOIN HALVING"
    override val halvingDaysLabel: String = "días hasta el próximo halving"
    override val halvingHoursLabel: String = "horas restantes"
    override val whyWeSayThisTitle: String = "Contexto Histórico y Advertencias del Ciclo"

    // Signals Screen
    override val signalsCoinSelectorTitle: String = "Seleccionar Activo"
    override val signalsAllCoins: String = "Todas las 100+ Criptos"
    override val timeframe1D: String = "1D"
    override val timeframe1W: String = "1S"
    override val timeframe1M: String = "1M"
    override val timeframe1Y: String = "1A"
    override val timeframeCycle: String = "Ciclo Macro"
    override val signalBullish: String = "24h ALZA"
    override val signalBearish: String = "24h BAJA"

    // Settings Screen
    override val settingsHeader: String = "Ajustes"
    override val languageTitle: String = "Idioma"
    override val languageDesc: String = "Selecciona tu idioma preferido"
    override val optionsTitle: String = "Opciones"
    override val soundEffectsTitle: String = "Efectos de Sonido Crypto (SFX)"
    override val soundEffectsSub: String = "Sonidos cortos al tocar, cambiar y navegar"
    override val soundTestTitle: String = "Probar Efectos de Sonido"
    override val soundTestLaunch: String = "Escala Mayor Ascendente 🎵"
    override val soundTestClick: String = "Toque Tecnológico"
    override val soundTestToggle: String = "Tono de Interruptor"
    override val soundTestChime: String = "Campanilla de Recompensa"
    override val logChartsTitle: String = "Gráficos Logarítmicos"
    override val logChartsSub: String = "Mostrar precios en escala logarítmica"
    override val proMembershipTitle: String = "Suscripción Pro"
    override val manageProSubscription: String = "Gestionar suscripción Pro"
    override val proTapeTitle: String = "LECTURA DE CINTA PRO"
    override val proTapeDesc: String = "Desbloquea la lectura en vivo de RSI, EMA, ATR, funding y ETF desde cierres diarios. No es una previsión."
    override val proBenefit1: String = "Líneas 2016 y 2020 en el mismo día de ciclo"
    override val proBenefit2: String = "Registro diario de los números en vivo que mostró la app"
    override val proBenefit3: String = "Alerta opcional del día de ciclo que abre el gráfico"
    override val proBenefit4: String = "Cinta en vivo de cierres, funding y ETF — no es una previsión"
    override val proBenefit5: String = "IA que solo lee la instantánea en pantalla"
    override val proBenefit6: String = "Lecciones extra sobre apalancamiento, funding y el libro — sin orden de trade"
    override val currencyDisplayTitle: String = "Moneda de Visualización"
    override val howWeReadItTitle: String = "Cómo lo leemos — en palabras sencillas"
    override val plainItem1Title: String = "1. La historia se repite en ciclos"
    override val plainItem1Desc: String = "Las criptos siguen ciclos de halving de unos 4 años. Comparamos hoy con el mismo día tras los halvings de 2012, 2016 y 2020."
    override val plainItem2Title: String = "2. Análogos Históricos"
    override val plainItem2Desc: String = "En el gráfico del ciclo la curva violeta es 2020, la ámbar 2016 y la línea cian el ciclo actual."
    override val plainItem3Title: String = "3. Zonas Históricas del Ciclo"
    override val plainItem3Desc: String = "Mediante regresión logarítmica calculamos zonas históricas con fines de estudio. Todas las herramientas son educativas y no constituyen asesoramiento financiero."
    override val plainItem4Title: String = "4. Whitepapers Fundamentales"
    override val plainItem4Desc: String = "Cada ficha incluye modelo de consenso, tokenomics, fundadores y casos de uso reales."
    override val plainItem5Title: String = "5. Advertencia sobre Riesgos"
    override val plainItem5Desc: String = "Las rentabilidades pasadas no garantizan resultados futuros. Invierte con prudencia."
    override val privacyPolicyTitle: String = "Términos de Uso y Política de Privacidad"
    override val privacyPolicyView: String = "Consulta nuestra política de privacidad y almacenamiento de datos"

    // Pro Modal & Subscriptions
    override val proModalTitle: String = "CryptoCycles Pro"
    override val proModalSubtitle: String = "Pagas las líneas 2016/2020, el registro, la alerta del día, la cinta en vivo y las lecciones extra. Precio, cap, Fear & Greed y ETF 1 día siguen gratis. No es una previsión."
    override val proModalFeature1: String = "Líneas 2016 y 2020 en el mismo día de ciclo"
    override val proModalFeature2: String = "Registro diario de los números en vivo que mostró la app"
    override val proModalFeature3: String = "Alerta opcional del día de ciclo que abre el gráfico"
    override val proModalFeature4: String = "Cinta en vivo de cierres, funding y ETF — no es una previsión"
    override val proModalFeature5: String = "IA que solo lee la instantánea en pantalla"
    override val proModalFeature6: String = "Lecciones extra sobre apalancamiento, funding y el libro — sin orden de trade"
    override val planMonthlyTitle: String = "Mensual"
    override val planMonthlyPeriod: String = "/ mes"
    override val planAnnualTitle: String = "Anual"
    override val planAnnualPeriod: String = "/ año"
    override val restorePurchases: String = "Restaurar Compras"
    override val restoringPurchases: String = "Verificando compras en Google Play..."
    override val playTermsDisclosure: String = "El pago se cargará a tu cuenta de Google Play tras confirmar la compra. La suscripción se renueva automáticamente a menos que se cancele al menos 24 horas antes del vencimiento."
    override val financialDisclaimerTitle: String = "Descargo Financiero y Regulatorio"
    override val financialDisclaimerText: String = "Historia educativa de ciclos pasados. No es un pronóstico ni un consejo. CryptoCycles no es un exchange, no custodia fondos y no dice que compres o vendas."
    override val privacySheetTitle: String = "Privacidad CryptoCycles"
    override val privSection1Title: String = "1. Recopilación de Datos"
    override val privSection1Body: String = "Las señales y ventanas de compra/venta son patrones históricos y no constituyen asesoramiento financiero."
    override val privSection2Title: String = "2. Menores"
    override val privSection2Body: String = "CryptoCycles no está dirigida a menores de 13 años."
    override val privSection3Title: String = "3. Contacto"
    override val privSection3Body: String = "Para dudas de privacidad, usa el correo de contacto en Google Play."
    override val privSection4Title: String = "4. Almacenamiento Local"
    override val privSection4Body: String = "CryptoCycles no crea cuentas de usuario ni vende datos personales. Todas tus preferencias quedan guardadas en tu dispositivo."

    // Signals Pro Locked Banner
    override val signalsProLockedTitle: String = "PRO líneas de ciclo y lectura de cinta"
    override val signalsProLockedSubtitle: String = "Desbloquea las superposiciones 2016 y 2020 y la lectura de cierres diarios. No es una previsión."
    override val signalsProLockedFeature2: String = "Lectura en vivo (RSI, EMA, ATR de cierres diarios)"
    override val signalsProLockedFeature3: String = "Registro diario de lo que mostró la app"
    override val signalsGateTitle: String = "Superposiciones de ciclo y lectura de cinta"
    override val signalsGateDesc: String = "Desbloquea las líneas 2016 y 2020 y la lectura en vivo de cierres diarios. No es una señal ni una previsión."
    override val signalsGateBadge: String = "Cierres en vivo · funding en vivo · ETF en vivo"

    // Weekly Briefing Strings
    override val weeklyBriefingTitle: String = "INFORME MACRO SEMANAL"
    override val weeklyBriefingSub: String = "Síntesis institucional semanal del ciclo & postura de riesgo"
    override val weeklyBriefingCurrentZone: String = "Zona Macro Actual"
    override val weeklyBriefingActionTitle: String = "Postura Recomendada"
    override val weeklyBriefingReasonTitle: String = "Síntesis en 3 Puntos"
    override val weeklyBriefingProUnlockText: String = "Desbloquea el Informe Semanal institucional, el playbook de zonas y análogos macro con Pro."

    override val historicalAnalogProUnlockText: String = "Desbloquea las líneas 2016 y 2020 en el mismo día de ciclo. Solo historia."

    // Push Alerts Settings Strings
    override val alertSettingsHeader: String = "Alertas Push de Ciclos & Indicadores"
    override val alertSettingsSub: String = "Notificaciones instantáneas en el dispositivo para umbrales críticos del ciclo de mercado"
    override val alertZoneChangeTitle: String = "Alerta de Cambio de Zona"
    override val alertZoneChangeDesc: String = "Aviso cuando cambia la zona de ánimo del mercado (Miedo, Neutral, Funding alto, Extremo), según Fear & Greed y funding"
    override val alertPiCycleTitle: String = "Brecha & Cruce de Pi Cycle Top"
    override val alertPiCycleDesc: String = "Aviso cuando la 111DMA queda a menos del 10 % de la 350DMA × 2, la cruza o se aleja. Revisión diaria"
    override val alertRainbowTitle: String = "Transición de Banda Rainbow"
    override val alertRainbowDesc: String = "Aviso cuando Bitcoin cambia entre bandas de valoración de Rainbow"
    override val alert200WTitle: String = "Distancia a 200-Week SMA"
    override val alert200WDesc: String = "Aviso cuando el precio cae bajo la 200W SMA, queda hasta un 10 % por encima o 2,5× por encima. Revisión diaria"
    override val alertFreeLimitNotice: String = "La versión gratuita incluye hasta 2 alertas activas. Mejora a Pro para alertas ilimitadas."
    override val alertProUnlockNotice: String = "Función PRO: Alertas push ilimitadas para ciclos, Pi Cycle y Rainbow."

    // Whale Radar & Live Order Flow
    override val whaleRadarTitle: String = "GRANDES PRINTS BINANCE USDT-M (PRO)"
    override val whaleRadarSub: String = "Prints de futuros Binance USDT-M desde $100k. No son transferencias on-chain."
    override val whaleNotificationsTitle: String = "Notificaciones Push Alerta de Ballenas"
    override val whaleNotificationsDesc: String = "Aviso para una sola operación de futuros Binance USDT-M por encima de tu tamaño, mientras la app está abierta."
    override val whaleNotificationsProLockedDesc: String = "Pro: aviso cuando un print Binance USDT-M supera el filtro. No son transferencias on-chain."
    override val whaleThresholdTitle: String = "Tamaño Mínimo de Alerta Ballena"
    override val whaleFilterAll: String = "Todas las Ballenas"
    override val whaleFilterInflow: String = "🔻 Grandes ventas"
    override val whaleFilterBuy: String = "🔺 Grandes compras"
    override val whaleCollapse: String = "Colapsar"
    override val whaleViewAll: String = "Ver todas (%d)"
    override val timeJustNow: String = "Justo ahora"
    override val timeMinsAgo: String = "hace %d min"
    override val timeHoursAgo: String = "hace %d h"
    override val liveOrderFlowTitle: String = "24/7 LIVE FLUJO DE ÓRDENES (BINANCE)"
    override val liveOrderFlowSub: String = "Grandes prints Binance USDT-M de los majors: presión compra vs venta"
    override val buyDominanceLabel: String = "PRESIÓN DE COMPRA"
    override val sellDominanceLabel: String = "PRESIÓN DE VENTA"
    override val liveExecutionFeed: String = "EJECUCIONES EN VIVO"

    // Macro Screen Strings
    override val macroScreenTitle: String = "Índices Macro & Ciclos"
    override val macroScreenSubtitle: String = "Modelos institucionales de valoración, Rainbow power law & sentimiento de mercado"
    override val macroProLockedTitle: String = "Herramientas PRO de historia de ciclo"
    override val macroProLockedSubtitle: String = "Desbloquea bandas Rainbow, cruces Pi Cycle y el briefing semanal de hechos. No es una señal de compra o venta."
    override val macroGateTitle: String = "Herramientas de historia de ciclo"
    override val macroGateDesc: String = "Bandas Rainbow, cruces Pi Cycle y hechos semanales. Solo historia — no es un trade."

    override val macroRainbowBadge: String = "HISTORIA"

    override val macroProLockedBadge: String = "🔒 Pro Bloqueado"

    // Alt Season Strings
    override val altSeasonHeaderTitle: String = "Índice Altcoin Season"
    override val altSeasonSubtitle: String = "75% del Top 50 de criptos superando a Bitcoin en 90 días"
    override val altSeasonBtcSeasonLabel: String = "Bitcoin Season"
    override val altSeasonNeutralLabel: String = "Zona Neutral"
    override val altSeasonAltSeasonLabel: String = "Altcoin Season"
    override val topPerformers90d: String = "Top 90D Superiores vs BTC"

    // Fear & Greed Strings
    override val fearGreedHeaderTitle: String = "Índice Fear & Greed"
    override val fearGreedSubtitle: String = "Sentimiento del mercado, euforia & reloj de acumulación"
    override val fearGreedYesterday: String = "Ayer"
    override val fearGreedLastWeek: String = "Semana Pasada"
    override val fearGreedLastMonth: String = "Mes Pasado"
    override val extremeFearLabel: String = "Miedo Extremo"
    override val fearLabel: String = "Miedo"
    override val neutralLabel: String = "Neutral"
    override val greedLabel: String = "Codicia"
    override val extremeGreedLabel: String = "Codicia Extrema"
    override val fearGreedAccumulationTip: String = "Lectura de sentimiento en vivo. Si falta el número, se muestra un guion. No es una orden de compra o venta."

    // Pi Cycle Strings
    override val piCycleHeaderTitle: String = "Indicadores Pi Cycle (Techo & Suelo)"
    override val piCycleSubtitle: String = "Techo (111SMA vs 350SMA×2) & Suelo (150EMA vs 471SMA×0.745)"
    override val piCycleTopSectionTitle: String = "🔴 PI CYCLE TOP (CRUCE HISTÓRICO)"
    override val piCycleBottomSectionTitle: String = "🟢 PI CYCLE BOTTOM (CRUCE HISTÓRICO)"
    override val piCycleDma111: String = "SMA 111 Días"
    override val piCycleDma350x2: String = "SMA 350 Días × 2 (Umbral de Techo)"
    override val piCycleEma150: String = "EMA 150 Días"
    override val piCycleSma471x0745: String = "SMA 471 Días × 0.745 (Umbral de Suelo)"
    override val piCycleMa200w: String = "Suelo SMA 200 Semanas"
    override val piCycleStatusSafeText: String = "Fase de Acumulación & Expansión (Zona Segura)"
    override val piCycleStatusAlertText: String = "🚨 CRUCE PI CYCLE TOP DETECTADO (Riesgo de Techo de Ciclo)"
    override val piCycleBottomStatusSafeText: String = "Por encima del Suelo Histórico (Fase de Expansión)"
    override val piCycleBottomStatusAlertText: String = "🚨 CRUCE PI CYCLE BOTTOM DETECTADO (suelo histórico)"

    // Futures Terminal Strings
    override val futuresTerminalTitle: String = "TERMINAL DE FUTUROS"
    override val futuresOfficialFeedsSub: String = "Feeds oficiales Binance USDT-M · Cero datos simulados"
    override val futuresStateLive: String = "LIVE"
    override val futuresStateStale: String = "OBSOLETO"
    override val futuresStateOffline: String = "OFFLINE"
    override val futuresStateUnavailable: String = "NO DISPONIBLE"
    override val futuresLastMarkIndexTitle: String = "PRECIOS ÚLTIMO / MARK / INDEX"
    override val futuresLastTradedPrice: String = "Último Precio Negociado"
    override val futuresMarkPrice: String = "Precio Mark"
    override val futuresIndexPrice: String = "Precio Index"
    override val futuresBasis: String = "Base (Mark - Index)"
    override val futuresHigh24h: String = "Máximo 24h"
    override val futuresLow24h: String = "Mínimo 24h"
    override val futuresVolume24h: String = "Volumen 24h (USDT)"
    override val futuresBboSpreadTitle: String = "MEJOR OFERTA / DEMANDA (BBO) & SPREAD"
    override val futuresBestBid: String = "MEJOR OFERTA (BID)"
    override val futuresBestAsk: String = "MEJOR DEMANDA (ASK)"
    override val futuresOrderbookSpread: String = "Spread del libro de órdenes:"
    override val futuresPerpFundingTitle: String = "TASA DE FINANCIACIÓN & CUENTA REGRESIVA"
    override val futuresCurrentFundingRate: String = "Tasa de Financiación Actual"
    override val futuresNextFundingIn: String = "Próxima Liquidación en"
    override val futuresApproxAprLabel: String = "APR Estimado (tasa × 3 × 365):"
    override val futuresOpenInterestTitle: String = "OPEN INTEREST (ACTUALIZADO 15S)"
    override val futuresContracts: String = "contratos"
    override val futuresLiquidationsListening: String = "Escuchando flujo de liquidaciones Binance en vivo..."
    override val futuresLongLiq: String = "LIQUIDACIÓN LONG (VENTA)"
    override val futuresShortLiq: String = "LIQUIDACIÓN SHORT (COMPRA)"
    override val futuresTradesTapeTitle: String = "⚡ CINTA DE OPERACIONES EN TIEMPO REAL"
    override val futuresTradesAwaiting: String = "Esperando flujo de operaciones..."
    override val futuresPriceHeader: String = "Precio (USDT)"
    override val futuresQtyHeader: String = "Cant"
    override val futuresTimeHeader: String = "Hora"
    override val futuresLockedTitle: String = "Par de Futuros Pro Bloqueado"
    override val futuresLockedDesc: String = "%s (%s) forma parte del nivel Pro. Desbloquea el libro de órdenes completo, arbitraje de base y datos de perpetuals."
    override val futuresLockedButton: String = "Desbloquear Acceso Pro"
    override val futuresSizePrefix: String = "Tamaño:"

    // AI Market Analyst Assistant
    override val aiAssistantTitle: String = "Analista de Mercado IA"
    override val aiAssistantBadge: String = "LIVE CC"
    override val aiAssistantSubtitle: String = "Inteligencia en Tiempo Real de Ciclos, Futuros y Ballenas"
    override val aiPromptPlaceholder: String = "Pregunta sobre ciclo BTC, funding, soporte, altseason..."
    override val aiAskButton: String = "Analizar"
    override val aiQuickActionCycle: String = "Ciclo y Riesgo Halving"
    override val aiQuickActionFutures: String = "Funding y Flujo de Apalancamiento"
    override val aiQuickActionWhales: String = "Acumulación de Ballenas"
    override val aiQuickActionAltseason: String = "Preparación Altseason"
    override val aiDisclaimer: String = "Desarrollado con modelos Gemini AI y telemetría en tiempo real. No es asesoramiento financiero."
    override val aiThinking: String = "Analizando telemetría y libro de órdenes en vivo..."
    override val aiGreeting: String = "Estoy aquí. ¿Qué te gustaría ver?"
    override val aiClearHistory: String = "Limpiar"
    override val aiLiveContextTag: String = "Datos en Vivo Conectados"
    override val aiPromptPrefixCycle: String = "Analiza la fase actual del ciclo halving, el riesgo y los análogos históricos."
    override val aiPromptPrefixFutures: String = "Interpreta las tasas de financiación actuales, el interés abierto y los riesgos de liquidación."
    override val aiPromptPrefixWhales: String = "¿Qué indican las alertas recientes de ballenas sobre acumulación o distribución institucional?"
    override val aiPromptPrefixAltseason: String = "Evalúa si las condiciones del mercado, el dominio de BTC y el sentimiento favorecen una Altseason ahora."
    override val backtestBadgeText: String = "Live whale radar · live order flow · live liquidations"
    override val derivativesRiskGuardrail: String = "Esta pantalla lee la cinta de perpetuos. No es un escritorio de trading y no dimensiona posiciones."

    // Market Intelligence Explainer Modal ("What is this & How it works")
    override val marketIntelligenceExplainerTitle: String = "Capa de Market Intelligence: Cómo Funciona"
    override val marketIntelligenceInfoButton: String = "¿Qué es esto?"
    override val marketIntelligenceConfidenceTitle: String = "Puntuación de Confianza (ej. 79%)"
    override val marketIntelligenceConfidenceDesc: String = "Mide la fuerza cuantitativa del posicionamiento actual en futuros según volumen, interés abierto y momentum."
    override val marketIntelligenceRegimesHeader: String = "Regímenes de Mercado (Qué significan las señales)"
    override val regimeShortSqueezeTitle: String = "Presión de Short Squeeze"
    override val regimeShortSqueezeDesc: String = "Fuertes posiciones en corto están atrapadas. Un leve movimiento alcista puede desatar liquidaciones en cascada y subidas bruscas."
    override val regimeSpotAccumulationTitle: String = "Acumulación Spot"
    override val regimeSpotAccumulationDesc: String = "Absorción de compras reales al contado en lugar de apalancamiento riesgoso. Señala una estructura de mercado sana y sostenible."
    override val regimeBalancedConsolidationTitle: String = "Consolidación Equilibrada"
    override val regimeBalancedConsolidationDesc: String = "El apalancamiento en derivados y la demanda al contado están en equilibrio, indicando operativa en rango."
    override val marketIntelligenceTelemetryHeader: String = "Telemetría Clave"
    override val telemetryOpenInterestTitle: String = "Open Interest (OI)"
    override val telemetryOpenInterestDesc: String = "Capital total bloqueado en contratos de derivados activos."
    override val telemetryFundingRateTitle: String = "Funding Rate"
    override val telemetryFundingRateDesc: String = "Comisión periódica entre longs y shorts. Tasas altamente positivas alertan de longs sobreapalancados propensos a caídas."
    override val marketIntelligenceUnderstood: String = "Entendido"
}
